### ISSUE TITLE
ncclient exception

### ISSUE THREAD

**Issue by abhikeshav** [CiscoDevNet/ydk-gen#10]
When running a series of YDK-Py apps, you may get the following thread exception:

> Exception in thread session (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/usr/local/lib/python2.7/dist-packages/ncclient/transport/ssh.py", line 554, in run <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'debug'

May be related to ncclient:

> Exception in thread session (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/home/gitlab-runner/builds/77b7020d/0/ydk-dev/ydk-gen/myenv/local/lib/python2.7/site-packages/ncclient/transport/ssh.py", line 556, in run
  File "/home/gitlab-runner/builds/77b7020d/0/ydk-dev/ydk-gen/myenv/local/lib/python2.7/site-packages/ncclient/transport/ssh.py", line 301, in close
  File "/home/gitlab-runner/builds/77b7020d/0/ydk-dev/ydk-gen/myenv/local/lib/python2.7/site-packages/paramiko/transport.py", line 644, in close
  File "/home/gitlab-runner/builds/77b7020d/0/ydk-dev/ydk-gen/myenv/local/lib/python2.7/site-packages/paramiko/transport.py", line 1536, in stop_thread
  File "/usr/lib/python2.7/threading.py", line 960, in join
  File "/usr/lib/python2.7/threading.py", line 363, in wait
<type 'exceptions.ValueError'>: list.remove(x): x not in list

**Comment by einarnn** [comment]
Abhi,

Is this an ncclient bug?

Cheers,

Einar

**Comment by abhikeshav** [comment]
Hi Einar,

Yes. This looks like a ncclient issue. I did find a similar issue on ncclient which was closed earlier (https://github.com/ncclient/ncclient/issues/38)

**Comment by einarnn** [comment]
That issue looks very similar, but is at the transport layer rather than the session layer. May be the same issue, I guess.

**Comment by abhikeshav** [comment]
Haven't seen this since a few months. closing as not reproducible
