### ISSUE TITLE
data tag not recognized when attribute present 

### ISSUE THREAD

**Issue by amoruck** [CiscoDevNet/ydk-gen#1021]
## Expected Behavior
Data tag should be correctly recognized

## Current Behavior
"ydk - ERROR - Cannot find 'data' tag in RPC reply from device".

## Steps to Reproduce
Query Arista switch with EOS 4.24.1.1F (tested with cEOS-lab-4.24.1.1F) for interface config

## Your Script
from ydk.services import NetconfService, Datastore
from ydk.providers import NetconfServiceProvider
from ydk.models.openconfig import openconfig_interfaces as oc_interfaces
import logging

def set_logger():
    logger = logging.getLogger("ydk")
    logger.setLevel(logging.INFO)
    handler = logging.StreamHandler()
    formatter = logging.Formatter(("%(asctime)s - %(name)s - "
                          "%(levelname)s - %(message)s"))
    handler.setFormatter(formatter)
    logger.addHandler(handler)

set_logger()
provider = NetconfServiceProvider(address="172.18.0.3",
                          port=830,
                          username="admin",
                          password="abc123",
                          protocol="ssh")

netconf = NetconfService()
interfaces = oc_interfaces.Interfaces()
interface = interfaces.Interface()
interface.name = 'Ethernet2'
interfaces.interface.append(interface)
cfg = netconf.get_config(provider, Datastore.running, interfaces)

## Logs
2020-07-29 19:44:00,581 - ydk - INFO - Path where models are to be downloaded: /root/.ydk/172.18.0.3
2020-07-29 19:44:00,588 - ydk - INFO - Connected to 172.18.0.3 on port 830 using ssh with timeout of -1
2020-07-29 19:44:00,599 - ydk - INFO - Executing 'get' RPC on [openconfig-interfaces:interfaces] from running
2020-07-29 19:44:00,607 - ydk - INFO - ============= Sending RPC to device =============
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><get-config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <source>
    <running/>
  </source>
  <filter><interfaces xmlns="http://openconfig.net/yang/interfaces">
  <interface>
    <name>Ethernet2</name>
  </interface>
</interfaces></filter>
</get-config>
</rpc>
2020-07-29 19:44:00,611 - ydk - INFO - ============= Received RPC from device =============
<?xml version="1.0"?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1">
  <data time-modified="2020-07-29T19:43:36.283176236Z">
    <interfaces xmlns="http://openconfig.net/yang/interfaces">
      <interface>
        <name>Ethernet2</name>
        <config>
          <description/>
          <enabled>true</enabled>
          <load-interval xmlns="http://arista.com/yang/openconfig/interfaces/augments">300</load-interval>
          <loopback-mode>false</loopback-mode>
          <mtu>0</mtu>
          <name>Ethernet2</name>
          <tpid xmlns="http://openconfig.net/yang/vlan" xmlns:oc-vlan-types="http://openconfig.net/yang/vlan-types">oc-vlan-types:TPID_0X8100</tpid>
          <type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type>
        </config>
        <ethernet xmlns="http://openconfig.net/yang/interfaces/ethernet">
          <config>
            <fec-encoding xmlns="http://arista.com/yang/openconfig/interfaces/augments">
              <disabled>false</disabled>
              <fire-code>false</fire-code>
              <reed-solomon>false</reed-solomon>
              <reed-solomon544>false</reed-solomon544>
            </fec-encoding>
            <forwarding-viable xmlns="http://openconfig.net/yang/hercules/interfaces">true</forwarding-viable>
            <mac-address>00:00:00:00:00:00</mac-address>
            <port-speed>SPEED_UNKNOWN</port-speed>
            <sfp-1000base-t xmlns="http://arista.com/yang/openconfig/interfaces/augments">false</sfp-1000base-t>
          </config>
          <pfc xmlns="http://arista.com/yang/openconfig/interfaces/augments"/>
          <switched-vlan xmlns="http://openconfig.net/yang/vlan">
            <config>
              <access-vlan>200</access-vlan>
              <interface-mode>ACCESS</interface-mode>
            </config>
          </switched-vlan>
        </ethernet>
        <hold-time>
          <config>
            <down>0</down>
            <up>0</up>
          </config>
        </hold-time>
        <subinterfaces>
          <subinterface>
            <index>0</index>
            <config>
              <description/>
              <enabled>true</enabled>
              <index>0</index>
            </config>
            <ipv4 xmlns="http://openconfig.net/yang/interfaces/ip">
              <config>
                <dhcp-client>false</dhcp-client>
                <enabled>false</enabled>
                <mtu>1500</mtu>
              </config>
              <unnumbered>
                <config>
                  <enabled>false</enabled>
                </config>
              </unnumbered>
            </ipv4>
            <ipv6 xmlns="http://openconfig.net/yang/interfaces/ip">
              <config>
                <dhcp-client>false</dhcp-client>
                <enabled>false</enabled>
                <mtu>1500</mtu>
              </config>
            </ipv6>
          </subinterface>
        </subinterfaces>
      </interface>
    </interfaces>
  </data>
</rpc-reply>

2020-07-29 19:44:00,612 - ydk - ERROR - Cannot find 'data' tag in RPC reply from device
<?xml version="1.0"?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1">
  <data time-modified="2020-07-29T19:43:36.283176236Z">
    <interfaces xmlns="http://openconfig.net/yang/interfaces">
      <interface>
        <name>Ethernet2</name>
        <config>
          <description/>
          <enabled>true</enabled>
          <load-interval xmlns="http://arista.com/yang/openconfig/interfaces/augments">300</load-interval>
          <loopback-mode>false</loopback-mode>
          <mtu>0</mtu>
          <name>Ethernet2</name>
          <tpid xmlns="http://openconfig.net/yang/vlan" xmlns:oc-vlan-types="http://openconfig.net/yang/vlan-types">oc-vlan-types:TPID_0X8100</tpid>
          <type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type>
        </config>
        <ethernet xmlns="http://openconfig.net/yang/interfaces/ethernet">
          <config>
            <fec-encoding xmlns="http://arista.com/yang/openconfig/interfaces/augments">
              <disabled>false</disabled>
              <fire-code>false</fire-code>
              <reed-solomon>false</reed-solomon>
              <reed-solomon544>false</reed-solomon544>
            </fec-encoding>
            <forwarding-viable xmlns="http://openconfig.net/yang/hercules/interfaces">true</forwarding-viable>
            <mac-address>00:00:00:00:00:00</mac-address>
            <port-speed>SPEED_UNKNOWN</port-speed>
            <sfp-1000base-t xmlns="http://arista.com/yang/openconfig/interfaces/augments">false</sfp-1000base-t>
          </config>
          <pfc xmlns="http://arista.com/yang/openconfig/interfaces/augments"/>
          <switched-vlan xmlns="http://openconfig.net/yang/vlan">
            <config>
              <access-vlan>200</access-vlan>
              <interface-mode>ACCESS</interface-mode>
            </config>
          </switched-vlan>
        </ethernet>
        <hold-time>
          <config>
            <down>0</down>
            <up>0</up>
          </config>
        </hold-time>
        <subinterfaces>
          <subinterface>
            <index>0</index>
            <config>
              <description/>
              <enabled>true</enabled>
              <index>0</index>
            </config>
            <ipv4 xmlns="http://openconfig.net/yang/interfaces/ip">
              <config>
                <dhcp-client>false</dhcp-client>
                <enabled>false</enabled>
                <mtu>1500</mtu>
              </config>
              <unnumbered>
                <config>
                  <enabled>false</enabled>
                </config>
              </unnumbered>
            </ipv4>
            <ipv6 xmlns="http://openconfig.net/yang/interfaces/ip">
              <config>
                <dhcp-client>false</dhcp-client>
                <enabled>false</enabled>
                <mtu>1500</mtu>
              </config>
            </ipv6>
          </subinterface>
        </subinterfaces>
      </interface>
    </interfaces>
  </data>
</rpc-reply>

Traceback (most recent call last):
  File "b.py", line 31, in <module>
    cfg = netconf.get_config(provider, Datastore.running, interfaces)
  File "/usr/local/lib/python3.6/dist-packages/ydk/services/netconf_service.py", line 108, in get_config
    return _ns_get(provider, source, read_filter, self._ns.get_config)
  File "/usr/local/lib/python3.6/dist-packages/ydk/services/netconf_service.py", line 165, in _ns_get
    top_result = ns_call(provider, top_filters)
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.6/dist-packages/ydk/errors/error_handler.py", line 82, in handle_runtime_error
    _raise(_exc)
  File "/usr/local/lib/python3.6/dist-packages/ydk/errors/error_handler.py", line 54, in _raise
    exec("raise exc from None")
  File "<string>", line 1, in <module>
ydk.errors.YServiceProviderError:  Cannot find 'data' tag in RPC reply
2020-07-29 19:44:00,624 - ydk - INFO - Disconnected from device

## System Information
Python 3.6.9
root@ydk:/var/tmp# pip freeze
bash: pip: command not found
root@ydk:/var/tmp# pip3 freeze
asn1crypto==0.24.0
chardet==3.0.4
cryptography==2.1.4
idna==2.6
keyring==10.6.0
keyrings.alt==3.0
pybind11==2.5.0
pycrypto==2.6.1
pygobject==3.26.1
python-apt==1.6.5+ubuntu0.3
python-debian==0.1.32
pyxdg==0.25
SecretStorage==2.3.1
six==1.11.0
ydk==0.8.4
ydk-models-ietf==0.1.5.post2
ydk-models-openconfig==0.1.8
root@ydk:/var/tmp# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

**Comment by amoruck** [comment]
[logs.txt](https://github.com/CiscoDevNet/ydk-gen/files/4997344/logs.txt)
attaching logs as file.

**Comment by 111pontes** [comment]
Thanks for sharing the problem.  Can you point to the standard that defines the `time-modified` attribute in the data tag?  I believe that attribute isn't defined in an RFC.

**Comment by amoruck** [comment]
Thanks for replay, please understand that I am not netconf expert, I have only noticed that my first "hello world" interaction with the device failed, and it seems the XML I'm receiving from the device has correct syntax (as long as XML and data tag presence is considered) 

So if it is really forbidden to add attributes to data tag in netconf response, and the correct behaviour is to throw an error not  just to ignore unknown attribute - it should be at least mentioned in error message, because now error message suggests that response parsing routine has some cognitive problems (it says tag cannot be found when the tag is in fact present).

**Comment by 111pontes** [comment]
The underlying issue is that your device is sending non-standard NETCONF messages that are confusing your script.  Having said that, I agree that, at a minimum, the error message needs to be improved since the data tag does exist in the payload sent from the router.  I'm marking this as an enhancement issue.

**Comment by amoruck** [comment]
So,  it seems that because of this confusion caused by additional XML attibute it is now impossible to to use ydk with Arista switches; Wouldn't it be possible to change ydk behavior to warn about unknown attribute being ignored?

**Comment by 111pontes** [comment]
Standards exist for a reason: to achieve interoperability (even at the cost of slower innovation).  Interoperability suffers when you deviate from a standard.  In this case, there is no debate on improving the error message.  Now, deciding on whether to silently ignore an unexpected attribute would require careful analysis on our part before deciding to change the implementation.  See the criticism of the [Robustness principle](https://en.wikipedia.org/wiki/Robustness_principle).

**Comment by amoruck** [comment]
I have tried to find some help on Arista forum, and [this](https://eos.arista.com/forum/time-modified-attribute-in-netconf-response/) is what they said. Unfortunately I am too noob in netconf to make anything useful out of it, so I'm leaving it here for reference;

**Comment by 111pontes** [comment]
Thanks for sharing.  The referenced comment describes what should be fixed on the network device to not violate the NETCONF standard.  That is a change required by the device vendor.  Furthermore, notice that the configuration data in your log file is not vendor neutral.  These are at least some of the vendor-specific nodes that are not part of the OpenConfig specification:
```
/interfaces/interface/config/load-interval
/interfaces/interface/ethernet/config/fec-encoding
/interfaces/interface/ethernet/config/sfp-100base-t
/interfaces/interface/ethernet/pfc
```
