### ISSUE TITLE
YModelError: Value "None" does not satisfy the constraint 

### ISSUE THREAD

**Issue by ldacol** [CiscoDevNet/ydk-gen#1057]
Issue tracker is ONLY used for reporting bugs. Please use the [YDK Community](https://communities.cisco.com/community/developer/ydk) for any support issues.

## Expected Behavior

masklength-range:  under openconfig-routing-policy:routing-policy should allow a value ([0-9]+\.\.[0-9]+)|exact

## Current Behavior

- masklength-range: exact

Value "None" does not satisfy the constraint "([0-9]+\.\.[0-9]+)|exact" (range, length, or pattern)
"exact" or any mask digits separated by .. will return "None" in the validation

## Steps to Reproduce

Run a encode Yang YAML to XML  

## Your Script

```
yang_xml = CODEC.encode(XML_PROVIDER, decoded_json_yang)


---
openconfig-routing-policy:routing-policy:
  defined-sets:
    prefix-sets:
      prefix-set:
        - name: DEFAULT
          prefixes:
            prefix:
               - ip-prefix: 0.0.0.0/0
               - masklength-range: exact
```

## Logs
Enable [logging](http://ydk.cisco.com/py/docs/guides/introduction.html#logging) and post the logs below

```
Traceback (most recent call last):
  File "convert.py", line 54, in <module>
    print(yang_yaml_to_xml(ARGS['yaml_file']))
  File "convert.py", line 40, in yang_yaml_to_xml
    yang_xml = CODEC.encode(XML_PROVIDER, decoded_json_yang)
  File "/opt/cteneteng/lib/python3.6/site-packages/ydk/errors/error_handler.py", line 112, in helper
    return func(self, provider, entity, *args, **kwargs)
  File "/opt/cteneteng/lib/python3.6/site-packages/ydk/services/codec_service.py", line 78, in encode
    return self._encode(provider, entity_holder, pretty, subtree)
  File "/opt/cteneteng/lib/python3.6/site-packages/ydk/services/codec_service.py", line 110, in _encode
    return result
  File "/export/apps/python/3.6.9/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/cteneteng/lib/python3.6/site-packages/ydk/errors/error_handler.py", line 82, in handle_runtime_error
    _raise(_exc)
  File "/opt/cteneteng/lib/python3.6/site-packages/ydk/errors/error_handler.py", line 54, in _raise
    exec("raise exc from None")
  File "<string>", line 1, in <module>
ydk.errors.YModelError:  Value "None" does not satisfy the constraint "([0-9]+\.\.[0-9]+)|exact" (range, length, or pattern). Path: /openconfig-routing-policy:routing-policy/defined-sets/prefix-sets/prefix-set[name='DEFAULT']/prefixes/prefix[ip-prefix='0.0.0.0/0'][masklength-range='None']/masklength-range
```

## System Information
ydk_models_openconfig-0.1.8-py3.6 models and libydk-0.8.5-1

**Comment by ygorelik** [comment]
I could not reproduce the issue. When model object is built properly the codec works as expected. Please read well the error message; it states: "Value **"None"** does not satisfy the constraint". Indeed, the _masklength-range_ value cannot be None. Most likely the error appears in translation of YAML description to JSON or XML, which is obviously not a part of YDK.

**Comment by ldacol** [comment]
Could you please provide the code example you run the test agains? 
In my case as you can see masklength-range is instantiated with the "exact" value or the mask and I am able to see the value in the  json file passed to the decode function: 

```
{'openconfig-routing-policy:routing-policy': {'policy-definitions': {'policy-definition': [{'name': 'PS-CTR-EXPORT-IPV4', 'statements': {'statement': [{'name': 'NEXT-HOP-SELF', 'conditions': {'config': {'install-protocol-eq': 'openconfig-policy-types:BGP'}}, 'actions': {'openconfig-bgp-policy:bgp-actions': {'config': {'set-next-hop': '10.0.0.1'}}}}]}}, {'name': 'PS-ISIS-EXPORT-IPV4', 'statements': {'statement': [{'name': 'AGGREGATE-ACCEPT', 'conditions': {'config': {'install-protocol-eq': 'openconfig-policy-types:LOCAL_AGGREGATE'}}, 'actions': {'config': {'policy-result': 'ACCEPT_ROUTE'}}}]}}, {'name': 'PS-CTR-IMPORT-IPV4', 'statements': {'statement': [{'name': 'DEFAULT-REJECT', 'conditions': {'match-prefix-set': {'config': {'prefix-set': 'DEFAULT'}}}, 'actions': {'config': {'policy-result': 'ACCEPT_ROUTE'}}}]}}]}, 'defined-sets': {'prefix-sets': {'prefix-set': [{'name': 'DEFAULT', 'prefixes': {'prefix': [{'ip-prefix': '0.0.0.0/0'}, {'masklength-range': 'exact'}]}}]}}}}
Traceback (most recent call last):
  File "convert_original.py", line 57, in <module>
    print(yang_yaml_to_xml(ARGS['yaml_file']))
  File "convert_original.py", line 43, in yang_yaml_to_xml
    yang_xml = CODEC.encode(XML_PROVIDER, decoded_json_yang)
  File "/opt/cteneteng/lib/python3.6/site-packages/ydk/errors/error_handler.py", line 112, in helper
    return func(self, provider, entity, *args, **kwargs)
  File "/opt/cteneteng/lib/python3.6/site-packages/ydk/services/codec_service.py", line 78, in encode
    return self._encode(provider, entity_holder, pretty, subtree)
  File "/opt/cteneteng/lib/python3.6/site-packages/ydk/services/codec_service.py", line 110, in _encode
    return result
  File "/export/apps/python/3.6.9/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/cteneteng/lib/python3.6/site-packages/ydk/errors/error_handler.py", line 82, in handle_runtime_error
    _raise(_exc)
  File "/opt/cteneteng/lib/python3.6/site-packages/ydk/errors/error_handler.py", line 54, in _raise
    exec("raise exc from None")
  File "<string>", line 1, in <module>
ydk.errors.YModelError:  Value "None" does not satisfy the constraint "([0-9]+\.\.[0-9]+)|exact" (range, length, or pattern). Path: /openconfig-routing-policy:routing-policy/defined-sets/prefix-sets/prefix-set[name='DEFAULT']/prefixes/prefix[ip-prefix='0.0.0.0/0'][masklength-range='None']/masklength-range
```

This is the python code I am using to convert from YAML to JSON and feed the result into the decode function. 

Thank yoiu
Luca

**Comment by ygorelik** [comment]
Here is the test case to check codec functionality on specific payload:
```
""" GitHub issue 1057
openconfig-routing-policy:routing-policy:
  defined-sets:
    prefix-sets:
      prefix-set:
        - name: DEFAULT
          prefixes:
            prefix:
               - ip-prefix: 0.0.0.0/0
               - masklength-range: exact
"""

from ydk.services.codec_service import CodecService, _get_yang_path
from ydk.providers import CodecServiceProvider
# from ydk.entity_utils import XmlSubtreeCodec,_get_bundle_name
# from ydk.path import Repository
from ydk.models.ydktest.openconfig_routing_policy import RoutingPolicy
import logging


def enable_logging(level):
    log = logging.getLogger('ydk')
    log.setLevel(level)
    handler = logging.StreamHandler()
    formatter = logging.Formatter("%(asctime)s - %(name)s - %(levelname)s - %(message)s")
    handler.setFormatter(formatter)
    log.addHandler(handler)


def run_test():
    prefix = RoutingPolicy.DefinedSets.PrefixSets.PrefixSet.Prefixes.Prefix()
    prefix.ip_prefix = '0.0.0.0/0'
    prefix.masklength_range = 'exact'

    prefix_set = RoutingPolicy.DefinedSets.PrefixSets.PrefixSet()
    prefix_set.prefix_set_name = 'DEFAULT'
    prefix_set.prefixes.prefix.append(prefix)

    policy = RoutingPolicy()
    policy.defined_sets.prefix_sets.prefix_set.append(prefix_set)

    codec_service = CodecService()
    xml_provider = CodecServiceProvider(type="xml")

    policy_xml = codec_service.encode(xml_provider, policy)

    return policy_xml


if __name__ == "__main__":
    """Execute main program."""
    enable_logging(logging.INFO)

    policy_xml = run_test()
    print(policy_xml)
```
And the output from YDK-0.8.6 docker:
```
root@ee1f81701716:~/ydk-gen/scripts# python data_validation_error.py 
<routing-policy xmlns="http://openconfig.net/yang/routing-policy">
  <defined-sets>
    <prefix-sets>
      <prefix-set>
        <prefix-set-name>DEFAULT</prefix-set-name>
        <prefixes>
          <prefix>
            <ip-prefix>0.0.0.0/0</ip-prefix>
            <masklength-range>exact</masklength-range>
          </prefix>
        </prefixes>
      </prefix-set>
    </prefix-sets>
  </defined-sets>
</routing-policy>

root@ee1f81701716:~/ydk-gen/scripts# 
```
