### ISSUE TITLE
Installation crashes

### ISSUE THREAD

**Issue by JonasKs** [CiscoDevNet/ydk-gen#1090]
I seem to be unable to use `ydk-py` due to installation issues. 

I get access denied to the [Cisco community](https://communities.cisco.com/community/developer/ydk). 

## Expected Behavior
`pip install` should work. 

## Current Behavior
Crashes, unable to build. 

## Steps to Reproduce
Use Python3.11 and try a `pip install` as per instructions.
Installing models such as `ydk-models-cisco-ios-xe` works fine. 

## Logs
Enable [logging](http://ydk.cisco.com/py/docs/guides/introduction.html#logging) and post the logs below

```
❯ pip install ydk           
Collecting ydk
  Using cached ydk-0.8.6.2.tar.gz (213 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pybind11==2.6.2 in ./.venv/lib/python3.11/site-packages (from ydk) (2.6.2)
Building wheels for collected packages: ydk
  Building wheel for ydk (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [148 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-13-arm64-cpython-311
      creating build/lib.macosx-13-arm64-cpython-311/ydk
      copying ydk/__init__.py -> build/lib.macosx-13-arm64-cpython-311/ydk
      copying ydk/exthook.py -> build/lib.macosx-13-arm64-cpython-311/ydk
      creating build/lib.macosx-13-arm64-cpython-311/ydk/filters
      copying ydk/filters/__init__.py -> build/lib.macosx-13-arm64-cpython-311/ydk/filters
      creating build/lib.macosx-13-arm64-cpython-311/ydk/types
      copying ydk/types/__init__.py -> build/lib.macosx-13-arm64-cpython-311/ydk/types
      copying ydk/types/py_types.py -> build/lib.macosx-13-arm64-cpython-311/ydk/types
      creating build/lib.macosx-13-arm64-cpython-311/ydk/_core
      copying ydk/_core/_importer.py -> build/lib.macosx-13-arm64-cpython-311/ydk/_core
      copying ydk/_core/_dm_meta_info.py -> build/lib.macosx-13-arm64-cpython-311/ydk/_core
      copying ydk/_core/__init__.py -> build/lib.macosx-13-arm64-cpython-311/ydk/_core
      creating build/lib.macosx-13-arm64-cpython-311/ydk/providers
      copying ydk/providers/netconf_provider.py -> build/lib.macosx-13-arm64-cpython-311/ydk/providers
      copying ydk/providers/__init__.py -> build/lib.macosx-13-arm64-cpython-311/ydk/providers
      copying ydk/providers/codec_provider.py -> build/lib.macosx-13-arm64-cpython-311/ydk/providers
      creating build/lib.macosx-13-arm64-cpython-311/ydk/path
      copying ydk/path/__init__.py -> build/lib.macosx-13-arm64-cpython-311/ydk/path
      creating build/lib.macosx-13-arm64-cpython-311/ydk/ext
      copying ydk/ext/__init__.py -> build/lib.macosx-13-arm64-cpython-311/ydk/ext
      creating build/lib.macosx-13-arm64-cpython-311/ydk/entity_utils
      copying ydk/entity_utils/__init__.py -> build/lib.macosx-13-arm64-cpython-311/ydk/entity_utils
      copying ydk/entity_utils/entity_utils.py -> build/lib.macosx-13-arm64-cpython-311/ydk/entity_utils
      creating build/lib.macosx-13-arm64-cpython-311/ydk/models
      copying ydk/models/__init__.py -> build/lib.macosx-13-arm64-cpython-311/ydk/models
      creating build/lib.macosx-13-arm64-cpython-311/ydk/errors
      copying ydk/errors/__init__.py -> build/lib.macosx-13-arm64-cpython-311/ydk/errors
      copying ydk/errors/error_handler.py -> build/lib.macosx-13-arm64-cpython-311/ydk/errors
      creating build/lib.macosx-13-arm64-cpython-311/ydk/logging
      copying ydk/logging/__init__.py -> build/lib.macosx-13-arm64-cpython-311/ydk/logging
      creating build/lib.macosx-13-arm64-cpython-311/ydk/services
      copying ydk/services/netconf_service.py -> build/lib.macosx-13-arm64-cpython-311/ydk/services
      copying ydk/services/__init__.py -> build/lib.macosx-13-arm64-cpython-311/ydk/services
      copying ydk/services/executor_service.py -> build/lib.macosx-13-arm64-cpython-311/ydk/services
      copying ydk/services/crud_service.py -> build/lib.macosx-13-arm64-cpython-311/ydk/services
      copying ydk/services/codec_service.py -> build/lib.macosx-13-arm64-cpython-311/ydk/services
      creating build/lib.macosx-13-arm64-cpython-311/ydk/path/sessions
      copying ydk/path/sessions/netconf_session.py -> build/lib.macosx-13-arm64-cpython-311/ydk/path/sessions
      copying ydk/path/sessions/__init__.py -> build/lib.macosx-13-arm64-cpython-311/ydk/path/sessions
      copying ydk/path/sessions/restconf_session.py -> build/lib.macosx-13-arm64-cpython-311/ydk/path/sessions
      creating build/lib.macosx-13-arm64-cpython-311/ydk/models/ydktest
      copying ydk/models/ydktest/openconfig_interfaces.py -> build/lib.macosx-13-arm64-cpython-311/ydk/models/ydktest
      copying ydk/models/ydktest/ydktest_sanity_typedefs.py -> build/lib.macosx-13-arm64-cpython-311/ydk/models/ydktest
      copying ydk/models/ydktest/openconfig_routing_policy.py -> build/lib.macosx-13-arm64-cpython-311/ydk/models/ydktest
      copying ydk/models/ydktest/ydktest_types.py -> build/lib.macosx-13-arm64-cpython-311/ydk/models/ydktest
      copying ydk/models/ydktest/openconfig_bgp_policy.py -> build/lib.macosx-13-arm64-cpython-311/ydk/models/ydktest
      copying ydk/models/ydktest/ydktest_filterread.py -> build/lib.macosx-13-arm64-cpython-311/ydk/models/ydktest
      copying ydk/models/ydktest/openconfig_policy_types.py -> build/lib.macosx-13-arm64-cpython-311/ydk/models/ydktest
      copying ydk/models/ydktest/openconfig_transport_types.py -> build/lib.macosx-13-arm64-cpython-311/ydk/models/ydktest
      copying ydk/models/ydktest/ydktest_aug_ietf_5.py -> build/lib.macosx-13-arm64-cpython-311/ydk/models/ydktest
      copying ydk/models/ydktest/ydktest_sanity.py -> build/lib.macosx-13-arm64-cpython-311/ydk/models/ydktest
      copying ydk/models/ydktest/ietf_inet_types.py -> build/lib.macosx-13-arm64-cpython-311/ydk/models/ydktest
      copying ydk/models/ydktest/ietf_netconf_monitoring.py -> build/lib.macosx-13-arm64-cpython-311/ydk/models/ydktest
      copying ydk/models/ydktest/__init__.py -> build/lib.macosx-13-arm64-cpython-311/ydk/models/ydktest
      copying ydk/models/ydktest/ietf_interfaces.py -> build/lib.macosx-13-arm64-cpython-311/ydk/models/ydktest
      copying ydk/models/ydktest/openconfig_types.py -> build/lib.macosx-13-arm64-cpython-311/ydk/models/ydktest
      copying ydk/models/ydktest/ietf_aug_base_2.py -> build/lib.macosx-13-arm64-cpython-311/ydk/models/ydktest
      copying ydk/models/ydktest/ietf_system.py -> build/lib.macosx-13-arm64-cpython-311/ydk/models/ydktest
      copying ydk/models/ydktest/ietf_netconf_with_defaults.py -> build/lib.macosx-13-arm64-cpython-311/ydk/models/ydktest
      copying ydk/models/ydktest/ietf_aug_base_1.py -> build/lib.macosx-13-arm64-cpython-311/ydk/models/ydktest
      copying ydk/models/ydktest/openconfig_platform.py -> build/lib.macosx-13-arm64-cpython-311/ydk/models/ydktest
      copying ydk/models/ydktest/iana_if_type.py -> build/lib.macosx-13-arm64-cpython-311/ydk/models/ydktest
      copying ydk/models/ydktest/openconfig_bgp_types.py -> build/lib.macosx-13-arm64-cpython-311/ydk/models/ydktest
      copying ydk/models/ydktest/ietf_netconf.py -> build/lib.macosx-13-arm64-cpython-311/ydk/models/ydktest
      copying ydk/models/ydktest/openconfig_bgp.py -> build/lib.macosx-13-arm64-cpython-311/ydk/models/ydktest
      copying ydk/models/ydktest/openconfig_terminal_device.py -> build/lib.macosx-13-arm64-cpython-311/ydk/models/ydktest
      copying ydk/models/ydktest/ietf_netconf_acm.py -> build/lib.macosx-13-arm64-cpython-311/ydk/models/ydktest
      copying ydk/models/ydktest/ydktest_sanity_types.py -> build/lib.macosx-13-arm64-cpython-311/ydk/models/ydktest
      copying ydk/models/ydktest/_yang_ns.py -> build/lib.macosx-13-arm64-cpython-311/ydk/models/ydktest
      copying ydk/models/ydktest/main.py -> build/lib.macosx-13-arm64-cpython-311/ydk/models/ydktest
      copying ydk/models/ydktest/openconfig_platform_types.py -> build/lib.macosx-13-arm64-cpython-311/ydk/models/ydktest
      copying ydk/models/ydktest/openconfig_if_ethernet.py -> build/lib.macosx-13-arm64-cpython-311/ydk/models/ydktest
      copying ydk/models/ydktest/oc_pattern.py -> build/lib.macosx-13-arm64-cpython-311/ydk/models/ydktest
      running build_ext
      -- The C compiler identification is AppleClang 14.0.3.14030022
      -- The CXX compiler identification is AppleClang 14.0.3.14030022
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      python version: 3.11
      -- Found PythonLibs: /opt/homebrew/Frameworks/Python.framework/Versions/3.11/lib/libpython3.11.dylib (found version "3.11.4")
      pybind11 include: /Users/jonas/Documents/code/yangtest/.venv/lib/python3.11/site-packages/pybind11/include
      -- Configuring done (0.7s)
      CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
      Please set them or make sure they are set and tested correctly in the CMake files:
      ssh_location
          linked by target "ydk_" in directory /private/var/folders/h5/84fbdwt95d321k0y7py_fq_h0000gn/T/pip-install-_4zixo1q/ydk_ef32dbad72494666a484b455adce89c4
      ssh_threads_location
          linked by target "ydk_" in directory /private/var/folders/h5/84fbdwt95d321k0y7py_fq_h0000gn/T/pip-install-_4zixo1q/ydk_ef32dbad72494666a484b455adce89c4
      ydk_location
          linked by target "ydk_" in directory /private/var/folders/h5/84fbdwt95d321k0y7py_fq_h0000gn/T/pip-install-_4zixo1q/ydk_ef32dbad72494666a484b455adce89c4
      
      -- Generating done (0.0s)
      CMake Generate step failed.  Build files cannot be regenerated correctly.
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/h5/84fbdwt95d321k0y7py_fq_h0000gn/T/pip-install-_4zixo1q/ydk_ef32dbad72494666a484b455adce89c4/setup.py", line 116, in <module>
          setup(
        File "/Users/jonas/Documents/code/yangtest/.venv/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/jonas/Documents/code/yangtest/.venv/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/Users/jonas/Documents/code/yangtest/.venv/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/Users/jonas/Documents/code/yangtest/.venv/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/Users/jonas/Documents/code/yangtest/.venv/lib/python3.11/site-packages/setuptools/dist.py", line 1244, in run_command
          super().run_command(command)
        File "/Users/jonas/Documents/code/yangtest/.venv/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/Users/jonas/Documents/code/yangtest/.venv/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 343, in run
          self.run_command("build")
        File "/Users/jonas/Documents/code/yangtest/.venv/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/Users/jonas/Documents/code/yangtest/.venv/lib/python3.11/site-packages/setuptools/dist.py", line 1244, in run_command
          super().run_command(command)
        File "/Users/jonas/Documents/code/yangtest/.venv/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/Users/jonas/Documents/code/yangtest/.venv/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/Users/jonas/Documents/code/yangtest/.venv/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/Users/jonas/Documents/code/yangtest/.venv/lib/python3.11/site-packages/setuptools/dist.py", line 1244, in run_command
          super().run_command(command)
        File "/Users/jonas/Documents/code/yangtest/.venv/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/h5/84fbdwt95d321k0y7py_fq_h0000gn/T/pip-install-_4zixo1q/ydk_ef32dbad72494666a484b455adce89c4/setup.py", line 74, in run
          self.build_extension(ext)
        File "/private/var/folders/h5/84fbdwt95d321k0y7py_fq_h0000gn/T/pip-install-_4zixo1q/ydk_ef32dbad72494666a484b455adce89c4/setup.py", line 105, in build_extension
          subprocess.check_call([cmake_executable, ext.sourcedir] + cmake_args, cwd=self.build_temp)
        File "/opt/homebrew/Cellar/python@3.11/3.11.4/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '/private/var/folders/h5/84fbdwt95d321k0y7py_fq_h0000gn/T/pip-install-_4zixo1q/ydk_ef32dbad72494666a484b455adce89c4', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/private/var/folders/h5/84fbdwt95d321k0y7py_fq_h0000gn/T/pip-install-_4zixo1q/ydk_ef32dbad72494666a484b455adce89c4/build/lib.macosx-13-arm64-cpython-311', '-DPYBIND11_INCLUDE=/Users/jonas/Documents/code/yangtest/.venv/lib/python3.11/site-packages/pybind11/include', '-DPYTHON_VERSION=3.11', '-DCMAKE_BUILD_TYPE=Release', '-DCOVERAGE=False']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for ydk
  Running setup.py clean for ydk
Failed to build ydk

```

## System Information

* Apple M1
* OS: Ventura 13.4.1

**Comment by JonasKs** [comment]
Seems like we get `0.8.6.2` from pip as well?

**Comment by ygorelik** [comment]
The ydk-py is not supported anymore. Please consider switching to ydk-gen release 0.8.6.4.
