### ISSUE TITLE
SIGSEGV or Connect Failed

### ISSUE THREAD

**Issue by achurak** [CiscoDevNet/ydk-gen#1095]
## Expected Behavior

gNMIServiceProvider can connect to nxos switches.

## Current Behavior

Inconsistent which is super odd - either 

`Process finished with exit code 139 (interrupted by signal 11:SIGSEGV)` 

or 

```
2024-02-12 16:03:43,996 - ydk - ERROR - CapabilityRequest failed with error:
Connect Failed
Traceback (most recent call last):
  File "/tmp/pycharm_project_997/src/main.py", line 41, in <module>
    main()
  File "/tmp/pycharm_project_997/src/main.py", line 28, in main
    provider = gNMIServiceProvider(
  File "/root/ydk_vne/lib/python3.10/site-packages/ydk/gnmi/providers/gnmi_provider.py", line 47, in __init__
    self.gsp.__init__(repo, address, port,
RuntimeError: YServiceProviderError: CapabilityRequest failed with error:
Connect Failed
```

## Steps to Reproduce

I'm quite literally simply creating a gnmi provider and point it to an nxos switch, nothing else at this point.
## Your Script

```
provider = gNMIServiceProvider(
        repo=Repository("/root/gnmi.repo"),
        address="x.x.x.x",
        username="gnmi",
        password="gnmi",
        port=57400,
        server_certificate="/usr/local/share/ca-certificates/n9kv01.selfsigned.crt",
    )
```

## Logs
I enabled `DEBUG` in the logger and the logs I posted above are the only ones I see. Also ydk.cisco.com domain doesn't seem to work anymore.

## System Information
Everything appeared to have compiled nicely on ubuntu jammy, python version is 3.10.12.

Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy

**Comment by ygorelik** [comment]
The current gNMI service code in YDK was built based on gNMI implementation on XR devices. It is known that gNMI implementations on XE and Nexus devices are different comparing to XR and therefore need new development in YDK.
