### ISSUE TITLE
Seeing a issue while passing a leaf element having a type as union with one of the variable is of type empty

### ISSUE THREAD

**Issue by rohanhiyer** [CiscoDevNet/ydk-gen#1101]
Issue tracker is ONLY used for reporting bugs. Please use the [YDK Community](https://communities.cisco.com/community/developer/ydk) for any support issues.

## Expected Behavior
Extract -o-ran-uplane-conf.yang

    leaf transmission-window-schedule {
      when "(../transmission-window-control = 'STATIC')";
      if-feature feat:STATIC-TRANSMISSION-WINDOW-CONTROL;
      type union {
        type empty;
        type leafref {
          path "/o-ran-uplane-conf:user-plane-configuration/o-ran-uplane-conf:transmission-window-schedules/o-ran-uplane-conf:id";
        }    
      }    

## Current Behavior
Seeing the following error while code generation - 

Processing 17 of 44 /mnt/data0/rohan.iyer/ws/new_ran_schema_cucp/ran-schema-cucp/Build/gcc_x86_64_x86-64_rocky_8.10/cucp-cm-5g/cucp_cm_5g-comp/ydk-gen/gen-api/.cache/models/ran_du_cm@0.0.0/o-ran-uplane-conf.yang
Meta_info_data.children is greater than 0  transmission-window-schedule [<ydkgen.printer.meta_data_util.MetaInfoData object at 0x7fcd3fb46f50>, None]
Traceback (most recent call last):
  File "/mnt/data0/rohan.iyer/ws/new_ran_schema_cucp/ran-schema-cucp/Build/gcc_x86_64_x86-64_rocky_8.10/cucp-cm-5g/cucp_cm_5g-comp/ydk-gen/generate.py", line 336, in <module>
    output_directory = (generator.generate(options.bundle))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data0/rohan.iyer/ws/new_ran_schema_cucp/ran-schema-cucp/Build/gcc_x86_64_x86-64_rocky_8.10/cucp-cm-5g/cucp_cm_5g-comp/ydk-gen/ydkgen/__init__.py", line 94, in generate
    return self._generate_bundle(description_file)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data0/rohan.iyer/ws/new_ran_schema_cucp/ran-schema-cucp/Build/gcc_x86_64_x86-64_rocky_8.10/cucp-cm-5g/cucp_cm_5g-comp/ydk-gen/ydkgen/__init__.py", line 150, in _generate_bundle
    generated_files = self._print_packages(packages, gen_api_root, curr_bundle)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data0/rohan.iyer/ws/new_ran_schema_cucp/ran-schema-cucp/Build/gcc_x86_64_x86-64_rocky_8.10/cucp-cm-5g/cucp_cm_5g-comp/ydk-gen/ydkgen/__init__.py", line 229, in _print_packages
    generated_files = ydk_printer.emit(bundle_packages, classes_per_source_file)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data0/rohan.iyer/ws/new_ran_schema_cucp/ran-schema-cucp/Build/gcc_x86_64_x86-64_rocky_8.10/cucp-cm-5g/cucp_cm_5g-comp/ydk-gen/ydkgen/printer/language_bindings_printer.py", line 64, in emit
    return self.print_files()
           ^^^^^^^^^^^^^^^^^^
  File "/mnt/data0/rohan.iyer/ws/new_ran_schema_cucp/ran-schema-cucp/Build/gcc_x86_64_x86-64_rocky_8.10/cucp-cm-5g/cucp_cm_5g-comp/ydk-gen/ydkgen/printer/cpp/cpp_bindings_printer.py", line 55, in print_files
    self._print_module(index, package, size)
  File "/mnt/data0/rohan.iyer/ws/new_ran_schema_cucp/ran-schema-cucp/Build/gcc_x86_64_x86-64_rocky_8.10/cucp-cm-5g/cucp_cm_5g-comp/ydk-gen/ydkgen/printer/cpp/cpp_bindings_printer.py", line 73, in _print_module
    self._print_cpp_rst_doc(package)
  File "/mnt/data0/rohan.iyer/ws/new_ran_schema_cucp/ran-schema-cucp/Build/gcc_x86_64_x86-64_rocky_8.10/cucp-cm-5g/cucp_cm_5g-comp/ydk-gen/ydkgen/printer/cpp/cpp_bindings_printer.py", line 137, in _print_cpp_rst_doc
    _walk_n_print(package, self.ydk_doc_dir)
  File "/mnt/data0/rohan.iyer/ws/new_ran_schema_cucp/ran-schema-cucp/Build/gcc_x86_64_x86-64_rocky_8.10/cucp-cm-5g/cucp_cm_5g-comp/ydk-gen/ydkgen/printer/cpp/cpp_bindings_printer.py", line 135, in _walk_n_print
    _walk_n_print(owned_element, p)
  File "/mnt/data0/rohan.iyer/ws/new_ran_schema_cucp/ran-schema-cucp/Build/gcc_x86_64_x86-64_rocky_8.10/cucp-cm-5g/cucp_cm_5g-comp/ydk-gen/ydkgen/printer/cpp/cpp_bindings_printer.py", line 135, in _walk_n_print
    _walk_n_print(owned_element, p)
  File "/mnt/data0/rohan.iyer/ws/new_ran_schema_cucp/ran-schema-cucp/Build/gcc_x86_64_x86-64_rocky_8.10/cucp-cm-5g/cucp_cm_5g-comp/ydk-gen/ydkgen/printer/cpp/cpp_bindings_printer.py", line 129, in _walk_n_print
    self.print_file(get_cpp_doc_file_name(p, named_element),
  File "/mnt/data0/rohan.iyer/ws/new_ran_schema_cucp/ran-schema-cucp/Build/gcc_x86_64_x86-64_rocky_8.10/cucp-cm-5g/cucp_cm_5g-comp/ydk-gen/ydkgen/printer/language_bindings_printer.py", line 97, in print_file
    emit_func(emit_args.ctx, emit_args.package, emit_args.extra_args)
  File "/mnt/data0/rohan.iyer/ws/new_ran_schema_cucp/ran-schema-cucp/Build/gcc_x86_64_x86-64_rocky_8.10/cucp-cm-5g/cucp_cm_5g-comp/ydk-gen/ydkgen/printer/cpp/cpp_bindings_printer.py", line 190, in emit_cpp_doc
    DocPrinter(ctx, 'cpp').print_module_documentation(named_element, identity_subclasses)
  File "/mnt/data0/rohan.iyer/ws/new_ran_schema_cucp/ran-schema-cucp/Build/gcc_x86_64_x86-64_rocky_8.10/cucp-cm-5g/cucp_cm_5g-comp/ydk-gen/ydkgen/printer/doc/doc_printer.py", line 54, in print_module_documentation
    self._print_class_rst(named_element)
  File "/mnt/data0/rohan.iyer/ws/new_ran_schema_cucp/ran-schema-cucp/Build/gcc_x86_64_x86-64_rocky_8.10/cucp-cm-5g/cucp_cm_5g-comp/ydk-gen/ydkgen/printer/doc/doc_printer.py", line 135, in _print_class_rst
    docstring = get_class_docstring(
                ^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data0/rohan.iyer/ws/new_ran_schema_cucp/ran-schema-cucp/Build/gcc_x86_64_x86-64_rocky_8.10/cucp-cm-5g/cucp_cm_5g-comp/ydk-gen/ydkgen/printer/meta_data_util.py", line 111, in get_class_docstring
    properties_description.extend(get_type_doc(meta_info_data, 1, '    '))
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data0/rohan.iyer/ws/new_ran_schema_cucp/ran-schema-cucp/Build/gcc_x86_64_x86-64_rocky_8.10/cucp-cm-5g/cucp_cm_5g-comp/ydk-gen/ydkgen/printer/meta_data_util.py", line 139, in get_type_doc
    properties_description.extend(get_type_doc(child, type_depth+1, ident+'    '))
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data0/rohan.iyer/ws/new_ran_schema_cucp/ran-schema-cucp/Build/gcc_x86_64_x86-64_rocky_8.10/cucp-cm-5g/cucp_cm_5g-comp/ydk-gen/ydkgen/printer/meta_data_util.py", line 133, in get_type_doc
    if len(meta_info_data.children) > 0:
           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'children'

## Steps to Reproduce

Please Download the yang files from the following path : 
https://specifications.o-ran.org/download?id=741

## Your Script

```

```

## Logs
Enable [logging](http://ydk.cisco.com/py/docs/guides/introduction.html#logging) and post the logs below

```

```

**Comment by ygorelik** [comment]
This issue has been addressed in the release 0.9.x, which you can find in [my fork in branch yang11](https://github.com/ygorelik/ydk-gen/tree/yang11). If you need this feature, please switch.
