### ISSUE TITLE
install_ydk script fails for python language on macOS

### ISSUE THREAD

**Issue by ygorelik** [CiscoDevNet/ydk-gen#1104]
## Current Behavior

When attempting to install YDK for Python language using _install_ydk.sh_ script the installation finishes successfully, but validation fails:
```
Successfully installed ydk-0.8.6.6

Code generation and installation completed successfully!

Total time taken:  32 seconds

*** Tue Dec  3 15:44:16 PST 2024 *** install_ydk.sh | Verifying Python YDK core package installation 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/ygorelik/github/venv3.10/lib/python3.10/site-packages/ydk/path/__init__.py", line 17, in <module>
    from ydk.ext.path import Annotation
  File "/Users/ygorelik/github/venv3.10/lib/python3.10/site-packages/ydk/exthook.py", line 86, in load_module
    raise ImportError('No module named %s' % fullname)
ImportError: No module named ydk.ext.path
*** Tue Dec  3 15:44:17 PST 2024 *** install_ydk.sh | Verification failed for the Python core package 'ydk_.so' 
```

## Steps to Reproduce

```
cd $YDK_HOME
export PYTHON_VENV=~/venv3.10
./install_ydk.sh --cpp --core --venv
./install_ydk.sh --py --core --venv
```

## System Information

macOS Sonoma (14.4)
YDK 0.8.6.6

**Comment by ygorelik** [comment]
The same issue appears in CLI:
```
(venv3.10) Yakovs-MacBook-Air:ydk-gen ygorelik$ source .env
(venv3.10) Yakovs-MacBook-Air:ydk-gen ygorelik$ python
Python 3.10.15 (main, Sep  7 2024, 00:20:06) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ydk.types
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ygorelik/github/venv3.10/lib/python3.10/site-packages/ydk/types/__init__.py", line 17, in <module>
    from .py_types import Entity, EntityCollection, Config, Filter, YList, YLeafList
  File "/Users/ygorelik/github/venv3.10/lib/python3.10/site-packages/ydk/types/py_types.py", line 37, in <module>
    from ydk_ import is_set
ImportError: dlopen(/Users/ygorelik/github/venv3.10/lib/python3.10/site-packages/ydk_.so, 0x0002): Library not loaded: libssh_threads.4.dylib
  Referenced from: <4587C173-7419-342F-930A-BF1FD1D9DC49> /Users/ygorelik/github/venv3.10/lib/python3.10/site-packages/ydk_.so
  Reason: tried: 'libssh_threads.4.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibssh_threads.4.dylib' (no such file), 'libssh_threads.4.dylib' (no such file), '/Users/ygorelik/github/ydk-gen/libssh_threads.4.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/ygorelik/github/ydk-gen/libssh_threads.4.dylib' (no such file), '/Users/ygorelik/github/ydk-gen/libssh_threads.4.dylib' (no such file)
>>> exit()
```

**Comment by ygorelik** [comment]
Resolved the issue for YDK releases 0.8.6.7 and 0.9.1.2.
