### ISSUE TITLE
Type validation broken

### ISSUE THREAD

**Issue by 111pontes** [CiscoDevNet/ydk-gen#116]
A simple type error isn't caught by YDK during validation:

https://github.com/CiscoDevNet/ydk-py-samples/blob/master/samples/basic/ydk/models/bgp/nc-create-config-bgp-40-ydk.py
```
43c43
<     bgp.global_.config.as_ = 65001
---
>     bgp.global_.config.as_ = "invalid as"
```
Error is finally caught by the app as a sever generated error.  The YDK app doesn't generate the AS config due to the type mismatch and the server complains about the missing config:
Traceback (most recent call last):
```
  File "./nc-create-config-bgp-44-ydk.py", line 103, in <module>
    crud.create(provider, bgp)  # create object on NETCONF device
  File "/usr/local/lib/python2.7/dist-packages/ydk/services/crud_service.py", line 56, in create
    self._execute_crud_operation_on_provider(provider, entity, 'CREATE', False)
  File "/usr/local/lib/python2.7/dist-packages/ydk/services/crud_service.py", line 146, in _execute_crud_operation_on_provider
    only_config
  File "/usr/local/lib/python2.7/dist-packages/ydk/services/service.py", line 31, in execute_payload
    payload)
  File "/usr/local/lib/python2.7/dist-packages/ydk/providers/_provider_plugin.py", line 172, in execute_operation
    return self._handle_rpc_reply(session_manager, optype, payload, reply_str)
  File "/usr/local/lib/python2.7/dist-packages/ydk/providers/_provider_plugin.py", line 190, in _handle_rpc_reply
    self._handle_rpc_error(session_manager, payload, reply_str, pathlist)
  File "/usr/local/lib/python2.7/dist-packages/ydk/providers/_provider_plugin.py", line 207, in _handle_rpc_error
    raise YPYError(YPYErrorCode.SERVER_REJ, reply_str)
ydk.errors.YPYError: Server rejected request.
	error-type: protocol
	error-tag: missing-element
	error-severity: error
	error-message: An expected element is missing.
	bad-element: as
```

**Comment by abhikeshav** [comment]
Need to make sure we catch all these errors in YDK local validation phase. Also, as part of a general fix for this, need to add a sanity unit test module (something like test_sanity_errors.py) for negative testing (testing *all* the different errors).
