### ISSUE TITLE
AttributeError exception when encoding BGP object

### ISSUE THREAD

**Issue by 111pontes** [CiscoDevNet/ydk-gen#119]
Issue may actually be caused by NETCONF service.  No exception is seen when CRUD read operation is used instead of NETCONF get-config.

```
Traceback (most recent call last):
  File "./nc-get-config-bgp-20-ydk.py", line 77, in <module>
    print(codec.encode(cd_provider, bgp))  # process object data
  File "/usr/local/lib/python2.7/dist-packages/ydk/services/codec_service.py", line 32, in encode
    MetaService.normalize_meta([], entity)
  File "/usr/local/lib/python2.7/dist-packages/ydk/services/meta_service.py", line 32, in normalize_meta
    deviation_tables = MetaService.get_active_deviation_tables(capabilities, entity)
  File "/usr/local/lib/python2.7/dist-packages/ydk/services/meta_service.py", line 39, in get_active_deviation_tables
    active_dmodule_names = get_active_deviation_module_names(capabilities, entity)
  File "/usr/local/lib/python2.7/dist-packages/ydk/services/meta_service.py", line 64, in get_active_deviation_module_names
    entity_module_name = entity._meta_info().module_name
AttributeError: 'str' object has no attribute '_meta_info'
```

**Comment by psykokwak4** [comment]
Might caused by MetaService, related to my commit, could you share this script?

Thanks,

**Comment by 111pontes** [comment]
Actually, the issue seems to be created by the NETCONF service.  It is not returning a YDK object, but an string with the XML encoded data.  That was confusing the encode operation in the Codec service which expects a YDK object.
