### ISSUE TITLE
Bug in error message handling

### ISSUE THREAD

**Issue by psykokwak4** [CiscoDevNet/ydk-gen#162]
> Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 859, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 732, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 471, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 331, in getMessage
    msg = str(self.msg)
  File "/home/gregorbr/oc-bgp/local/lib/python2.7/site-packages/ydk/errors.py", line 58, in __str__
    ret.append('\t{}: {}'.format(tag, r.text.strip()))
AttributeError: 'NoneType' object has no attribute 'append'
Logged from file openconfig-bgp-rib.py, line 41
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 859, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 732, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 471, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 331, in getMessage
    msg = str(self.msg)
  File "/home/gregorbr/oc-bgp/local/lib/python2.7/site-packages/ydk/errors.py", line 58, in __str__
    ret.append('\t{}: {}'.format(tag, r.text.strip()))
AttributeError: 'NoneType' object has no attribute 'append'
Logged from file openconfig-bgp-rib.py, line 41

**Comment by psykokwak4** [comment]
Confirmed with bug finder, this issue occurs in 0.4.0, and get fixed in later revised version.
