### ISSUE TITLE
Error when handling leaf-list of identityref type

### ISSUE THREAD

**Issue by abhikeshav** [CiscoDevNet/ydk-gen#186]
Below YDK script using [leaf-list of identityref type](https://github.com/CiscoDevNet/ydk-py/blob/master/ydk/models/routing/routing_policy.py#L1625) from openconfig routing-policy model produces the below error:

```python
from ydk.providers import NetconfServiceProvider
from ydk.services import CRUDService

from ydk.models.routing.routing_policy import RoutingPolicy
from ydk.models.bgp.bgp_types import BgpOriginAttrTypeEnum
from ydk.models.bgp.bgp_types import Ipv4UnicastIdentity

ncc = NativeNetconfServiceProvider(address='127.0.0.1' , username='admin', password='admin', port=12022)
crud = CRUDService()

bgp_conditions = RoutingPolicy.PolicyDefinitions.PolicyDefinition.Statements.Statement.Conditions.BgpConditions()
bgp_conditions.med_eq = 100
bgp_conditions.origin_eq = BgpOriginAttrTypeEnum.IGP
bgp_conditions.next_hop_in.append('1.2.3.4')
bgp_conditions.afi_safi_in = Ipv4UnicastIdentity()
bgp_conditions.local_pref_eq = 100
bgp_conditions.route_type = RoutingPolicy.PolicyDefinitions.PolicyDefinition.Statements.Statement.Conditions.BgpConditions.RouteTypeEnum.INTERNAL
conditions = RoutingPolicy.PolicyDefinitions.PolicyDefinition.Statements.Statement.Conditions()
statement = RoutingPolicy.PolicyDefinitions.PolicyDefinition.Statements.Statement()
statement.name = 'Hello'
statements = RoutingPolicy.PolicyDefinitions.PolicyDefinition.Statements()
statements.statement.append(statement)
statements = RoutingPolicy.PolicyDefinitions.PolicyDefinition.Statements()
policy_definition = RoutingPolicy.PolicyDefinitions.PolicyDefinition()
policy_definition.name = 'Hello'
policy_definitions = RoutingPolicy.PolicyDefinitions()
policy_definitions.policy_definition.append(policy_definition)
policy_definitions = RoutingPolicy.PolicyDefinitions()
routing_policy = RoutingPolicy()
policy_definitions.parent = routing_policy
policy_definition.parent = policy_definitions
statements.parent = policy_definition
statement.parent = statements
conditions.parent = statement
bgp_conditions.parent = conditions
crud.create(ncc, bgp_conditions)

ncc.close()
```

```
Traceback (most recent call last):
...

    self.crud.create(self.ncc, bgp_conditions)
  File "/ydk-gen/gen-api/python/ydk/services/crud_service.py", line 60, in create
    MetaService.normalize_meta(provider._get_capabilities(), entity)
  File "/ydk-gen/gen-api/python/ydk/services/meta_service.py", line 52, in normalize_meta
    MetaService.inject_imeta(entity, deviation_tables)
  File "/ydk-gen/gen-api/python/ydk/services/meta_service.py", line 96, in inject_imeta
    inject_imeta_helper(entity, deviation_tables)
  File "/ydk-gen/gen-api/python/ydk/services/meta_service.py", line 223, in inject_imeta_helper
    for v in value:
TypeError: 'Ipv4UnicastIdentity' object is not iterable
```

**Comment by abhikeshav** [comment]
Another issue is the encoding is not done correctly for leaf-list of identity-ref type. Below is current encoding.
```xml
              <bgp-conditions xmlns="http://openconfig.net/yang/bgp-policy">
                    <med-eq>100</med-eq>
                    <origin-eq>IGP</origin-eq>
                    <next-hop-in>1.2.3.4</next-hop-in>
```

**`<ipv4-unicast xmlns="http://openconfig.net/yang/bgp-types"/>`**

```
                    <local-pref-eq>100</local-pref-eq>
                    <route-type>INTERNAL</route-type>
                  </bgp-conditions>
```

This should be like the below:
                    **`<afi-saf-in xmlns:idx="http://openconfig.net/yang/bgp-types">idx:ipv4-unicast</afi-safi-in>`**

**Comment by psykokwak4** [comment]
The `BgpConditions.afi_safi_in` is a list not leaf-list.
