### ISSUE TITLE
TCP support for ncclient is not supported

### ISSUE THREAD

**Issue by GregoryBrown** [CiscoDevNet/ydk-gen#2]
When trying to connect via tcp, ydk throws an error:

Establishing connection with device 10.8.19.3:830 using tcp:
Traceback (most recent call last):
  File "yang_mplste_oper.py", line 53, in <module>
    main()
  File "yang_mplste_oper.py", line 39, in main
    session = NetconfServiceProvider(address=o.host, port=o.port, username = o.username, password = o.password, protocol = o.proto)
  File "/home/gregorbr/yang_test/local/lib/python2.7/site-packages/ydk/providers/netconf_provider.py", line 66, in __init__
    self._session_config,
AttributeError: 'NetconfServiceProvider' object has no attribute ‘_session_config'

Looks like NetconfServiceProvider passes tcp to ncclient in which it is not supported.

Proposed fixed:

Disable tcp support.

**Comment by einarnn** [comment]
I agree that we should disable plaintext TCP.
