### ISSUE TITLE
python setup.py develop doesn't work under gen-api/python

### ISSUE THREAD

**Issue by siming85** [CiscoDevNet/ydk-gen#228]
after a generation,
`pip install gen-api/python/dist/<file>.tar.gz` works fine. this installed the generated pip package

However if we just do `python gen-api/python/setup.py develop`, it appears to setup fine, but the ydk package goes missing altogether.

environment:
- one dedicated virtual environment for ydk-gen
- another virtual environment for installing/testing the generated ydk package.
(eg, there are no conflicting namespaces/packages/etc)

```

(ydk) [siyuan@siyuan-lnx:ydk]$ python ydk-gen/gen-api/python/setup.py develop
running develop
running egg_info
creating ydk.egg-info
writing ydk.egg-info/PKG-INFO
writing requirements to ydk.egg-info/requires.txt
writing dependency_links to ydk.egg-info/dependency_links.txt
writing top-level names to ydk.egg-info/top_level.txt
writing manifest file 'ydk.egg-info/SOURCES.txt'
warning: manifest_maker: standard file 'setup.py' not found

reading manifest file 'ydk.egg-info/SOURCES.txt'
writing manifest file 'ydk.egg-info/SOURCES.txt'
running build_ext
Creating /ydk/lib/python3.4/site-packages/ydk.egg-link (link to .)
Adding ydk 0.4.0 to easy-install.pth file

Installed /ydk
Processing dependencies for ydk==0.4.0
Searching for ncclient==0.5.2
Best match: ncclient 0.5.2
Adding ncclient 0.5.2 to easy-install.pth file

Using /ydk/lib/python3.4/site-packages
Searching for protobuf==3.0.0b2.post2
Best match: protobuf 3.0.0b2.post2
Adding protobuf 3.0.0b2.post2 to easy-install.pth file

Using /ydk/lib/python3.4/site-packages
Searching for Twisted==16.3.2
Best match: Twisted 16.3.2
Adding Twisted 16.3.2 to easy-install.pth file

Using /ydk/lib/python3.4/site-packages
Searching for pycrypto==2.6.1
Best match: pycrypto 2.6.1
Adding pycrypto 2.6.1 to easy-install.pth file

Using /ydk/lib/python3.4/site-packages
Searching for pyang==1.6
Best match: pyang 1.6
Adding pyang 1.6 to easy-install.pth file

Using /ydk/lib/python3.4/site-packages
Searching for paramiko==1.15.2
Best match: paramiko 1.15.2
Adding paramiko 1.15.2 to easy-install.pth file

Using /ydk/lib/python3.4/site-packages
Searching for lxml==3.4.4
Best match: lxml 3.4.4
Adding lxml 3.4.4 to easy-install.pth file

Using /ydk/lib/python3.4/site-packages
Searching for enum34==1.1.3
Best match: enum34 1.1.3
Adding enum34 1.1.3 to easy-install.pth file

Using /ydk/lib/python3.4/site-packages
Searching for ecdsa==0.13
Best match: ecdsa 0.13
Adding ecdsa 0.13 to easy-install.pth file

Using /ydk/lib/python3.4/site-packages
Searching for six==1.9.0
Best match: six 1.9.0
Adding six 1.9.0 to easy-install.pth file

Using /ydk/lib/python3.4/site-packages
Searching for setuptools==25.0.1
Best match: setuptools 25.0.1
Adding setuptools 25.0.1 to easy-install.pth file
Installing easy_install script to /ydk/bin
Installing easy_install-3.5 script to /ydk/bin

Using /ydk/lib/python3.4/site-packages
Searching for zope.interface==4.2.0
Best match: zope.interface 4.2.0
Adding zope.interface 4.2.0 to easy-install.pth file

Using /ydk/lib/python3.4/site-packages
Finished processing dependencies for ydk==0.4.0
(ydk) bash$ python
Python 3.4.1 (default, Nov 12 2014, 13:34:48) 
[GCC 4.4.6 20120305 (Red Hat 4.4.6-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ydk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'ydk'
>>> 

```

**Comment by siming85** [comment]
and also this breaks the virtual environment :(

trying to install the actual .tar.gz file no longer works
```

(ydk) bash$ pip uninstall ydk
Uninstalling ydk-0.4.0:
  /ydk/lib/python3.4/site-packages/ydk.egg-link
Proceed (y/n)? y
  Successfully uninstalled ydk-0.4.0
(ydk) bash$ pip install ../ydk-gen/ydk-gen/gen-api/python/dist/ydk-0.4.0.tar.gz 
Processing /ydk-gen/ydk-gen/gen-api/python/dist/ydk-0.4.0.tar.gz
  Requirement already satisfied (use --upgrade to upgrade): ydk==0.4.0 from file:///ydk-gen/ydk-gen/gen-api/python/dist/ydk-0.4.0.tar.gz in /ydk
Requirement already satisfied (use --upgrade to upgrade): ecdsa==0.13 in ./lib/python3.4/site-packages (from ydk==0.4.0)
Requirement already satisfied (use --upgrade to upgrade): enum34==1.1.3 in ./lib/python3.4/site-packages (from ydk==0.4.0)
Requirement already satisfied (use --upgrade to upgrade): lxml==3.4.4 in ./lib/python3.4/site-packages (from ydk==0.4.0)
Requirement already satisfied (use --upgrade to upgrade): paramiko==1.15.2 in ./lib/python3.4/site-packages (from ydk==0.4.0)
Requirement already satisfied (use --upgrade to upgrade): pyang==1.6 in ./lib/python3.4/site-packages (from ydk==0.4.0)
Requirement already satisfied (use --upgrade to upgrade): pycrypto==2.6.1 in ./lib/python3.4/site-packages (from ydk==0.4.0)
Requirement already satisfied (use --upgrade to upgrade): Twisted>=16.0.0 in ./lib/python3.4/site-packages (from ydk==0.4.0)
Requirement already satisfied (use --upgrade to upgrade): protobuf==3.0.0b2.post2 in ./lib/python3.4/site-packages (from ydk==0.4.0)
Requirement already satisfied (use --upgrade to upgrade): ncclient>=0.4.7 in ./lib/python3.4/site-packages (from ydk==0.4.0)
Requirement already satisfied (use --upgrade to upgrade): zope.interface>=4.0.2 in ./lib/python3.4/site-packages (from Twisted>=16.0.0->ydk==0.4.0)
Requirement already satisfied (use --upgrade to upgrade): six>=1.9 in ./lib/python3.4/site-packages (from protobuf==3.0.0b2.post2->ydk==0.4.0)
Requirement already satisfied (use --upgrade to upgrade): setuptools in ./lib/python3.4/site-packages (from protobuf==3.0.0b2.post2->ydk==0.4.0)
(ydk) bash$ python
Python 3.4.1 (default, Nov 12 2014, 13:34:48) 
[GCC 4.4.6 20120305 (Red Hat 4.4.6-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ydk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'ydk'
>>> 

```

**Comment by abhikeshav** [comment]
Not able to reproduce this on my Mac. I created a new virtualenv and executed ```python gen-api/python/setup.py develop```, which successfully installed ydk+all dependencies.

Not sure how to fix the broken virtualenv, other than deleting it and recreating a new one?

**Comment by siming85** [comment]
yeah, have to delete it and re-create it.

**Comment by abhikeshav** [comment]
Assuming this has been fixed/cannot reproduce. Let me know if this is happening again
