### ISSUE TITLE
For errors reported directly by server (not caught by validation), rpc-reply error-tag, error-info should be reported

### ISSUE THREAD

**Issue by abhikeshav** [CiscoDevNet/ydk-gen#23]
I ran across an issue where the yang models were incorrectly loaded/wrong version of yang models were loaded to the server. So, when I ran the sanity tests, the validation mechanism did not catch the error since the payload was valid. However, the server rejected them because of mismatched model. For this case, I think the error-tag and error-info from the RPC error can be captured in the exception raised, so that the user has a clear idea why the server rejected the request.

**Comment by abhikeshav** [comment]
Already fixed:
```
Traceback (most recent call last):
  File "tests/test_sanity_types.py", line 508, in test_union_int
    self.crud.create(self.ncc, runner)
  File "/root/ydk-gen/gen-api/python/ydk/services/crud_service.py", line 56, in create
    self._execute_crud_operation_on_provider(provider, entity, 'CREATE', False)
  File "/root/ydk-gen/gen-api/python/ydk/services/crud_service.py", line 146, in _execute_crud_operation_on_provider
    only_config
  File "/root/ydk-gen/gen-api/python/ydk/services/service.py", line 31, in execute_payload
    payload)
  File "/root/ydk-gen/gen-api/python/ydk/providers/_provider_plugin.py", line 172, in execute_operation
    return self._handle_rpc_reply(session_manager, optype, payload, reply_str)
  File "/root/ydk-gen/gen-api/python/ydk/providers/_provider_plugin.py", line 190, in _handle_rpc_reply
    self._handle_rpc_error(session_manager, payload, reply_str, pathlist)
  File "/root/ydk-gen/gen-api/python/ydk/providers/_provider_plugin.py", line 207, in _handle_rpc_error
    raise YPYError(YPYErrorCode.SERVER_REJ, reply_str)
YPYError: Server rejected request.
	error-type: protocol
	error-tag: unknown-element
	error-severity: error
	error-path: /rpc/edit-config/config/ydkut:runner/ydkut:ytypes/ydkut:built-in-t
	bad-element: enum-int-value
```
