### ISSUE TITLE
Copy config in NetconfService doesn't accept entity as source

### ISSUE THREAD

**Issue by 111pontes** [CiscoDevNet/ydk-gen#248]
`copy_config` method doesn't accept an entity as configuration source:

```
Traceback (most recent call last):
  File "./nc-copy-config-xr-clns-isis-cfg-20-ydk.py", line 125, in <module>
    netconf.copy_config(provider, Datastore.candidate, isis)
  File "/home/saalvare/.virtualenvs/ydk-0.5.0/local/lib/python2.7/site-packages/ydk/services/netconf_service.py", line 181, in copy_config
    rpc.input.source = _get_rpc_datastore_object(source, rpc.input.source)
  File "/home/saalvare/.virtualenvs/ydk-0.5.0/local/lib/python2.7/site-packages/ydk/services/netconf_service.py", line 461, in _get_rpc_datastore_object
    raise YPYModelError('Invalid datastore specified')
ydk.errors.YPYModelError: Invalid datastore specified
```

[copy-config RPC definition](https://tools.ietf.org/html/rfc6241#section-7.3) describes source as:
> source:  Name of the configuration datastore to use as the source
>         of the `<copy-config>` operation, or the <config> element
>         containing the complete configuration to copy.

**Comment by 111pontes** [comment]
`validate` RPC has a similar source definition:

>      source:
>
>            Name of the configuration datastore to validate, such as
>            <candidate>, or the <config> element containing the complete
>            configuration to validate.

In its current implementation, it has two arguments: `source`, which takes a datastore enum, and `config`, which takes an entity.  The description of the latter is actually missing in the 0.5.0 documentation.  Both the `copy_config` and `validate` methods should use the same interface to provide a datastore or a entity as a source.
