### ISSUE TITLE
Attempt to assign non YDK entity object of type OverloadBits to Isis.Instances.Instance.OverloadBits

### ISSUE THREAD

**Issue by 111pontes** [CiscoDevNet/ydk-gen#320]
[ISIS Codec sample apps](https://git.io/v1Cax) break with YDK 0.5.2

```
Traceback (most recent call last):
  File "./cd-encode-xr-clns-isis-cfg-20-ydk.py", line 119, in <module>
    print(codec.encode(provider, isis))
  File "/usr/local/lib/python2.7/dist-packages/ydk/services/codec_service.py", line 40, in encode
    payload = self.operate_on_object_or_dictionary(entity, CodecService._encode_entity, [encoder])
  File "/usr/local/lib/python2.7/dist-packages/ydk/services/service.py", line 32, in operate_on_object_or_dictionary
    result = function(entity, *args)
  File "/usr/local/lib/python2.7/dist-packages/ydk/services/codec_service.py", line 60, in _encode_entity
    MetaService.normalize_meta([], entity)
  File "/usr/local/lib/python2.7/dist-packages/ydk/services/meta_service.py", line 68, in normalize_meta
    MetaService.inject_imeta(entity, deviation_tables)
  File "/usr/local/lib/python2.7/dist-packages/ydk/services/meta_service.py", line 108, in inject_imeta
    _inject_imeta_helper(entity)
  File "/usr/local/lib/python2.7/dist-packages/ydk/services/meta_service.py", line 232, in _inject_imeta_helper
    _inject_imeta_helper(value, deviation_table, entity.i_meta)
  File "/usr/local/lib/python2.7/dist-packages/ydk/services/meta_service.py", line 230, in _inject_imeta_helper
    _inject_imeta_helper(v, deviation_table, entity.i_meta)
  File "/usr/local/lib/python2.7/dist-packages/ydk/services/meta_service.py", line 226, in _inject_imeta_helper
    _check_type_mismatch(value, member)
  File "/usr/local/lib/python2.7/dist-packages/ydk/services/meta_service.py", line 245, in _check_type_mismatch
    value.__class__.__name__, member.clazz_name))
ydk.errors.YPYServiceError: Attempt to assign non YDK entity object of type OverloadBits to Isis.Instances.Instance.OverloadBits
```

**Comment by 111pontes** [comment]
Somewhat related to issue #303 The `overload-bits` YANG node results in a class `OverloadBits` which is assumed to be of `bits` type.  Fixing #303 should take care of this defect.
