### ISSUE TITLE
Incorrect subtree filter using NETCONF service

### ISSUE THREAD

**Issue by 111pontes** [CiscoDevNet/ydk-gen#441]
When trying to read `/software-install/active` from `Cisco-IOS-XR-spirit-install-instmgr-oper.yang`, the subtree filter has `active` as the model root instead of `software-install` when using the `NETCONF` service:

```python
    # create NETCONF service
    netconf = NetconfService()

    software_install = xr_spirit_install_instmgr_oper.SoftwareInstall()  # create object

    # get data from NETCONF device
    software_install = netconf.get(provider, software_install.active)
```

```xml
2017-04-04 09:28:08,819 - ydk.providers.netconf_provider - INFO - NetconfServiceProvider connected to host:None using ssh
2017-04-04 09:28:08,820 - ydk.services.netconf_service - INFO - Executing get RPC
2017-04-04 09:28:08,826 - ydk.services.executor_service - INFO - Executor operation initiated
2017-04-04 09:28:08,827 - ydk.providers._provider_plugin - DEBUG - 
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:1f4747d4-89bb-4107-ace2-48ffe66cce7a">
  <get>
    <filter>
      <active xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-spirit-install-instmgr-oper"/>
    </filter>
  </get>
</rpc>

2017-04-04 09:28:09,093 - ydk.providers._provider_plugin - DEBUG - 
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:1f4747d4-89bb-4107-ace2-48ffe66cce7a">
  <rpc-error>
    <error-type>protocol</error-type>
    <error-tag>unknown-element</error-tag>
    <error-severity>error</error-severity>
    <error-path xmlns:ns1="http://cisco.com/ns/yang/Cisco-IOS-XR-spirit-install-instmgr-oper">ns1:active</error-path>
    <error-info>
      <bad-element>active</bad-element>
    </error-info>
  </rpc-error>
</rpc-reply>

2017-04-04 09:28:09,093 - ydk.providers._provider_plugin - ERROR - 
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:1f4747d4-89bb-4107-ace2-48ffe66cce7a">
  <get>
    <filter>
      <active xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-spirit-install-instmgr-oper"/>
    </filter>
  </get>
</rpc>

<?xml version="1.0"?>
<rpc-reply message-id="urn:uuid:1f4747d4-89bb-4107-ace2-48ffe66cce7a" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
 <rpc-error>
  <error-type>protocol</error-type>
  <error-tag>unknown-element</error-tag>
  <error-severity>error</error-severity>
  <error-path xmlns:ns1="http://cisco.com/ns/yang/Cisco-IOS-XR-spirit-install-instmgr-oper">ns1:active</error-path>
  <error-info>
   <bad-element>active</bad-element>
  </error-info>
 </rpc-error>
</rpc-reply>

2017-04-04 09:28:09,094 - ydk.services.executor_service - INFO - Executor operation completed
Traceback (most recent call last):
  File "./nc-get-xr-spirit-install-instmgr-oper-99-ydk.py", line 78, in <module>
    software_install = netconf.get(provider, software_install.active)
  File "/usr/local/lib/python2.7/dist-packages/ydk/services/netconf_service.py", line 377, in get
    payload = self.executor.execute_rpc(provider, rpc)
  File "/usr/local/lib/python2.7/dist-packages/ydk/services/executor_service.py", line 58, in execute_rpc
    ''
  File "/usr/local/lib/python2.7/dist-packages/ydk/providers/netconf_provider.py", line 94, in execute
    return self.sp_instance.execute_operation(payload, operation)
  File "/usr/local/lib/python2.7/dist-packages/ydk/providers/_provider_plugin.py", line 224, in execute_operation
    return self._handle_rpc_reply(operation, payload, reply.xml)
  File "/usr/local/lib/python2.7/dist-packages/ydk/providers/_provider_plugin.py", line 246, in _handle_rpc_reply
    self._handle_rpc_error(payload, reply_str, pathlist)
  File "/usr/local/lib/python2.7/dist-packages/ydk/providers/_provider_plugin.py", line 259, in _handle_rpc_error
    raise YPYServiceProviderError(error_code=YPYErrorCode.SERVER_REJ, error_msg=reply_str)
ydk.errors.YPYServiceProviderError: Server rejected request.
	error-type: protocol
	error-tag: unknown-element
	error-severity: error
	error-path: ns1:active
	bad-element: active
```

When using `CRUD` service, the subtree filter is built correctly:

```Python
    # create CRUD service
    crud = CRUDService()

    software_install = xr_spirit_install_instmgr_oper.SoftwareInstall()  # create object

    # read data from NETCONF device
    software_install = crud.read(provider, software_install.active)
```

```xml
2017-04-04 09:49:55,563 - ydk.providers.netconf_provider - INFO - NetconfServiceProvider connected to host:None using ssh
2017-04-04 09:49:55,565 - ydk.services.crud_service - INFO - READ operation initiated
2017-04-04 09:49:55,565 - ydk.providers._provider_plugin - DEBUG - 
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:d4844ef6-3e1d-43d5-a44a-0a17be463428">
  <get>
    <filter type="subtree">
      <software-install xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-spirit-install-instmgr-oper">
        <active/>
      </software-install>
    </filter>
  </get>
</rpc>

2017-04-04 09:49:56,181 - ydk.providers._provider_plugin - DEBUG - 
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:d4844ef6-3e1d-43d5-a44a-0a17be463428">
  <data>
    <software-install xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-spirit-install-instmgr-oper">
      <active>
        <active-package-info>
          <error-message/>
          <location>0/RP0/CPU0</location>
          <node-type>RP</node-type>
          <boot-partition-name>xr_lv0</boot-partition-name>
          <number-of-active-packages>1</number-of-active-packages>
          <active-packages>
        xrv9k-xr-6.2.1 version=6.2.1 [Boot image]
</active-packages>
        </active-package-info>
        <active-package-info>
          <error-message/>
          <location>0/0/CPU0</location>
          <node-type>LC</node-type>
          <boot-partition-name>xr_lcp_lv0</boot-partition-name>
          <number-of-active-packages>1</number-of-active-packages>
          <active-packages>
        xrv9k-xr-6.2.1 version=6.2.1 [Boot image]
</active-packages>
        </active-package-info>
      </active>
    </software-install>
  </data>
</rpc-reply>

2017-04-04 09:49:56,182 - ydk.services.crud_service - INFO - READ operation completed
2017-04-04 09:49:56,577 - ydk.providers.netconf_provider - INFO - NetconfServiceProvider disconnected from host using ssh
```

The issue doesn't occur when using `libydk`.

**Comment by psykokwak4** [comment]
Hi Santiago,

Is `software_install = crud.read(provider, software_install.active)` supposed to be `software_install = crud.read(provider, software_install)`?

**Comment by psykokwak4** [comment]
Sorry, didn't read the issue carefully, so the payload for NetconfService should be same as the one created through CRUD(`<filter type="subtree">` and `software-install` as root)?

**Comment by 111pontes** [comment]
Correct.  The filter currently generated for the `NETCONF` service is invalid.

**Comment by ygorelik** [comment]
The XR software got changed and the issue with the latest 0.8.4 code is not reproducible.

New script:
```
#!/usr/bin/env python

import argparse
import logging

from urllib.parse import urlparse

from ydk.services import NetconfService
from ydk.providers import NetconfServiceProvider
from ydk.models.ydktest_xr import Cisco_IOS_XR_spirit_install_instmgr_oper as xr

from test_utils import enable_logging


if __name__ == "__main__":
    """Execute main program."""

    parser = argparse.ArgumentParser()
    parser.add_argument("-v", "--verbose",
                        help="print debugging messages",
                        action="store_true")
    parser.add_argument("device",
                        help="NETCONF device (ssh://user:password@host:port)")
    args = parser.parse_args()
    device = urlparse(args.device)

    if args.verbose:
        enable_logging(logging.INFO)

    # create NETCONF provider and service
    provider = NetconfServiceProvider(address=device.hostname,
                                      port=device.port,
                                      username=device.username,
                                      password=device.password,
                                      protocol=device.scheme)
    ns = NetconfService()

    # NI configuration
    software_install = xr.Install()  # create object

    # get data from NETCONF device
    active_software = ns.get(provider, software_install.packages.active)
    for active_package in active_software.summary.package:
        print(active_package.name, active_package.version, active_package.release)
```
Produces this result:
```
2019-09-09 12:22:14,611 - ydk - INFO - Path where models are to be downloaded: /home/yan/.ydk/10.30.110.85
2019-09-09 12:22:14,623 - ydk - INFO - Connected to 10.30.110.85 on port 830 using ssh with timeout of -1
2019-09-09 12:22:14,638 - ydk - INFO - Executing 'get' RPC on [Cisco-IOS-XR-spirit-install-instmgr-oper:install]
2019-09-09 12:22:14,649 - ydk - INFO - ============= Sending RPC to device =============
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><get xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <filter><install xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-spirit-install-instmgr-oper">
  <packages>
    <active/>
  </packages>
</install></filter>
</get>
</rpc>
2019-09-09 12:22:15,682 - ydk - INFO - ============= Received RPC from device =============
<?xml version="1.0"?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1">
  <data>
    <install xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-spirit-install-instmgr-oper">
      <packages>
        <active>
          <nodes>
            <node>
              <node>0/RP0/CPU0</node>
              <package>
                <name>xrv9k-xr</name>
                <version>7.0.1.145I</version>
                <release>r701145I</release>
              </package>
            </node>
            <node>
              <node>0/0/CPU0</node>
              <package>
                <name>xrv9k-xr</name>
                <version>7.0.1.145I</version>
                <release>r701145I</release>
              </package>
            </node>
          </nodes>
          <summary>
            <package>
              <name>xrv9k-xr</name>
              <version>7.0.1.145I</version>
              <release>r701145I</release>
            </package>
          </summary>
        </active>
      </packages>
    </install>
  </data>
</rpc-reply>

xrv9k-xr 7.0.1.145I r701145I
2019-09-09 12:22:15,714 - ydk - INFO - Disconnected from device
```
