### ISSUE TITLE
CRUD service unrecognized

### ISSUE THREAD

**Issue by 111pontes** [CiscoDevNet/ydk-gen#554]
CRUD operations may be rejected as unrecognized in YDK 0.6.0.  Seen when connecting to a device that doesn't support [ietf-netconf-monitoring](https://tools.ietf.org/html/rfc6022).

```
ubuntu@ubuntu-xenial:~$ ./nc-create-nx-device-20-ydk.py ssh://admin:cisco@10.60.0.110 -v
2017-09-16 01:30:46,427 - ydk - INFO - Path where models are to be downloaded: /home/ubuntu/.ydk
2017-09-16 01:30:46,434 - ydk - INFO - Connected to 10.60.0.110 on port 830 using ssh
2017-09-16 01:30:46,559 - ydk - INFO - Executing CRUD create operation
2017-09-16 01:30:46,559 - ydk - ERROR - Libyang ERROR: Module not found. Path: '/ydk'
Traceback (most recent call last):
  File "./nc-create-nx-device-20-ydk.py", line 88, in <module>
    crud.create(provider, system)
  File "/usr/local/lib/python2.7/dist-packages/ydk/errors/error_handler.py", line 112, in helper
    return func(self, provider, entity, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ydk/services/crud_service.py", line 30, in create
    return self._crud.create(provider, entity)
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/ydk/errors/error_handler.py", line 82, in handle_runtime_error
    _raise(_exc)
  File "/usr/local/lib/python2.7/dist-packages/ydk/errors/error_handler.py", line 56, in _raise
    raise exc
ydk.errors.YPYInvalidArgumentError:  Path is invalid: ydk:create
2017-09-16 01:30:46,602 - ydk - INFO - Disconnected from device
ubuntu@ubuntu-xenial:~$ 
```

**Comment by abhikeshav** [comment]
Workaround:

Unzip the attached zip file to some local directory and use it to create a `Repository` object:
[models.zip](https://github.com/CiscoDevNet/ydk-gen/files/1817262/models.zip)

Then create the provider as follows
```
from ydk.providers import NetconfServiceProvider    
from ydk.services import CRUDService
from ydk.path import Repository
 
repo=Repository('/path/to/directory/with/models')
crud = CRUDService()
provider = NetconfServiceProvider(repo=repo,address='<ip>' , username='<username>', password='<password>')
```
