### ISSUE TITLE
openconfig_routing_policy: Libyang ERROR: Schema node "INLINE" not found (../config/method=INLINE)

### ISSUE THREAD

**Issue by mjegathe** [CiscoDevNet/ydk-gen#580]
**Description:**
while doing crud create operation RPC is not generating and throwing Libyang error.

**Script**
```python
def oc_routing_policy(crud_service, provider):
    routing_policy_cfg = openconfig_routing_policy.RoutingPolicy()
    policy_def_cfg = routing_policy_cfg.policy_definitions.PolicyDefinition()
    policy_def_cfg.name = 'policy1'
    policy_def_cfg.config.name = 'policy1'

    prefix_set_cfg = routing_policy_cfg.defined_sets.prefix_sets.PrefixSet()
    prefix_set_cfg.prefix_set_name = 'sample'
    prefix_set_cfg.config.prefix_set_name = 'sample'
    prefix_cfg = prefix_set_cfg.prefixes.Prefix()
    prefix_cfg.masklength_range = 'exact'
    prefix_cfg.ip_prefix = '10.0.0.1/24'
    prefix_cfg.config.ip_prefix = '10.0.0.1/24'
    prefix_cfg.config.masklength_range = 'exact'
    prefix_set_cfg.prefixes.prefix.append(prefix_cfg)
    routing_policy_cfg.defined_sets.prefix_sets.prefix_set.append(prefix_set_cfg)

    tag_set_cfg = routing_policy_cfg.defined_sets.tag_sets.TagSet()
    tag_set_cfg.tag_set_name = 'tagsample'
    tag_set_cfg.config.tag_set_name = 'tagsample'
    tag_set_cfg.config.tag_value.append(10)
    routing_policy_cfg.defined_sets.tag_sets.tag_set.append(tag_set_cfg)

    aspathset_cfg = routing_policy_cfg.defined_sets.bgp_defined_sets.as_path_sets.AsPathSet()
    aspathset_cfg.as_path_set_name = 'sampleaspath'
    aspathset_cfg.config.as_path_set_member.append('_1234_')
    aspathset_cfg.config.as_path_set_name = 'sampleaspath'
    routing_policy_cfg.defined_sets.bgp_defined_sets.as_path_sets.as_path_set.append(aspathset_cfg)

    communityset_cfg = routing_policy_cfg.defined_sets.bgp_defined_sets.community_sets.CommunitySet()
    communityset_cfg.community_set_name = 'community1'
    communityset_cfg.config.community_member.append(20)
    communityset_cfg.config.community_set_name = 'community1'
    routing_policy_cfg.defined_sets.bgp_defined_sets.community_sets.community_set.append(communityset_cfg)
  policy_stat_cfg = policy_def_cfg.Statements.Statement()
    policy_stat_cfg.actions.config.accept_route = Empty()
    policy_stat_cfg.actions.bgp_actions.config.set_local_pref = 21
    policy_stat_cfg.actions.bgp_actions.config.set_med = 5
    policy_stat_cfg.actions.bgp_actions.config.set_next_hop = '192.168.1.1'
    policy_stat_cfg.actions.bgp_actions.config.set_route_origin = oc_bgp_types.BgpOriginAttrType.IGP

    policy_stat_cfg.actions.bgp_actions.set_as_path_prepend.config.repeat_n = 50
    policy_stat_cfg.actions.bgp_actions.set_community.config.options = BgpSetCommunityOptionType.ADD
    policy_stat_cfg.actions.bgp_actions.set_community.inline.config.communities.append(65536)
    policy_stat_cfg.actions.bgp_actions.set_community.reference.config.community_set_ref = communityset_cfg.community_set_name
    policy_stat_cfg.actions.igp_actions.config.set_tag = 10

    policy_stat_cfg.conditions.bgp_conditions.as_path_length.config.operator = oc_pt.ATTRIBUTEGE()
    policy_stat_cfg.conditions.bgp_conditions.as_path_length.config.value = 1000

    policy_stat_cfg.conditions.bgp_conditions.config.local_pref_eq = 2000
    policy_stat_cfg.conditions.bgp_conditions.config.med_eq = 100
    policy_stat_cfg.conditions.bgp_conditions.config.next_hop_in.append('11.0.0.1')
    policy_stat_cfg.conditions.bgp_conditions.config.origin_eq = BgpOriginAttrType.IGP
    route_type = policy_stat_cfg.Conditions.BgpConditions.Config.RouteType()
    policy_stat_cfg.conditions.bgp_conditions.config.route_type = route_type.INTERNAL

    policy_stat_cfg.conditions.bgp_conditions.match_as_path_set.config.as_path_set = aspathset_cfg.as_path_set_name
    policy_stat_cfg.conditions.bgp_conditions.match_as_path_set.config.match_set_options = oc_pt.MatchSetOptionsType.ANY

    policy_stat_cfg.conditions.bgp_conditions.match_community_set.config.community_set = communityset_cfg.community_set_name
    policy_stat_cfg.conditions.bgp_conditions.match_community_set.config.match_set_options = oc_pt.MatchSetOptionsType.ALL

    policy_stat_cfg.conditions.config.call_policy = 'policy1'
    policy_stat_cfg.conditions.config.install_protocol_eq = oc_pt.STATIC()
    policy_stat_cfg.conditions.match_prefix_set.config.match_set_options = oc_pt.MatchSetOptionsRestrictedType.ANY
    policy_stat_cfg.conditions.match_prefix_set.config.prefix_set = prefix_set_cfg.prefix_set_name

    policy_stat_cfg.conditions.match_tag_set.config.match_set_options = oc_pt.MatchSetOptionsRestrictedType.INVERT
    policy_stat_cfg.conditions.match_tag_set.config.tag_set = tag_set_cfg.tag_set_name

    policy_def_cfg.statements.statement.append(policy_stat_cfg)
    routing_policy_cfg.policy_definitions.policy_definition.append(policy_def_cfg)

    crud_service.create(provider, routing_policy_cfg)
```
**Logs**

```
Executing CRUD create operation
Executing CRUD create operation
Libyang ERROR: Schema node "INLINE" not found (../config/method=INLINE).
Libyang ERROR: Schema node "INLINE" not found (../config/method=INLINE).
Libyang ERROR: Resolving when condition "../config/method=INLINE" failed. Path: '/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/set-community/inline'
Libyang ERROR: Resolving when condition "../config/method=INLINE" failed. Path: '/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/set-community/inline'
Libyang ERROR: Schema node "REFERENCE" not found (../config/method=REFERENCE).
Libyang ERROR: Schema node "REFERENCE" not found (../config/method=REFERENCE).
Libyang ERROR: Resolving when condition "../config/method=REFERENCE" failed. Path: '/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/set-community/reference'
Libyang ERROR: Resolving when condition "../config/method=REFERENCE" failed. Path: '/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/set-community/reference'
Libyang ERROR: Schema node "INLINE" not found (../config/method=INLINE).
Libyang ERROR: Schema node "INLINE" not found (../config/method=INLINE).
Libyang ERROR: Resolving when condition "../config/method=INLINE" failed. Path: '/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/set-ext-community/inline'
Libyang ERROR: Resolving when condition "../config/method=INLINE" failed. Path: '/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/set-ext-community/inline'
Libyang ERROR: Schema node "REFERENCE" not found (../config/method=REFERENCE).
Libyang ERROR: Schema node "REFERENCE" not found (../config/method=REFERENCE).
Libyang ERROR: Resolving when condition "../config/method=REFERENCE" failed. Path: '/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/set-ext-community/reference'
Libyang ERROR: Resolving when condition "../config/method=REFERENCE" failed. Path: '/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/set-ext-community/reference'
Libyang ERROR: Module "openconfig-bgp-policy" parsing failed.
Libyang ERROR: Module "openconfig-bgp-policy" parsing failed.
Libyang ERROR: Schema node "INLINE" not found (../config/method=INLINE).
Libyang ERROR: Schema node "INLINE" not found (../config/method=INLINE).
Libyang ERROR: Resolving when condition "../config/method=INLINE" failed. Path: '/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/set-community/inline'
Libyang ERROR: Resolving when condition "../config/method=INLINE" failed. Path: '/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/set-community/inline'
Libyang ERROR: Schema node "REFERENCE" not found (../config/method=REFERENCE).
Libyang ERROR: Schema node "REFERENCE" not found (../config/method=REFERENCE).
Libyang ERROR: Resolving when condition "../config/method=REFERENCE" failed. Path: '/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/set-community/reference'
Libyang ERROR: Resolving when condition "../config/method=REFERENCE" failed. Path: '/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/set-community/reference'
Libyang ERROR: Schema node "INLINE" not found (../config/method=INLINE).
Libyang ERROR: Schema node "INLINE" not found (../config/method=INLINE).
Libyang ERROR: Resolving when condition "../config/method=INLINE" failed. Path: '/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/set-ext-community/inline'
Libyang ERROR: Resolving when condition "../config/method=INLINE" failed. Path: '/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/set-ext-community/inline'
Libyang ERROR: Schema node "REFERENCE" not found (../config/method=REFERENCE).
Libyang ERROR: Schema node "REFERENCE" not found (../config/method=REFERENCE).
Libyang ERROR: Resolving when condition "../config/method=REFERENCE" failed. Path: '/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/set-ext-community/reference'
Libyang ERROR: Resolving when condition "../config/method=REFERENCE" failed. Path: '/routing-policy/policy-definitions/policy-definition/statements/statement/actions/bgp-actions/set-ext-community/reference'
Libyang ERROR: Module "openconfig-bgp-policy" parsing failed.
Libyang ERROR: Module "openconfig-bgp-policy" parsing failed.
Libyang ERROR: Schema node not found. Path: 'openconfig-bgp-policy:bgp-defined-sets'
Libyang ERROR: Schema node not found. Path: 'openconfig-bgp-policy:bgp-defined-sets'
Libyang ERROR: Schema node not found. Path: 'openconfig-bgp-policy:bgp-defined-sets'
Libyang ERROR: Schema node not found. Path: 'openconfig-bgp-policy:bgp-defined-sets'
Invalid path: openconfig-bgp-policy:bgp-defined-sets
Invalid path: openconfig-bgp-policy:bgp-defined-sets
An error occurred creating the routing_policy_cfg configuration.
```

**System Information**
-bash-4.2$ pip list | grep ydk
ydk (0.6.1)
ydk-models-cisco-ios-xr (6.3.1)
ydk-models-ietf (0.1.4)
ydk-models-openconfig (0.1.4)

-bash-4.2$ lsb_release -d
Description:    Red Hat Enterprise Server VXR Linux release 7.3.1611 (Core)

**Comment by abhikeshav** [comment]
Please find attached a .zip file containing a RPM package which should contain the fix for this issue. Let me know if you face any issues.

[libydk-0.6.1-1.x86_64.rpm.zip](https://github.com/CiscoDevNet/ydk-gen/files/1345100/libydk-0.6.1-1.x86_64.rpm.zip)

To install:

```
$ pip uninstall ydk -y
$ sudo yum install libydk-0.6.1*.rpm
$ pip install ydk
```

**Comment by mjegathe** [comment]
I have tried this already and once again tried installing the above libydk-rpm and followed the steps. Still getting the same error.

**Comment by abhikeshav** [comment]
That is strange. It seems to work for me. Need to understand why it is not working for you

**Comment by mjegathe** [comment]
Leaf which is referring the bgp-policy yang having problem. 
For Eg:
Below code will throw the libyang error.
 aspathset_cfg = routing_policy_cfg.defined_sets.bgp_defined_sets.as_path_sets.AsPathSet()
    aspathset_cfg.as_path_set_name = 'sampleaspath'
    aspathset_cfg.config.as_path_set_member.append('_1234_')
    aspathset_cfg.config.as_path_set_name = 'sampleaspath'
    routing_policy_cfg.defined_sets.bgp_defined_sets.as_path_sets.as_path_set.append(aspathset_cfg)

**Comment by mjegathe** [comment]
I have generated bundle with ydk-gen for oc-routing-policy and ran my script. I got attribute error.

**Error Log:**

-bash-4.2$ python2.7 routing_policy.py --host 10.85.104.17 --port 20311 -u lab -p lab
Establishing connection with device 10.85.104.17:20311 using ssh :
Path where models are to be downloaded: /users/mjegathe/.ydk/10.85.104.17:20311
Path where models are to be downloaded: /users/mjegathe/.ydk/10.85.104.17:20311
Connected to 10.85.104.17 on port 20311 using ssh with timeout of -1
Connected to 10.85.104.17 on port 20311 using ssh with timeout of -1
Connected to 10.85.104.17 on port 20311 using ssh with timeout of -1
Connected to 10.85.104.17 on port 20311 using ssh with timeout of -1
connection established...
> /auto/tftp-pluto/mjegathe/ydk-py-0.6.0/core/samples/routing_policy.py(48)oc_routing_policy()
-> prefix_set_cfg = routing_policy_cfg.defined_sets.prefix_sets.PrefixSet()
(Pdb) c
Traceback (most recent call last):
  File "routing_policy.py", line 132, in <module>
    oc_routing_policy(crud_service, provider)
  File "routing_policy.py", line 48, in oc_routing_policy
    prefix_set_cfg = routing_policy_cfg.defined_sets.prefix_sets.PrefixSet()
AttributeError: 'DefinedSets' object has no attribute 'bgp_defined_sets'

**Comment by abhikeshav** [comment]
Are you including `bgp-policy.yang` when generating the bundle? This is where the `bgp_defined_sets` is defined: http://ydk.cisco.com/py/docs/gen_doc_9dccfd5cabfe5220944c55494b00b2bc1b5438ab.html#ydk.models.openconfig.openconfig_routing_policy.RoutingPolicy.DefinedSets.BgpDefinedSets

**Comment by mjegathe** [comment]
In YDK-gen fix can able to generate RPC and libyang error resolved . IF facing any issues in validation against router will post in this bug.

**Comment by abhikeshav** [comment]
Thanks for confirming, @mjegathe . Will close this for now as YDK issue is fixed. Let me know in case of any further issues
