### ISSUE TITLE
Interface config output with unexpected  YDK error "Couldn't fetch child entity 'Cisco-IOS-XR-cdp-cfg:cdp' " 

### ISSUE THREAD

**Issue by qazishafat** [CiscoDevNet/ydk-gen#665]
Issue tracker is ONLY used for reporting bugs. Please use the [YDK Community](https://communities.cisco.com/community/developer/ydk) for any support issues.

## Expected Behavior

Getting interface configuration using YDK should get the RPC, however it throughs RDK error also related to child entity of "Cisco-IOS-XR-cdp-cfg:cdp". Expected is:

```
=============
shafat@shaashra-lnx:~/ydk-py$ ./interface.py ssh://admin:cisco123@10.87.163.199 -v
2018-01-16 15:01:53,822 - ydk - INFO - Path where models are to be downloaded: /home/shafat/.ydk/10.87.163.199:830
2018-01-16 15:01:53,832 - ydk - INFO - Connected to 10.87.163.199 on port 830 using ssh with timeout of -1
2018-01-16 15:01:53,889 - ydk - INFO - Executing get-config RPC
2018-01-16 15:01:53,932 - ydk - INFO - =============Generating payload to send to device=============
2018-01-16 15:01:53,933 - ydk - INFO - <rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><get-config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <source>
    <running/>
  </source>
  <filter><interface-configurations xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-ifmgr-cfg">
  <interface-configuration>
    <interface-name>TenGigE0/0/0/0</interface-name>
    <active>act</active>
  </interface-configuration>
</interface-configurations></filter>
</get-config>
</rpc>
2018-01-16 15:01:53,933 - ydk - INFO - 

2018-01-16 15:01:54,411 - ydk - INFO - =============Reply payload received from device=============
2018-01-16 15:01:54,411 - ydk - INFO - <?xml version="1.0"?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1">
  <data>
    <interface-configurations xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-ifmgr-cfg">
      <interface-configuration>
        <active>act</active>
        <interface-name>TenGigE0/0/0/0</interface-name>
        <description>" Spine1 | tengig 0/0/0/0 CIRCUIT-ID: "</description>
        <cdp xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-cdp-cfg">
          <enable/>
        </cdp>
        <vrf xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-infra-rsi-cfg">vrf-mgmt</vrf>
        <ipv4-network xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-ipv4-io-cfg">
          <addresses>
            <primary>
              <address>172.16.100.2</address>
              <netmask>255.255.255.0</netmask>
            </primary>
          </addresses>
        </ipv4-network>
      </interface-configuration>
    </interface-configurations>
  </data>
</rpc-reply>

```

## Current Behavior:
```
/ydk-py$ ./interface.py ssh://admin:cisco123@10.87.163.199 -v
2018-01-16 15:01:53,822 - ydk - INFO - Path where models are to be downloaded: /home/shafat/.ydk/10.87.163.199:830
2018-01-16 15:01:53,832 - ydk - INFO - Connected to 10.87.163.199 on port 830 using ssh with timeout of -1
2018-01-16 15:01:53,889 - ydk - INFO - Executing get-config RPC
2018-01-16 15:01:53,932 - ydk - INFO - =============Generating payload to send to device=============
2018-01-16 15:01:53,933 - ydk - INFO - <rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><get-config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <source>
    <running/>
  </source>
  <filter><interface-configurations xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-ifmgr-cfg">
  <interface-configuration>
    <interface-name>TenGigE0/0/0/0</interface-name>
    <active>act</active>
  </interface-configuration>
</interface-configurations></filter>
</get-config>
</rpc>
2018-01-16 15:01:53,933 - ydk - INFO - 

2018-01-16 15:01:54,411 - ydk - INFO - =============Reply payload received from device=============
2018-01-16 15:01:54,411 - ydk - INFO - <?xml version="1.0"?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1">
  <data>
    <interface-configurations xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-ifmgr-cfg">
      <interface-configuration>
        <active>act</active>
        <interface-name>TenGigE0/0/0/0</interface-name>
        <description>" Spine1 | tengig 0/0/0/0 CIRCUIT-ID: "</description>
        <cdp xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-cdp-cfg">
          <enable/>
        </cdp>
        <vrf xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-infra-rsi-cfg">vrf-mgmt</vrf>
        <ipv4-network xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-ipv4-io-cfg">
          <addresses>
            <primary>
              <address>172.16.100.2</address>
              <netmask>255.255.255.0</netmask>
            </primary>
          </addresses>
        </ipv4-network>
      </interface-configuration>
    </interface-configurations>
  </data>
</rpc-reply>

2018-01-16 15:01:54,412 - ydk - INFO - 

2018-01-16 15:01:54,489 - ydk - ERROR - Couldn't fetch child entity Cisco-IOS-XR-cdp-cfg:cdp in parent /Cisco-IOS-XR-ifmgr-cfg:interface-configurations/interface-configuration[active='act'][interface-name='TenGigE0/0/0/0']!
Traceback (most recent call last):
  File "./interface.py", line 84, in <module>
    main()
  File "./interface.py", line 68, in main
    router_config = netconf_operations.get_config(provider, Datastore.running, interface_configurations)
  File "/usr/local/lib/python2.7/dist-packages/ydk/services/netconf_service.py", line 88, in get_config
    return self._ns.get_config(provider, source, read_filter)
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/ydk/errors/error_handler.py", line 82, in handle_runtime_error
    _raise(_exc)
  File "/usr/local/lib/python2.7/dist-packages/ydk/errors/error_handler.py", line 56, in _raise
    raise exc
ydk.errors.YPYCoreError:  Couldn't fetch child entity 'Cisco-IOS-XR-cdp-cfg:cdp' in parent /Cisco-IOS-XR-ifmgr-cfg:interface-configurations/interface-configuration[active='act'][interface-name='TenGigE0/0/0/0']
2018-01-16 15:01:54,498 - ydk - INFO - Disconnected from device
shafat@shaashra-lnx:~/ydk-py$ 

```

## Steps to Reproduce
Run the program with verbose mode .

## Your Script

```python
#!/usr/bin/env python
from ydk.models.cisco_ios_xr.Cisco_IOS_XR_ifmgr_cfg import InterfaceConfigurations 
from ydk.models.cisco_ios_xr.Cisco_IOS_XR_ipv4_bgp_cfg import Bgp
from ydk.providers import NetconfServiceProvider
from ydk.services import NetconfService
from ydk.services import Datastore
from ydk.services import CodecService
from ydk.providers import CodecServiceProvider
from ydk.services import CRUDService
from ydk.filters import YFilter
from ydk.types import Empty
from argparse import ArgumentParser
from urlparse import urlparse
import logging

"""
Create configuration for model Cisco_IOS_XR_ifmgr_cfg.
usage: interface.py [-h] [-v] device
positional arguments:
  device         NETCONF device (ssh://user:password@host:port)
optional arguments:
  -h, --help     show this help message and exit
  -v, --verbose  print debugging messages
"""

def config_interface_configurations(interface_configurations):

	interface = interface_configurations.InterfaceConfiguration()
	interface.active = 'act'
	interface.interface_name = 'TenGigE0/0/0/0'
	#interface.interface_virtual = Empty()
	interface_configurations.interface_configuration.append(interface)

def main():
	parser = ArgumentParser()
	parser.add_argument("-v", "--verbose", help="print debugging messages",action="store_true")
	parser.add_argument("device",help="NETCONF device (ssh://user:password@host:port)")
	args = parser.parse_args()
	device = urlparse(args.device)

	# log debug messages if verbose argument specified
	if args.verbose:
		logger = logging.getLogger("ydk")
		logger.setLevel(logging.INFO)
		handler = logging.StreamHandler()
		formatter = logging.Formatter(("%(asctime)s - %(name)s - " 
									   "%(levelname)s - %(message)s"))
		handler.setFormatter(formatter)
		logger.addHandler(handler)
	provider = NetconfServiceProvider(address=device.hostname,
										port=device.port,
										username=device.username,
										password=device.password,
										protocol=device.scheme)

	crud = CRUDService()
	codec_provider = CodecServiceProvider()
	codec = CodecService()
	
	#Get the BGP config from router (a config is already on there)
	netconf_operations = NetconfService()
	

	interface_configurations = InterfaceConfigurations()  # create object
	config_interface_configurations(interface_configurations)  # add object configuration

	#interface.yfilter = YFilter.read
	router_config = netconf_operations.get_config(provider, Datastore.running, interface_configurations)
	router_config_crud = crud.read_config(netconf_session,router_config)
	print codec.encode(codec_provider,router_config_crud)
	#print codec.encode(codec_provider, bgp_on_router_config)
	#Delete BGP config from router
	#crud.delete(netconf_session, bgp_on_router_config)
	#print "Deleting the config"
	#Re apply the BGP config
	#netconf_operations.edit_config(netconf_session, Datastore.candidate, bgp_on_router_config)
	#netconf_operations.commit(netconf_session)
	#print "Re applied the config"
	#Get all config
	#full_config = netconf_operations.get_config(netconf_session, Datastore.running, None)
	#print codec.encode(codec_provider, full_config)

if __name__ == '__main__':
	main()
```

## Logs

Enable [logging](http://ydk.cisco.com/py/docs/guides/introduction.html#logging) and post the logs below

```
2018-01-16 15:01:53,822 - ydk - INFO - Path where models are to be downloaded: /home/shafat/.ydk/10.87.163.199:830
2018-01-16 15:01:53,832 - ydk - INFO - Connected to 10.87.163.199 on port 830 using ssh with timeout of -1
2018-01-16 15:01:53,889 - ydk - INFO - Executing get-config RPC
2018-01-16 15:01:53,932 - ydk - INFO - =============Generating payload to send to device=============
2018-01-16 15:01:53,933 - ydk - INFO - <rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0"><get-config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <source>
    <running/>
  </source>
  <filter><interface-configurations xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-ifmgr-cfg">
  <interface-configuration>
    <interface-name>TenGigE0/0/0/0</interface-name>
    <active>act</active>
  </interface-configuration>
</interface-configurations></filter>
</get-config>
</rpc>
2018-01-16 15:01:53,933 - ydk - INFO - 

2018-01-16 15:01:54,411 - ydk - INFO - =============Reply payload received from device=============
2018-01-16 15:01:54,411 - ydk - INFO - <?xml version="1.0"?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1">
  <data>
    <interface-configurations xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-ifmgr-cfg">
      <interface-configuration>
        <active>act</active>
        <interface-name>TenGigE0/0/0/0</interface-name>
        <description>" Spine1 | tengig 0/0/0/0 CIRCUIT-ID: "</description>
        <cdp xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-cdp-cfg">
          <enable/>
        </cdp>
        <vrf xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-infra-rsi-cfg">vrf-mgmt</vrf>
        <ipv4-network xmlns="http://cisco.com/ns/yang/Cisco-IOS-XR-ipv4-io-cfg">
          <addresses>
            <primary>
              <address>172.16.100.2</address>
              <netmask>255.255.255.0</netmask>
            </primary>
          </addresses>
        </ipv4-network>
      </interface-configuration>
    </interface-configurations>
  </data>
</rpc-reply>

2018-01-16 15:01:54,412 - ydk - INFO - 

2018-01-16 15:01:54,489 - ydk - ERROR - Couldn't fetch child entity Cisco-IOS-XR-cdp-cfg:cdp in parent /Cisco-IOS-XR-ifmgr-cfg:interface-configurations/interface-configuration[active='act'][interface-name='TenGigE0/0/0/0']!
Traceback (most recent call last):
  File "./interface.py", line 84, in <module>
    main()
  File "./interface.py", line 68, in main
    router_config = netconf_operations.get_config(provider, Datastore.running, interface_configurations)
  File "/usr/local/lib/python2.7/dist-packages/ydk/services/netconf_service.py", line 88, in get_config
    return self._ns.get_config(provider, source, read_filter)
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/ydk/errors/error_handler.py", line 82, in handle_runtime_error
    _raise(_exc)
  File "/usr/local/lib/python2.7/dist-packages/ydk/errors/error_handler.py", line 56, in _raise
    raise exc
ydk.errors.YPYCoreError:  Couldn't fetch child entity 'Cisco-IOS-XR-cdp-cfg:cdp' in parent /Cisco-IOS-XR-ifmgr-cfg:interface-configurations/interface-configuration[active='act'][interface-name='TenGigE0/0/0/0']
2018-01-16 15:01:54,498 - ydk - INFO - Disconnected from device
```

## System Information

```
Python 2.7.12 
shafat@shaashra-lnx:~/ydk-py$ pip list | grep ydk
ydk (0.6.3)
ydk-models-cisco-ios-xr (6.3.1)
ydk-models-ietf (0.1.4)
ydk-models-openconfig (0.1.4)
shafat@shaashra-lnx:~/ydk-py$ 

Host ( device information )
NCS55001:
image version : 6.3.1
```

**Comment by abhikeshav** [comment]
Unable to reproduce on:

```
# apt list libydk
Listing... Done
libydk/now 0.7.1 amd64 [installed,local]
 
# pip list|grep ydk
ydk                     0.7.1   
ydk-models-cisco-ios-xr 6.3.2
```
