### ISSUE TITLE
XR BGP Oper error with XR 6.1.2 model

### ISSUE THREAD

**Issue by abhikeshav** [CiscoDevNet/ydk-gen#676]
Issue tracker is ONLY used for reporting bugs. Please use the [YDK Community](https://communities.cisco.com/community/developer/ydk) for any support issues.

## Expected Behavior

See https://communities.cisco.com/thread/89074

## Current Behavior

```
Invalid path: af-data  
Traceback (most recent call last):  
  File "lib/bgp/oper.py", line 47, in <module>  
    print(codec.encode(codec_provider, bgp_obj, pretty=True))  
  File "/home/ubuntu/.virtualenvs/ydk-py/lib/python3.5/site-packages/ydk/errors/error_handler.py", line 112, in helper  
    return func(self, provider, entity, *args, **kwargs)  
  File "/home/ubuntu/.virtualenvs/ydk-py/lib/python3.5/site-packages/ydk/services/codec_service.py", line 74, in encode  
    return self._encode(provider, entity_holder, pretty, subtree)  
  File "/home/ubuntu/.virtualenvs/ydk-py/lib/python3.5/site-packages/ydk/services/codec_service.py", line 105, in _encode  
    return result  
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__  
    self.gen.throw(type, value, traceback)  
  File "/home/ubuntu/.virtualenvs/ydk-py/lib/python3.5/site-packages/ydk/errors/error_handler.py", line 82, in handle_runtime_error  
    _raise(_exc)  
  File "/home/ubuntu/.virtualenvs/ydk-py/lib/python3.5/site-packages/ydk/errors/error_handler.py", line 54, in _raise  
    exec("raise exc from None")  
  File "<string>", line 1, in <module>  
ydk.errors.YPYModelError:  Invalid path: af-data : Failed to resolve uses "DEFAULT-VRF".. Path: /Cisco-IOS-XR-ipv4-bgp-oper:bgp/instances/instance/instance-standby/DEFAULT-VRF  
Disconnected from device 
```

## System Information

XRv version is 6.1.2

``` 
ydk (0.6.3)  
ydk-models-cisco-ios-xr (6.3.1)  
ydk-models-ietf (0.1.4) 
```

**Comment by abhikeshav** [comment]
It looks like the XR [6.1.2 model has an invalid pattern](https://github.com/YangModels/yang/blob/master/vendor/cisco/xr/631/Cisco-IOS-XR-types.yang#L137) using double quotes, which is causing the error you are seeing. This was fixed in the [621 model where it was changed to use single quote](https://github.com/YangModels/yang/blob/master/vendor/cisco/xr/631/Cisco-IOS-XR-types.yang#L137). YDK `0.7.1` cannot be used with XR 612. The issue should be fixed if you use a XR 612 or newer device after clearing the cache (rm -rf ~/.ydk).
