### ISSUE TITLE
pip install ydk fails on RHEL6

### ISSUE THREAD

**Issue by dcg-csc** [CiscoDevNet/ydk-gen#687]
On RHEL6, I have yum installed all the prerequisites as per:
https://github.com/CiscoDevNet/ydk-py/blob/master/README.rst#linux

pip install of ydk fails due to cmake3 missing CXX14 option

## Expected Behavior

pip install should work

AND

Update the https://github.com/CiscoDevNet/ydk-py/blob/master/README.rst#linux
file if more dependencies are required

## Current Behavior

pip install / upgrade fails due to build error

## Steps to Reproduce

(start python3.6 virtualenv)
pip install ydk

## Your Script

```

```

## Logs
Enable [logging](http://ydk.cisco.com/py/docs/guides/introduction.html#logging) and post the logs below

```

rhel6 $ pip install -U ydk
Collecting ydk
  Using cached ydk-0.7.0.tar.gz
Collecting pybind11>=2.1.1 (from ydk)
  Using cached pybind11-2.2.2-py2.py3-none-any.whl
Building wheels for collected packages: ydk
  Running setup.py bdist_wheel for ydk ... error
  Complete output from command /mypy36.venv/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-kf_783rl/ydk/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp32m56gjxpip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/ydk
  copying ydk/exthook.py -> build/lib.linux-x86_64-3.6/ydk
  copying ydk/__init__.py -> build/lib.linux-x86_64-3.6/ydk
  creating build/lib.linux-x86_64-3.6/ydk/errors
  copying ydk/errors/error_handler.py -> build/lib.linux-x86_64-3.6/ydk/errors
  copying ydk/errors/__init__.py -> build/lib.linux-x86_64-3.6/ydk/errors
  creating build/lib.linux-x86_64-3.6/ydk/models
  copying ydk/models/__init__.py -> build/lib.linux-x86_64-3.6/ydk/models
  creating build/lib.linux-x86_64-3.6/ydk/types
  copying ydk/types/py_types.py -> build/lib.linux-x86_64-3.6/ydk/types
  copying ydk/types/__init__.py -> build/lib.linux-x86_64-3.6/ydk/types
  creating build/lib.linux-x86_64-3.6/ydk/path
  copying ydk/path/__init__.py -> build/lib.linux-x86_64-3.6/ydk/path
  creating build/lib.linux-x86_64-3.6/ydk/entity_utils
  copying ydk/entity_utils/__init__.py -> build/lib.linux-x86_64-3.6/ydk/entity_utils
  creating build/lib.linux-x86_64-3.6/ydk/logging
  copying ydk/logging/__init__.py -> build/lib.linux-x86_64-3.6/ydk/logging
  creating build/lib.linux-x86_64-3.6/ydk/services
  copying ydk/services/executor_service.py -> build/lib.linux-x86_64-3.6/ydk/services
  copying ydk/services/codec_service.py -> build/lib.linux-x86_64-3.6/ydk/services
  copying ydk/services/crud_service.py -> build/lib.linux-x86_64-3.6/ydk/services
  copying ydk/services/__init__.py -> build/lib.linux-x86_64-3.6/ydk/services
  copying ydk/services/netconf_service.py -> build/lib.linux-x86_64-3.6/ydk/services
  creating build/lib.linux-x86_64-3.6/ydk/ext
  copying ydk/ext/__init__.py -> build/lib.linux-x86_64-3.6/ydk/ext
  creating build/lib.linux-x86_64-3.6/ydk/providers
  copying ydk/providers/__init__.py -> build/lib.linux-x86_64-3.6/ydk/providers
  copying ydk/providers/codec_provider.py -> build/lib.linux-x86_64-3.6/ydk/providers
  creating build/lib.linux-x86_64-3.6/ydk/filters
  copying ydk/filters/__init__.py -> build/lib.linux-x86_64-3.6/ydk/filters
  creating build/lib.linux-x86_64-3.6/ydk/path/sessions
  copying ydk/path/sessions/__init__.py -> build/lib.linux-x86_64-3.6/ydk/path/sessions
  copying ydk/path/sessions/netconf_session.py -> build/lib.linux-x86_64-3.6/ydk/path/sessions
  copying ydk/path/sessions/restconf_session.py -> build/lib.linux-x86_64-3.6/ydk/path/sessions
  running build_ext
  -- The C compiler identification is GNU 4.4.7
  -- The CXX compiler identification is GNU 4.4.7
  -- Check for working C compiler: /usr/bin/cc
  -- Check for working C compiler: /usr/bin/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: /usr/bin/c++
  -- Check for working CXX compiler: /usr/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  python version: 3.6m
  -- Found PythonLibs: /usr/local/lib/libpython3.6m.a (found version "3.6.4")
  pybind11 include: /mypy36.venv/include/site/python3.6;/mypy36.venv/include/site/python3.6
  -- Configuring done
  CMake Error in CMakeLists.txt:
    Target "ydk_" requires the language dialect "CXX14" (with compiler
    extensions), but CMake does not know the compile flags to use to enable it.
  
  
  -- Generating done
  -- Build files have been written to: /tmp/pip-build-kf_783rl/ydk/build/temp.linux-x86_64-3.6
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-kf_783rl/ydk/setup.py", line 145, in <module>
      zip_safe=False,
    File "/mypy36.venv/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/mypy36.venv/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 204, in run
      self.run_command('build')
    File "/usr/local/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-kf_783rl/ydk/setup.py", line 72, in run
      self.build_extension(ext)
    File "/tmp/pip-build-kf_783rl/ydk/setup.py", line 100, in build_extension
      subprocess.check_call([cmake_executable, ext.sourcedir] + cmake_args, cwd=self.build_temp)
    File "/usr/local/lib/python3.6/subprocess.py", line 291, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake3', '/tmp/pip-build-kf_783rl/ydk', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-build-kf_783rl/ydk/build/lib.linux-x86_64-3.6', '-DPYBIND11_INCLUDE=/mypy36.venv/include/site/python3.6;/mypy36.venv/include/site/python3.6', '-DPYTHON_VERSION=3.6m', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
  
  ----------------------------------------
  Failed building wheel for ydk
  Running setup.py clean for ydk
Failed to build ydk
Installing collected packages: pybind11, ydk
  Found existing installation: pybind11 2.0.1
    Uninstalling pybind11-2.0.1:
      Successfully uninstalled pybind11-2.0.1
  Found existing installation: ydk 0.5.5
    Uninstalling ydk-0.5.5:
      Successfully uninstalled ydk-0.5.5
  Running setup.py install for ydk ... error
    Complete output from command /mypy36.venv/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-kf_783rl/ydk/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-ccuxek07-record/install-record.txt --single-version-externally-managed --compile --install-headers /mypy36.venv/include/site/python3.6/ydk:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/ydk
    copying ydk/exthook.py -> build/lib.linux-x86_64-3.6/ydk
    copying ydk/__init__.py -> build/lib.linux-x86_64-3.6/ydk
    creating build/lib.linux-x86_64-3.6/ydk/errors
    copying ydk/errors/error_handler.py -> build/lib.linux-x86_64-3.6/ydk/errors
    copying ydk/errors/__init__.py -> build/lib.linux-x86_64-3.6/ydk/errors
    creating build/lib.linux-x86_64-3.6/ydk/models
    copying ydk/models/__init__.py -> build/lib.linux-x86_64-3.6/ydk/models
    creating build/lib.linux-x86_64-3.6/ydk/types
    copying ydk/types/py_types.py -> build/lib.linux-x86_64-3.6/ydk/types
    copying ydk/types/__init__.py -> build/lib.linux-x86_64-3.6/ydk/types
    creating build/lib.linux-x86_64-3.6/ydk/path
    copying ydk/path/__init__.py -> build/lib.linux-x86_64-3.6/ydk/path
    creating build/lib.linux-x86_64-3.6/ydk/entity_utils
    copying ydk/entity_utils/__init__.py -> build/lib.linux-x86_64-3.6/ydk/entity_utils
    creating build/lib.linux-x86_64-3.6/ydk/logging
    copying ydk/logging/__init__.py -> build/lib.linux-x86_64-3.6/ydk/logging
    creating build/lib.linux-x86_64-3.6/ydk/services
    copying ydk/services/executor_service.py -> build/lib.linux-x86_64-3.6/ydk/services
    copying ydk/services/codec_service.py -> build/lib.linux-x86_64-3.6/ydk/services
    copying ydk/services/crud_service.py -> build/lib.linux-x86_64-3.6/ydk/services
    copying ydk/services/__init__.py -> build/lib.linux-x86_64-3.6/ydk/services
    copying ydk/services/netconf_service.py -> build/lib.linux-x86_64-3.6/ydk/services
    creating build/lib.linux-x86_64-3.6/ydk/ext
    copying ydk/ext/__init__.py -> build/lib.linux-x86_64-3.6/ydk/ext
    creating build/lib.linux-x86_64-3.6/ydk/providers
    copying ydk/providers/__init__.py -> build/lib.linux-x86_64-3.6/ydk/providers
    copying ydk/providers/codec_provider.py -> build/lib.linux-x86_64-3.6/ydk/providers
    creating build/lib.linux-x86_64-3.6/ydk/filters
    copying ydk/filters/__init__.py -> build/lib.linux-x86_64-3.6/ydk/filters
    creating build/lib.linux-x86_64-3.6/ydk/path/sessions
    copying ydk/path/sessions/__init__.py -> build/lib.linux-x86_64-3.6/ydk/path/sessions
    copying ydk/path/sessions/netconf_session.py -> build/lib.linux-x86_64-3.6/ydk/path/sessions
    copying ydk/path/sessions/restconf_session.py -> build/lib.linux-x86_64-3.6/ydk/path/sessions
    running build_ext
    -- The C compiler identification is GNU 4.4.7
    -- The CXX compiler identification is GNU 4.4.7
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    python version: 3.6m
    -- Found PythonLibs: /usr/local/lib/libpython3.6m.a (found version "3.6.4")
    pybind11 include: /mypy36.venv/include/site/python3.6;/mypy36.venv/include/site/python3.6
    -- Configuring done
    CMake Error in CMakeLists.txt:
      Target "ydk_" requires the language dialect "CXX14" (with compiler
      extensions), but CMake does not know the compile flags to use to enable it.
    
    
    -- Generating done
    -- Build files have been written to: /tmp/pip-build-kf_783rl/ydk/build/temp.linux-x86_64-3.6
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-kf_783rl/ydk/setup.py", line 145, in <module>
        zip_safe=False,
      File "/mypy36.venv/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/mypy36.venv/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/usr/local/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/local/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-kf_783rl/ydk/setup.py", line 72, in run
        self.build_extension(ext)
      File "/tmp/pip-build-kf_783rl/ydk/setup.py", line 100, in build_extension
        subprocess.check_call([cmake_executable, ext.sourcedir] + cmake_args, cwd=self.build_temp)
      File "/usr/local/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake3', '/tmp/pip-build-kf_783rl/ydk', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-build-kf_783rl/ydk/build/lib.linux-x86_64-3.6', '-DPYBIND11_INCLUDE=/mypy36.venv/include/site/python3.6;/mypy36.venv/include/site/python3.6', '-DPYTHON_VERSION=3.6m', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
    
    ----------------------------------------
  Rolling back uninstall of ydk
Command "/mypy36.venv/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-kf_783rl/ydk/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-ccuxek07-record/install-record.txt --single-version-externally-managed --compile --install-headers /mypy36.venv/include/site/python3.6/ydk" failed with error code 1 in /tmp/pip-build-kf_783rl/ydk/
rhel6 $ 

```

## System Information

```
rhel6$ lsb_release -a
LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID:	RedHatEnterpriseWorkstation
Description:	Red Hat Enterprise Linux Workstation release 6.7 (Santiago)
Release:	6.7
Codename:	Santiago
```

**Comment by abhikeshav** [comment]
There are some [dependencies](https://github.com/CiscoDevNet/ydk-gen#linux) of ydk which are not available in RHEL6. If you know of any workarounds, do let us know.

**Comment by ygorelik** [comment]
Not actual anymore as YDK works fine on RHEL7.
