### ISSUE TITLE
XR unable to read interface

### ISSUE THREAD

**Issue by RunSi** [CiscoDevNet/ydk-gen#775]
Issue tracker is ONLY used for reporting bugs. Please use the [YDK Community](https://communities.cisco.com/community/developer/ydk) for any support issues.

As advised by 'abhirame' on the YDK communities forum am raising this issue with respect to reading interface configuration on XRv.  This code worked prior to 0.7.0

## Expected Behavior

The code should print out in xml format the configuration of interfaces on XRv

## Current Behavior

Currently the script tracebacks with the following error
ydk.errors.YInvalidArgumentError:  Path is invalid: Cisco-IOS-XR-ifmgr-cfg:global-interface-configuration

## Steps to Reproduce

Running the script from docker image (although behaviour is consistent with native install and Vagrant)

./nc_read_test_sh.py ssh://vagrant:vagrant@docker.for.mac.host.internal:2230 -vv

## Your Script

```
from argparse import ArgumentParser
from urlparse import urlparse

from ydk.services import CRUDService
from ydk.providers import NetconfServiceProvider
from ydk.services.codec_service import CodecService
from ydk.providers.codec_provider import CodecServiceProvider
from ydk.models.cisco_ios_xr import Cisco_IOS_XR_ifmgr_cfg \
    as xr_ifmgr_cfg
import logging


def process_global_interface_configuration(interface_configurations):
    print(codec.encode(codec_provider, interface_configurations))
    return


if __name__ == "__main__":
    """Execute main program."""
    parser = ArgumentParser()
    parser.add_argument("-v", "--verbose", help="print debugging messages",
                        action="store_true")
    parser.add_argument("device",
                        help="NETCONF device (ssh://user:password@host:port)")
    args = parser.parse_args()
    device = urlparse(args.device)

    # log debug messages if verbose argument specified
    if args.verbose:
        logger = logging.getLogger("ydk")
        logger.setLevel(logging.INFO)
        handler = logging.StreamHandler()
        formatter = logging.Formatter(("%(asctime)s - %(name)s - "
                                      "%(levelname)s - %(message)s"))
        handler.setFormatter(formatter)
        logger.addHandler(handler)

    # create CODEC service
    codec = CodecService()
    # create CODEC provider
    codec_provider = CodecServiceProvider(type='xml')

    # create NETCONF provider
    provider = NetconfServiceProvider(address=device.hostname,
                                      port=device.port,
                                      username=device.username,
                                      password=device.password,
                                      protocol=device.scheme)
    # create CRUD service
    crud = CRUDService()

    interface_configurations = xr_ifmgr_cfg.InterfaceConfigurations()  # create object

    # read data from NETCONF device
    interface_configurations = crud.read(provider, interface_configurations)
    process_interface_configurations(interface_configurations)  # process object data

    exit()

```

## Logs
Enable [logging](http://ydk.cisco.com/py/docs/guides/introduction.html#logging) and post the logs below

```
2018-05-01 08:10:24,700 - ydk - INFO - Path where models are to be downloaded: /root/.ydk/docker.for.mac.host.internal_2230
2018-05-01 08:10:24,711 - ydk - INFO - Connected to docker.for.mac.host.internal on port 2230 using ssh with timeout of -1
2018-05-01 08:10:24,712 - ydk - INFO - Executing CRUD read operation on [Cisco-IOS-XR-ifmgr-cfg:interface-configurations]
2018-05-01 08:10:24,713 - ydk - ERROR - Data is invalid according to the yang model. Error details: Invalid keyword "[0-9]|25[0-5])\.){3}([1-9]?[0-9]|1[0-9][0-9]|2[0-4][0-9]"".
2018-05-01 08:10:24,713 - ydk - ERROR - Data is invalid according to the yang model. Error details: Module "Cisco-IOS-XR-types" parsing failed.
2018-05-01 08:10:24,713 - ydk - ERROR - Data is invalid according to the yang model. Error details: Importing "Cisco-IOS-XR-types" module into "Cisco-IOS-XR-ifmgr-cfg" failed.
2018-05-01 08:10:24,714 - ydk - ERROR - Data is invalid according to the yang model. Error details: Module "Cisco-IOS-XR-ifmgr-cfg" parsing failed.
2018-05-01 08:10:24,714 - ydk - ERROR - Data is invalid according to the yang model. Error details: Invalid keyword "[0-9]|25[0-5])\.){3}([1-9]?[0-9]|1[0-9][0-9]|2[0-4][0-9]"".
2018-05-01 08:10:24,714 - ydk - ERROR - Data is invalid according to the yang model. Error details: Module "Cisco-IOS-XR-types" parsing failed.
2018-05-01 08:10:24,715 - ydk - ERROR - Data is invalid according to the yang model. Error details: Importing "Cisco-IOS-XR-types" module into "Cisco-IOS-XR-ifmgr-cfg" failed.
2018-05-01 08:10:24,715 - ydk - ERROR - Data is invalid according to the yang model. Error details: Module "Cisco-IOS-XR-ifmgr-cfg" parsing failed.
2018-05-01 08:10:24,715 - ydk - ERROR - Data is invalid according to the yang model. Error details: Module not found. Path: '/Cisco-IOS-XR-ifmgr-cfg'
2018-05-01 08:10:24,715 - ydk - ERROR - Path 'Cisco-IOS-XR-ifmgr-cfg:interface-configurations' is invalid
Traceback (most recent call last):
  File "./nc_read_test_sh.py", line 78, in <module>
    interface_configurations = crud.read(provider, interface_configurations)
  File "/usr/local/lib/python2.7/dist-packages/ydk/services/crud_service.py", line 63, in read
    read_entity = self._crud.read(provider, filters)
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/ydk/errors/error_handler.py", line 82, in handle_runtime_error
    _raise(_exc)
  File "/usr/local/lib/python2.7/dist-packages/ydk/errors/error_handler.py", line 56, in _raise
    raise exc
ydk.errors.YInvalidArgumentError:  Path is invalid: Cisco-IOS-XR-ifmgr-cfg:interface-configurations

```

## System Information

Running docker image on Mac OSX Sierra.  Image = ydkdev/ydk-py:latest

Output of pip list on docker image
pip (8.1.1)
pybind11 (2.2.2)
setuptools (20.7.0)
wheel (0.29.0)
ydk (0.7.1)
ydk-models-cisco-ios-xe (16.8.1)
ydk-models-cisco-ios-xr (6.3.2)
ydk-models-ietf (0.1.5)
ydk-models-openconfig (0.1.5)

Python Version
Python 2.7.12

XRv running 6.1.2
RP/0/RP0/CPU0:My_XR#sh ver
Tue May  1 07:59:26.890 UTC

Cisco IOS XR Software, Version 6.1.2
Copyright (c) 2013-2016 by Cisco Systems, Inc.

Build Information:
 Built By     : ahoang
 Built On     : Fri Nov 11 05:35:50 PST 2016
 Build Host   : iox-lnx-024
 Workspace    : /auto/srcarchive11/production/6.1.2/iosxrv-x64/workspace
 Version      : 6.1.2
 Location     : /opt/cisco/XR/packages/

cisco IOS XRv x64 () processor

**Comment by abhikeshav** [comment]
This is a bug with the XR 6.1.2 model which has an invalid usage. So it cannot be used with YDK directly. See this community message for details: https://communities.cisco.com/message/288550#288550

As a workaround, you could try editing the [model](https://github.com/YangModels/yang/blob/master/vendor/cisco/xr/612/Cisco-IOS-XR-types.yang#L110) located in `/root/.ydk/docker.for.mac.host.internal_2230/Cisco-IOS-XR-types.yang` to change the pattern from double quote to single quote
