### ISSUE TITLE
Latest ydk-gen pull generates ydk with error

### ISSUE THREAD

**Issue by GregoryBrown** [CiscoDevNet/ydk-gen#86]
>>> from ydk.providers import NetconfServiceProvider
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gregorbr/yang-6.1.1-tests/local/lib/python2.7/site-packages/ydk/providers/__init__.py", line 24, in <module>
    from .netconf_provider import NetconfServiceProvider
  File "/home/gregorbr/yang-6.1.1-tests/local/lib/python2.7/site-packages/ydk/providers/netconf_provider.py", line 24, in <module>
    from ._network_element import _NetworkElement
  File "/home/gregorbr/yang-6.1.1-tests/local/lib/python2.7/site-packages/ydk/providers/_network_element.py", line 23, in <module>
    from ._provider_plugin import _NCClientSPPlugin
  File "/home/gregorbr/yang-6.1.1-tests/local/lib/python2.7/site-packages/ydk/providers/_provider_plugin.py", line 32, in <module>
    from ._decoder import XmlDecoder
  File "/home/gregorbr/yang-6.1.1-tests/local/lib/python2.7/site-packages/ydk/providers/_decoder.py", line 28, in <module>
    from ydk.services.meta_service import MetaService
  File "/home/gregorbr/yang-6.1.1-tests/local/lib/python2.7/site-packages/ydk/services/__init__.py", line 30, in <module>
    from .netconf_service import Datastore
  File "/home/gregorbr/yang-6.1.1-tests/local/lib/python2.7/site-packages/ydk/services/netconf_service.py", line 25, in <module>
    from ydk.models.ietf import ietf_netconf
ImportError: No module named ietf

**Comment by GregoryBrown** [comment]
Profile json file:

{
    "version": "0.1.0",
    "Author": "Cisco",
    "Copyright": "Cisco",
    "Description": "Cisco IOS-XR Native Models From Git",
    "models": {
	"dir": [
	    "/home/gregorbr/yang_profiles/6.1.1_yang_files"
	]
    }
}
