### ISSUE TITLE
gNMI service fails to read single openconfig interface from XR

### ISSUE THREAD

**Issue by ygorelik** [CiscoDevNet/ydk-gen#865]
## Current Behavior

gNMI service fails to read single openconfig interface from XR, YDK generates error 'invalid format string'

The service succeeds to read all openconfig interfaces from XR.

The issue is not observed with Netconf

## Your Script

```
#!/usr/bin/env python
#
"""
Test case for issue 849
Namespace prefix payload error
(https://github.com/CiscoDevNet/ydk-gen/issues/849)

libyang issue 703
(https://github.com/CESNET/libyang/issues/703)
"""

from ydk.services import CodecService, CRUDService
from ydk.providers import CodecServiceProvider
from ydk.path import Repository
from ydk.gnmi.providers import gNMIServiceProvider
from ydk.providers import NetconfServiceProvider

from ydk.models.openconfig import openconfig_interfaces as oc_interfaces

import os
import logging

from test_utils import print_entity, enable_logging

def test1(provider, crud):
    ifcs = oc_interfaces.Interfaces()
    output = crud.read(provider, ifcs)
    print_entity(output, provider.get_session().get_root_schema())
    
def test2(provider, crud):
    ifc = oc_interfaces.Interfaces.Interface()
    ifc.name = 'TenGigE0/0/0/0'
    
    # read data from gNMI device
    output = crud.read(provider, ifc)
    print_entity(output, provider.get_session().get_root_schema())
    
if __name__ == "__main__":

    enable_logging(logging.INFO)

    
    # create gNMI provider
    repo = Repository('/home/yan/.ydk/172.27.150.154_830')
    provider = gNMIServiceProvider(repo=repo,
                                   address='172.27.150.154',
                                   port=57800,
                                   username='root',
                                   password='Cisco123!')
    crud = CRUDService()

    # succeeds
    test1(provider, crud)

    # fails
    test2(provider, crud)
```
The `test1` succeeds, while `test2` fails.
## Logs
Enable [logging](http://ydk.cisco.com/py/docs/guides/introduction.html#logging) and post the logs below

The failure part of the log:
```
2019-01-25 16:30:10,104 - ydk - INFO - Executing CRUD read operation on [openconfig-interfaces:interfaces]
2019-01-25 16:30:10,110 - ydk - INFO - 
=============== Get Request Sent ================
path {
  origin: "openconfig-interfaces"
  elem {
    name: "interfaces"
  }
  elem {
    name: "interface"
    key {
      key: "name"
      value: "TenGigE0/0/0/0"
    }
  }
}
encoding: JSON_IETF


Traceback (most recent call last):
  File "/home/yan/ydk-workspace/ydk-gen/scripts/tests/test_XXX.py", line 56, in <module>
    test2(provider, crud)
  File "/home/yan/ydk-workspace/ydk-gen/scripts/tests/test_XXX.py", line 35, in test2
    output = crud.read(provider, ifc)
  File "/usr/local/lib/python2.7/dist-packages/ydk/services/crud_service.py", line 65, in read
    read_top_entity = self._crud.read(provider, top_filters)
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/ydk/errors/error_handler.py", line 82, in handle_runtime_error
    _raise(_exc)
  File "/usr/local/lib/python2.7/dist-packages/ydk/errors/error_handler.py", line 56, in _raise
    raise exc
ydk.errors.YError: invalid format string
2019-01-25 16:30:10,168 - ydk - INFO - Disconnected from device
```

## System Information
YDK-0.8.1, model bundle ydk-model-openconfig

**Comment by ygorelik** [comment]
The issue appears due to specific XR gNMI server handling of string value keys - it expects the key value to be enclosed in double-quotes. XR defect CSCvk26949.
The YDK handles correctly the query when string key value is enclosed in double-quotes. In the script above the key must be defind like this:
```
    ifc.name = '"TenGigE0/0/0/0"'
```
With corrected key value we get:
```
2019-01-29 14:33:00,802 - ydk - INFO - gNMIServiceProvider Connected to 172.27.150.154 via Insecure Channel
2019-01-29 14:33:00,823 - ydk - INFO - Executing CRUD read operation on [openconfig-interfaces:interfaces]
2019-01-29 14:33:00,828 - ydk - INFO - 
=============== Get Request Sent ================
path {
  origin: "openconfig-interfaces"
  elem {
    name: "interfaces"
  }
  elem {
    name: "interface"
    key {
      key: "name"
      value: "\"TenGigE0/0/0/0\""
    }
  }
}
encoding: JSON_IETF


2019-01-29 14:33:01,134 - ydk - INFO - 
============= Get Response Received =============
notification {
  timestamp: 1548772380349551597
  update {
    path {
      origin: "openconfig-interfaces"
      elem {
        name: "interfaces"
      }
      elem {
        name: "interface"
        key {
          key: "name"
          value: "\"TenGigE0/0/0/0\""
        }
      }
    }
    val {
      json_ietf_val: "[{\"name\":\"TenGigE0/0/0/0\",\"config\":{\"name\":\"TenGigE0/0/0/0\",\"type\":\"iana-if-type:ethernetCsmacd\",\"enabled\":false},\"state\":{\"name\":\"TenGigE0/0/0/0\",\"enabled\":true,\"type\":\"iana-if-type:ethernetCsmacd\",\"admin-status\":\"DOWN\",\"oper-status\":\"DOWN\",\"mtu\":1514,\"last-change\":1700864,\"counters\":{\"in-unicast-pkts\":\"0\",\"in-octets\":\"0\",\"out-unicast-pkts\":\"0\",\"out-octets\":\"0\",\"in-multicast-pkts\":\"0\",\"in-broadcast-pkts\":\"0\",\"out-multicast-pkts\":\"0\",\"out-broadcast-pkts\":\"0\",\"out-discards\":\"0\",\"in-discards\":\"0\",\"in-unknown-protos\":0,\"in-errors\":\"0\",\"out-errors\":\"0\",\"last-clear\":\"2019-01-09T22:02:18.340+00:00\"},\"ifindex\":52},\"openconfig-if-ethernet:ethernet\":{\"config\":{\"auto-negotiate\":false},\"state\":{\"auto-negotiate\":false,\"hw-mac-address\":\"00:c1:64:3c:b0:4c\",\"counters\":{\"in-8021q-frames\":\"0\",\"in-mac-pause-frames\":\"0\",\"in-oversize-frames\":\"0\",\"in-jabber-frames\":\"0\",\"in-fragment-frames\":\"0\",\"in-crc-errors\":\"0\",\"out-8021q-frames\":\"0\",\"out-mac-pause-frames\":\"0\"}}}}]"
    }
  }
}
error {
}


2019-01-29 14:33:01,134 - ydk - INFO - Get Operation Succeeded
2019-01-29 14:33:01,136 - ydk - ERROR - Cannot find model with module name '2019-01-09T22'
2019-01-29 14:33:01,136 - ydk - ERROR - Data is invalid according to the yang model. Libyang error: Data model "2019-01-09T22" not found.
2019-01-29 14:33:01,188 - ydk - ERROR - Cannot find model with module name '2019-01-09T22'
2019-01-29 14:33:01,189 - ydk - ERROR - Data is invalid according to the yang model. Libyang error: Data model "2019-01-09T22" not found.

=====>  Printing DataNode: '/openconfig-interfaces:interfaces'
<interfaces>
  <interface>
    <name>TenGigE0/0/0/0</name>
    <config>
      <type>iana-if-type:ethernetCsmacd</type>
      <name>TenGigE0/0/0/0</name>
      <enabled>false</enabled>
    </config>
    <state>
      <type>iana-if-type:ethernetCsmacd</type>
      <mtu>1514</mtu>
      <name>TenGigE0/0/0/0</name>
      <enabled>true</enabled>
      <ifindex>52</ifindex>
      <admin-status>DOWN</admin-status>
      <oper-status>DOWN</oper-status>
      <last-change>1700864</last-change>
      <counters>
        <in-octets>0</in-octets>
        <in-unicast-pkts>0</in-unicast-pkts>
        <in-broadcast-pkts>0</in-broadcast-pkts>
        <in-multicast-pkts>0</in-multicast-pkts>
        <in-discards>0</in-discards>
        <in-errors>0</in-errors>
        <in-unknown-protos>0</in-unknown-protos>
        <out-octets>0</out-octets>
        <out-unicast-pkts>0</out-unicast-pkts>
        <out-broadcast-pkts>0</out-broadcast-pkts>
        <out-multicast-pkts>0</out-multicast-pkts>
        <out-discards>0</out-discards>
        <out-errors>0</out-errors>
        <last-clear>2019-01-09T22:02:18.340+00:00</last-clear>
      </counters>
    </state>
    <ethernet>
      <config>
        <auto-negotiate>false</auto-negotiate>
      </config>
      <state>
        <auto-negotiate>false</auto-negotiate>
        <hw-mac-address>00:c1:64:3c:b0:4c</hw-mac-address>
        <counters>
          <in-mac-pause-frames>0</in-mac-pause-frames>
          <in-oversize-frames>0</in-oversize-frames>
          <in-jabber-frames>0</in-jabber-frames>
          <in-fragment-frames>0</in-fragment-frames>
          <in-8021q-frames>0</in-8021q-frames>
          <in-crc-errors>0</in-crc-errors>
          <out-mac-pause-frames>0</out-mac-pause-frames>
          <out-8021q-frames>0</out-8021q-frames>
        </counters>
      </state>
    </ethernet>
  </interface>
</interfaces>

2019-01-29 14:33:01,201 - ydk - INFO - Disconnected from device
```
