### ISSUE TITLE
pip install ydk fails on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by balbalas** [CiscoDevNet/ydk-gen#883]
Issue tracker is ONLY used for reporting bugs. Please use the [YDK Community](https://communities.cisco.com/community/developer/ydk) for any support issues.

## Expected Behavior
Install should succeed. 

## Current Behavior
Fails with an error

## Steps to Reproduce
vagrant@ubuntu-xenial:~/Repo/yang2api$ pipenv --python=2.7
Creating a virtualenv for this project...
Pipfile: /home/vagrant/Repo/yang2api/Pipfile
Using /usr/bin/python2.7 (2.7.15rc1) to create virtualenv...
⠧ Creating virtual environment...New python executable in /home/vagrant/.local/share/virtualenvs/yang2api-OPEdbTO0/bin/python2.7
Also creating executable in /home/vagrant/.local/share/virtualenvs/yang2api-OPEdbTO0/bin/python
Installing setuptools, pip, wheel...
done.
Running virtualenv with interpreter /usr/bin/python2.7

✔ Successfully created virtual environment!
Virtualenv location: /home/vagrant/.local/share/virtualenvs/yang2api-OPEdbTO0
Creating a Pipfile for this project...
vagrant@ubuntu-xenial:~/Repo/yang2api$ pipenv shell
Launching subshell in virtual environment...
 . /home/vagrant/.local/share/virtualenvs/yang2api-OPEdbTO0/bin/activate
vagrant@ubuntu-xenial:~/Repo/yang2api$  . /home/vagrant/.local/share/virtualenvs/yang2api-OPEdbTO0/bin/activate
(yang2api) vagrant@ubuntu-xenial:~/Repo/yang2api$
(yang2api) vagrant@ubuntu-xenial:~/Repo/yang2api$
(yang2api) vagrant@ubuntu-xenial:~/Repo/yang2api$
(yang2api) vagrant@ubuntu-xenial:~/Repo/yang2api$
(yang2api) vagrant@ubuntu-xenial:~/Repo/yang2api$ pipenv install ydk
Installing ydk...
Adding ydk to Pipfile's [packages]...
✔ Installation Succeeded
Pipfile.lock not found, creating...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
✔ Success!
Updated Pipfile.lock (3bd472)!
Installing dependencies from Pipfile.lock (3bd472)...
An error occurred while installing ydk==0.8.1 --hash=sha256:7475d23e75ba4c236ca6761df047574542bd76857034771bd328b56c3f28b232! Will try again.
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 2/2 — 00:00:27
Installing initially failed dependencies...
  ☤  ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/1 — 00:00:00

## Logs
Enable [logging](http://ydk.cisco.com/py/docs/guides/introduction.html#logging) and post the logs below

```
Installing initially failed dependencies...
  ☤  ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/1 — 00:00:00

[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python2.7/dist-packages/pipenv/core.py", line 1992, in do_install
[pipenv.exceptions.InstallError]:       skip_lock=skip_lock,
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python2.7/dist-packages/pipenv/core.py", line 1253, in do_init
[pipenv.exceptions.InstallError]:       pypi_mirror=pypi_mirror,
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python2.7/dist-packages/pipenv/core.py", line 859, in do_install_dependencies
[pipenv.exceptions.InstallError]:       retry_list, procs, failed_deps_queue, requirements_dir, **install_kwargs
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python2.7/dist-packages/pipenv/core.py", line 763, in batch_install
[pipenv.exceptions.InstallError]:       _cleanup_procs(procs, not blocking, failed_deps_queue, retry=retry)
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python2.7/dist-packages/pipenv/core.py", line 681, in _cleanup_procs
[pipenv.exceptions.InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
[pipenv.exceptions.InstallError]: ['Collecting ydk==0.8.1 (from -r /tmp/pipenv-kR2Fyz-requirements/pipenv-ozeksE-requirement.txt (line 1))', '  Using cached https://files.pythonhosted.org/packages/1b/6e/ec0664d282cdfb9f0f50e74fb59a404ee1897fe007238e08dbe6bb8be3f2/ydk-0.8.1.tar.gz', 'Building wheels for collected packages: ydk', '  Building wheel for ydk (setup.py): started', "  Building wheel for ydk (setup.py): finished with status 'error'", '  Complete output from command /home/vagrant/.local/share/virtualenvs/yang2api-OPEdbTO0/bin/python2.7 -u -c "import setuptools, tokenize;__file__=\'/tmp/pip-install-fCibKM/ydk/setup.py\';f=getattr(tokenize, \'open\', open)(__file__);code=f.read().replace(\'\\r\\n\', \'\\n\');f.close();exec(compile(code, __file__, \'exec\'))" bdist_wheel -d /tmp/pip-wheel-B33iaP --python-tag cp27:', '  running bdist_wheel', '  running build', '  running build_py', '  creating build', '  creating build/lib.linux-x86_64-2.7', '  creating build/lib.linux-x86_64-2.7/ydk', '  copying ydk/__init__.py -> build/lib.linux-x86_64-2.7/ydk', '  copying ydk/exthook.py -> build/lib.linux-x86_64-2.7/ydk', '  creating build/lib.linux-x86_64-2.7/ydk/providers', '  copying ydk/providers/__init__.py -> build/lib.linux-x86_64-2.7/ydk/providers', '  copying ydk/providers/codec_provider.py -> build/lib.linux-x86_64-2.7/ydk/providers', '  copying ydk/providers/netconf_provider.py -> build/lib.linux-x86_64-2.7/ydk/providers', '  creating build/lib.linux-x86_64-2.7/ydk/ext', '  copying ydk/ext/__init__.py -> build/lib.linux-x86_64-2.7/ydk/ext', '  creating build/lib.linux-x86_64-2.7/ydk/models', '  copying ydk/models/__init__.py -> build/lib.linux-x86_64-2.7/ydk/models', '  creating build/lib.linux-x86_64-2.7/ydk/path', '  copying ydk/path/__init__.py -> build/lib.linux-x86_64-2.7/ydk/path', '  creating build/lib.linux-x86_64-2.7/ydk/errors', '  copying ydk/errors/__init__.py -> build/lib.linux-x86_64-2.7/ydk/errors', '  copying ydk/errors/error_handler.py -> build/lib.linux-x86_64-2.7/ydk/errors', '  creating build/lib.linux-x86_64-2.7/ydk/types', '  copying ydk/types/__init__.py -> build/lib.linux-x86_64-2.7/ydk/types', '  copying ydk/types/py_types.py -> build/lib.linux-x86_64-2.7/ydk/types', '  creating build/lib.linux-x86_64-2.7/ydk/_core', '  copying ydk/_core/__init__.py -> build/lib.linux-x86_64-2.7/ydk/_core', '  copying ydk/_core/_importer.py -> build/lib.linux-x86_64-2.7/ydk/_core', '  copying ydk/_core/_dm_meta_info.py -> build/lib.linux-x86_64-2.7/ydk/_core', '  creating build/lib.linux-x86_64-2.7/ydk/entity_utils', '  copying ydk/entity_utils/__init__.py -> build/lib.linux-x86_64-2.7/ydk/entity_utils', '  copying ydk/entity_utils/entity_utils.py -> build/lib.linux-x86_64-2.7/ydk/entity_utils', '  creating build/lib.linux-x86_64-2.7/ydk/filters', '  copying ydk/filters/__init__.py -> build/lib.linux-x86_64-2.7/ydk/filters', '  creating build/lib.linux-x86_64-2.7/ydk/logging', '  copying ydk/logging/__init__.py -> build/lib.linux-x86_64-2.7/ydk/logging', '  creating build/lib.linux-x86_64-2.7/ydk/services', '  copying ydk/services/executor_service.py -> build/lib.linux-x86_64-2.7/ydk/services', '  copying ydk/services/netconf_service.py -> build/lib.linux-x86_64-2.7/ydk/services', '  copying ydk/services/__init__.py -> build/lib.linux-x86_64-2.7/ydk/services', '  copying ydk/services/codec_service.py -> build/lib.linux-x86_64-2.7/ydk/services', '  copying ydk/services/crud_service.py -> build/lib.linux-x86_64-2.7/ydk/services', '  creating build/lib.linux-x86_64-2.7/ydk/path/sessions', '  copying ydk/path/sessions/__init__.py -> build/lib.linux-x86_64-2.7/ydk/path/sessions', '  copying ydk/path/sessions/restconf_session.py -> build/lib.linux-x86_64-2.7/ydk/path/sessions', '  copying ydk/path/sessions/netconf_session.py -> build/lib.linux-x86_64-2.7/ydk/path/sessions', '  warning: build_py: byte-compiling is disabled, skipping.', '  ', '  running build_ext', '  -- The C compiler identification is GNU 5.5.0', '  -- The CXX compiler identification is GNU 5.5.0', '  -- Check for working C compiler: /usr/bin/cc', '  -- Check for working C compiler: /usr/bin/cc -- works', '  -- Detecting C compiler ABI info', '  -- Detecting C compiler ABI info - done', '  -- Detecting C compile features', '  -- Detecting C compile features - done', '  -- Check for working CXX compiler: /usr/bin/c++', '  -- Check for working CXX compiler: /usr/bin/c++ -- works', '  -- Detecting CXX compiler ABI info', '  -- Detecting CXX compiler ABI info - done', '  -- Detecting CXX compile features', '  -- Detecting CXX compile features - done', '  python version: 2.7', '  -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found version "2.7.15rc1")', '  pybind11 include: /home/vagrant/.local/share/virtualenvs/yang2api-OPEdbTO0/include/site/python2.7;/home/vagrant/.local/share/virtualenvs/yang2api-OPEdbTO0/include/site/python2.7', '  -- Configuring done', '  -- Generating done', '  -- Build files have been written to: /tmp/pip-install-fCibKM/ydk/build/temp.linux-x86_64-2.7', '  Scanning dependencies of target ydk_', '  [ 50%] Building CXX object CMakeFiles/ydk_.dir/python.cpp.o', '  /tmp/pip-install-fCibKM/ydk/python.cpp:539:39: warning: unused parameter \xe2\x80\x98left\xe2\x80\x99 [-Wunused-parameter]', '           .def("__eq__", [](ydk::Empty& left, ydk::Empty& right)', '                                         ^', '  /tmp/pip-install-fCibKM/ydk/python.cpp:539:57: warning: unused parameter \xe2\x80\x98right\xe2\x80\x99 [-Wunused-parameter]', '           .def("__eq__", [](ydk::Empty& left, ydk::Empty& right)', '                                                           ^', '  /tmp/pip-install-fCibKM/ydk/python.cpp:543:39: warning: unused parameter \xe2\x80\x98left\xe2\x80\x99 [-Wunused-parameter]', '           .def("__ne__", [](ydk::Empty& left, ydk::Empty& right)', '                                         ^', '  /tmp/pip-install-fCibKM/ydk/python.cpp:543:57: warning: unused parameter \xe2\x80\x98right\xe2\x80\x99 [-Wunused-parameter]', '           .def("__ne__", [](ydk::Empty& left, ydk::Empty& right)', '                                                           ^', '  virtual memory exhausted: Cannot allocate memory', "  CMakeFiles/ydk_.dir/build.make:62: recipe for target 'CMakeFiles/ydk_.dir/python.cpp.o' failed", '  make[2]: *** [CMakeFiles/ydk_.dir/python.cpp.o] Error 1', "  CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/ydk_.dir/all' failed", '  make[1]: *** [CMakeFiles/ydk_.dir/all] Error 2', "  Makefile:83: recipe for target 'all' failed", '  make: *** [all] Error 2', '  Traceback (most recent call last):', '    File "<string>", line 1, in <module>', '    File "/tmp/pip-install-fCibKM/ydk/setup.py", line 145, in <module>', '      zip_safe=False,', '    File "/home/vagrant/.local/share/virtualenvs/yang2api-OPEdbTO0/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup', '      return distutils.core.setup(**attrs)', '    File "/usr/lib/python2.7/distutils/core.py", line 151, in setup', '      dist.run_commands()', '    File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands', '      self.run_command(cmd)', '    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command', '      cmd_obj.run()', '    File "/home/vagrant/.local/share/virtualenvs/yang2api-OPEdbTO0/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 192, in run', "      self.run_command('build')", '    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command', '      self.distribution.run_command(command)', '    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command', '      cmd_obj.run()', '    File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run', '      self.run_command(cmd_name)', '    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command', '      self.distribution.run_command(command)', '    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command', '      cmd_obj.run()', '    File "/tmp/pip-install-fCibKM/ydk/setup.py", line 68, in run', '      self.build_extension(ext)', '    File "/tmp/pip-install-fCibKM/ydk/setup.py", line 101, in build_extension', "      subprocess.check_call([cmake_executable, '--build', '.'], cwd=self.build_temp)", '    File "/usr/lib/python2.7/subprocess.py", line 190, in check_call', '      raise CalledProcessError(retcode, cmd)', "  subprocess.CalledProcessError: Command '['cmake', '--build', '.']' returned non-zero exit status 2", '  ', '  ----------------------------------------', '  Running setup.py clean for ydk', 'Failed to build ydk', 'Installing collected packages: ydk', '  Running setup.py install for ydk: started', "    Running setup.py install for ydk: finished with status 'error'", '    Complete output from command /home/vagrant/.local/share/virtualenvs/yang2api-OPEdbTO0/bin/python2.7 -u -c "import setuptools, tokenize;__file__=\'/tmp/pip-install-fCibKM/ydk/setup.py\';f=getattr(tokenize, \'open\', open)(__file__);code=f.read().replace(\'\\r\\n\', \'\\n\');f.close();exec(compile(code, __file__, \'exec\'))" install --record /tmp/pip-record-DNTbZ9/install-record.txt --single-version-externally-managed --compile --install-headers /home/vagrant/.local/share/virtualenvs/yang2api-OPEdbTO0/include/site/python2.7/ydk:', '    running install', '    running build', '    running build_py', '    creating build', '    creating build/lib.linux-x86_64-2.7', '    creating build/lib.linux-x86_64-2.7/ydk', '    copying ydk/__init__.py -> build/lib.linux-x86_64-2.7/ydk', '    copying ydk/exthook.py -> build/lib.linux-x86_64-2.7/ydk', '    creating build/lib.linux-x86_64-2.7/ydk/providers', '    copying ydk/providers/__init__.py -> build/lib.linux-x86_64-2.7/ydk/providers', '    copying ydk/providers/codec_provider.py -> build/lib.linux-x86_64-2.7/ydk/providers', '    copying ydk/providers/netconf_provider.py -> build/lib.linux-x86_64-2.7/ydk/providers', '    creating build/lib.linux-x86_64-2.7/ydk/ext', '    copying ydk/ext/__init__.py -> build/lib.linux-x86_64-2.7/ydk/ext', '    creating build/lib.linux-x86_64-2.7/ydk/models', '    copying ydk/models/__init__.py -> build/lib.linux-x86_64-2.7/ydk/models', '    creating build/lib.linux-x86_64-2.7/ydk/path', '    copying ydk/path/__init__.py -> build/lib.linux-x86_64-2.7/ydk/path', '    creating build/lib.linux-x86_64-2.7/ydk/errors', '    copying ydk/errors/__init__.py -> build/lib.linux-x86_64-2.7/ydk/errors', '    copying ydk/errors/error_handler.py -> build/lib.linux-x86_64-2.7/ydk/errors', '    creating build/lib.linux-x86_64-2.7/ydk/types', '    copying ydk/types/__init__.py -> build/lib.linux-x86_64-2.7/ydk/types', '    copying ydk/types/py_types.py -> build/lib.linux-x86_64-2.7/ydk/types', '    creating build/lib.linux-x86_64-2.7/ydk/_core', '    copying ydk/_core/__init__.py -> build/lib.linux-x86_64-2.7/ydk/_core', '    copying ydk/_core/_importer.py -> build/lib.linux-x86_64-2.7/ydk/_core', '    copying ydk/_core/_dm_meta_info.py -> build/lib.linux-x86_64-2.7/ydk/_core', '    creating build/lib.linux-x86_64-2.7/ydk/entity_utils', '    copying ydk/entity_utils/__init__.py -> build/lib.linux-x86_64-2.7/ydk/entity_utils', '    copying ydk/entity_utils/entity_utils.py -> build/lib.linux-x86_64-2.7/ydk/entity_utils', '    creating build/lib.linux-x86_64-2.7/ydk/filters', '    copying ydk/filters/__init__.py -> build/lib.linux-x86_64-2.7/ydk/filters', '    creating build/lib.linux-x86_64-2.7/ydk/logging', '    copying ydk/logging/__init__.py -> build/lib.linux-x86_64-2.7/ydk/logging', '    creating build/lib.linux-x86_64-2.7/ydk/services', '    copying ydk/services/executor_service.py -> build/lib.linux-x86_64-2.7/ydk/services', '    copying ydk/services/netconf_service.py -> build/lib.linux-x86_64-2.7/ydk/services', '    copying ydk/services/__init__.py -> build/lib.linux-x86_64-2.7/ydk/services', '    copying ydk/services/codec_service.py -> build/lib.linux-x86_64-2.7/ydk/services', '    copying ydk/services/crud_service.py -> build/lib.linux-x86_64-2.7/ydk/services', '    creating build/lib.linux-x86_64-2.7/ydk/path/sessions', '    copying ydk/path/sessions/__init__.py -> build/lib.linux-x86_64-2.7/ydk/path/sessions', '    copying ydk/path/sessions/restconf_session.py -> build/lib.linux-x86_64-2.7/ydk/path/sessions', '    copying ydk/path/sessions/netconf_session.py -> build/lib.linux-x86_64-2.7/ydk/path/sessions', '    warning: build_py: byte-compiling is disabled, skipping.', '    ', '    running build_ext', '    -- The C compiler identification is GNU 5.5.0', '    -- The CXX compiler identification is GNU 5.5.0', '    -- Check for working C compiler: /usr/bin/cc', '    -- Check for working C compiler: /usr/bin/cc -- works', '    -- Detecting C compiler ABI info', '    -- Detecting C compiler ABI info - done', '    -- Detecting C compile features', '    -- Detecting C compile features - done', '    -- Check for working CXX compiler: /usr/bin/c++', '    -- Check for working CXX compiler: /usr/bin/c++ -- works', '    -- Detecting CXX compiler ABI info', '    -- Detecting CXX compiler ABI info - done', '    -- Detecting CXX compile features', '    -- Detecting CXX compile features - done', '    python version: 2.7', '    -- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found version "2.7.15rc1")', '    pybind11 include: /home/vagrant/.local/share/virtualenvs/yang2api-OPEdbTO0/include/site/python2.7;/home/vagrant/.local/share/virtualenvs/yang2api-OPEdbTO0/include/site/python2.7', '    -- Configuring done', '    -- Generating done', '    -- Build files have been written to: /tmp/pip-install-fCibKM/ydk/build/temp.linux-x86_64-2.7', '    Scanning dependencies of target ydk_', '    [ 50%] Building CXX object CMakeFiles/ydk_.dir/python.cpp.o', '    /tmp/pip-install-fCibKM/ydk/python.cpp:539:39: warning: unused parameter \xe2\x80\x98left\xe2\x80\x99 [-Wunused-parameter]', '             .def("__eq__", [](ydk::Empty& left, ydk::Empty& right)', '                                           ^', '    /tmp/pip-install-fCibKM/ydk/python.cpp:539:57: warning: unused parameter \xe2\x80\x98right\xe2\x80\x99 [-Wunused-parameter]', '             .def("__eq__", [](ydk::Empty& left, ydk::Empty& right)', '                                                             ^', '    /tmp/pip-install-fCibKM/ydk/python.cpp:543:39: warning: unused parameter \xe2\x80\x98left\xe2\x80\x99 [-Wunused-parameter]', '             .def("__ne__", [](ydk::Empty& left, ydk::Empty& right)', '                                           ^', '    /tmp/pip-install-fCibKM/ydk/python.cpp:543:57: warning: unused parameter \xe2\x80\x98right\xe2\x80\x99 [-Wunused-parameter]', '             .def("__ne__", [](ydk::Empty& left, ydk::Empty& right)', '                                                             ^', '    virtual memory exhausted: Cannot allocate memory', "    CMakeFiles/ydk_.dir/build.make:62: recipe for target 'CMakeFiles/ydk_.dir/python.cpp.o' failed", '    make[2]: *** [CMakeFiles/ydk_.dir/python.cpp.o] Error 1', "    CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/ydk_.dir/all' failed", '    make[1]: *** [CMakeFiles/ydk_.dir/all] Error 2', "    Makefile:83: recipe for target 'all' failed", '    make: *** [all] Error 2', '    Traceback (most recent call last):', '      File "<string>", line 1, in <module>', '      File "/tmp/pip-install-fCibKM/ydk/setup.py", line 145, in <module>', '        zip_safe=False,', '      File "/home/vagrant/.local/share/virtualenvs/yang2api-OPEdbTO0/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup', '        return distutils.core.setup(**attrs)', '      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup', '        dist.run_commands()', '      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands', '        self.run_command(cmd)', '      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command', '        cmd_obj.run()', '      File "/home/vagrant/.local/share/virtualenvs/yang2api-OPEdbTO0/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run', '        return orig.install.run(self)', '      File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run', "        self.run_command('build')", '      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command', '        self.distribution.run_command(command)', '      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command', '        cmd_obj.run()', '      File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run', '        self.run_command(cmd_name)', '      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command', '        self.distribution.run_command(command)', '      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command', '        cmd_obj.run()', '      File "/tmp/pip-install-fCibKM/ydk/setup.py", line 68, in run', '        self.build_extension(ext)', '      File "/tmp/pip-install-fCibKM/ydk/setup.py", line 101, in build_extension', "        subprocess.check_call([cmake_executable, '--build', '.'], cwd=self.build_temp)", '      File "/usr/lib/python2.7/subprocess.py", line 190, in check_call', '        raise CalledProcessError(retcode, cmd)', "    subprocess.CalledProcessError: Command '['cmake', '--build', '.']' returned non-zero exit status 2", '    ', '    ----------------------------------------']
[pipenv.exceptions.InstallError]: ["DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.", '  Failed building wheel for ydk', 'Command "/home/vagrant/.local/share/virtualenvs/yang2api-OPEdbTO0/bin/python2.7 -u -c "import setuptools, tokenize;__file__=\'/tmp/pip-install-fCibKM/ydk/setup.py\';f=getattr(tokenize, \'open\', open)(__file__);code=f.read().replace(\'\\r\\n\', \'\\n\');f.close();exec(compile(code, __file__, \'exec\'))" install --record /tmp/pip-record-DNTbZ9/install-record.txt --single-version-externally-managed --compile --install-headers /home/vagrant/.local/share/virtualenvs/yang2api-OPEdbTO0/include/site/python2.7/ydk" failed with error code 1 in /tmp/pip-install-fCibKM/ydk/']
ERROR: ERROR: Package installation failed...
  ☤  ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/1 — 00:00:56
```

## System Information

yang2api) vagrant@ubuntu-xenial:~/Repo/yang2api$ python --version
Python 2.7.15rc1
(yang2api) vagrant@ubuntu-xenial:~/Repo/yang2api$ pipenv --version
pipenv, version 2018.11.26
(yang2api) vagrant@ubuntu-xenial:~/Repo/yang2api$ pip --version
pip 19.0.3 from /home/vagrant/.local/share/virtualenvs/yang2api-OPEdbTO0/lib/python2.7/site-packages/pip (python 2.7)
(yang2api) vagrant@ubuntu-xenial:~/Repo/yang2api$ uname -a
Linux ubuntu-xenial 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by 111pontes** [comment]
Please provide the output of `lsb_release -a`.  Make sure you follow all the installation steps including [system requirements](http://ydk.cisco.com/py/docs/getting_started.html#ubuntu-debian-based) for the matching Ubuntu release.  You may want to raise the question in the [YDK community](https://community.cisco.com/t5/yang-development-kit-ydk/bd-p/5475j-disc-dev-net-ydk) first as it is unclear that an issue really exists at this point.  Also, if you're looking for a vagrant box, we have a [YDK-PY Vagrant box](https://community.cisco.com/t5/yang-development-kit-ydk/vagrant-sandbox-updated-with-release-0-8-1/m-p/3808142) available.

**Comment by 111pontes** [comment]
Any update?
