### ISSUE TITLE
All elements of keyless list have the same segment path

### ISSUE THREAD

**Issue by ygorelik** [CiscoDevNet/ydk-gen#946]
Reported by ATOM team, which employs YDK-0.5.5. 

# Expected Behavior
All element in the list should have different segment paths.
## Current Behavior
All elements of keyless list have the same segment path.
The implication of this issue is that children map can store only last inserted element of keyless list.

## Steps to Reproduce
Add multiple elements to keyless list. then try to retrieve them by accessing parent entity children map.

## Your Script
Yang model:
```
  container runner {
    list no-key-list {
        config false;
        container test {
            leaf best {
                type string;
            }
        }
    }
  }
```
Script to run:
```
import unittest
import logging

from ydk.types import entity_to_dict

try:
    from ydk.models.ydktest.ydktest_sanity import Runner
    from ydk.models.ydktest import ydktest_sanity as ysanity
except ImportError:
    from ydk.models.ydktest.ydktest_sanity.runner.runner import Runner

def enable_logging(level):
    log = logging.getLogger('ydk')
    log.setLevel(level)
    handler = logging.StreamHandler()
    formatter = logging.Formatter(("%(asctime)s - %(name)s - %(levelname)s - %(message)s"))
    handler.setFormatter(formatter)
    log.addHandler(handler)

class SanityYang(unittest.TestCase):

    def test_keyless_list(self):
        test1 = ysanity.Runner.NoKeyList.Test()
        test1.test = 't1'
        test2 = ysanity.Runner.NoKeyList.Test()
        test2.test = 't2'
        test3 = ysanity.Runner.NoKeyList.Test()
        test3.test = 't3'

        runner = Runner()
        runner.no_key_list.extend([test1, test2, test3])

        ent_dict = entity_to_dict(runner)
        self.assertEqual(len(ent_dict), 3)


if __name__ == '__main__':
    import sys
    if len(sys.argv) > 1:
        SanityYang.PROVIDER_TYPE = sys.argv.pop()
    enable_logging(logging.DEBUG)
    suite = unittest.TestLoader().loadTestsFromTestCase(SanityYang)
    ret = not unittest.TextTestRunner(verbosity=2).run(suite).wasSuccessful()
    sys.exit(ret)
```

## Logs

```
Testing started at 2:48 PM ...
/home/yan/.virtualenvs/ydk55/bin/python3.5 /home/yan/Downloads/pycharm-community-2019.1.1/helpers/pycharm/_jb_unittest_runner.py --path /home/yan/ydk-workspace/ydk-0.5.5/ydk-gen/test/test-cases/python/tests/test_keyless_list.py
Launching unittests with arguments python -m unittest /home/yan/ydk-workspace/ydk-0.5.5/ydk-gen/test/test-cases/python/tests/test_keyless_list.py in /home/yan/ydk-workspace/ydk-0.5.5/ydk-gen/test/test-cases/python/tests


Ran 1 test in 0.006s

FAILED (failures=1)


3 != 0

Expected :0
Actual   :3
<Click to see difference>

Traceback (most recent call last):
  File "/home/yan/Downloads/pycharm-community-2019.1.1/helpers/pycharm/teamcity/diff_tools.py", line 32, in _patched_equals
    old(self, first, second, msg)
  File "/usr/lib/python3.5/unittest/case.py", line 820, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.5/unittest/case.py", line 813, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 0 != 3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/usr/lib/python3.5/unittest/case.py", line 600, in run
    testMethod()
  File "/home/yan/ydk-workspace/ydk-0.5.5/ydk-gen/test/test-cases/python/tests/test_keyless_list.py", line 82, in test_keyless_list
    self.assertEqual(len(ent_dict), 3)


Process finished with exit code 1
```

## System Information
YDK-0.5.5

**Comment by ygorelik** [comment]
The enhancement includes the following:

1.	Absolute path for items in keyless list (issue 946).

With the enhancement the keyless list items are counted in order they were inserted into the YList. The item object would be added new attribute ‘_index’, which holds the index of the item. The absolute path of the keyless list item now includes the item index in the format: 
```
 <list-name>[<item-index>]
```
Here an example from a test included to the unit test file _ydk-gen/sdk/python/core/tests/test_entity_diff.py_:
```
class EntityDiffTest(unittest.TestCase):

    def test_entity_to_dict_no_key_list(self):
        r_1 = ysanity.Runner()
        test1 = ysanity.Runner.NoKeyList()
        test1.test.best = 't1'
        test2 = ysanity.Runner.NoKeyList()
        test2.test.best = 't2'
        r_1.no_key_list.extend([test1, test2])
        ent_dict = entity_to_dict(r_1)
        self.assertEqual(len(ent_dict), 4)
        print_dictionary('-LEFT', ent_dict, 50)
```
The script produces output:
```
------> DICTIONARY-LEFT:
             /ydktest-sanity:runner/no-key-list[0]: exists
   /ydktest-sanity:runner/no-key-list[0]/test/best: t1
             /ydktest-sanity:runner/no-key-list[1]: exists
   /ydktest-sanity:runner/no-key-list[1]/test/best: t2
```

2.	Object/entity access by absolute path.
Developed convenience function _abs_path_to_entity()_, which allows to get the object/entity from its absolute path. The API of the function:
```
abs_path_to_entity(entity, abs_path)
```
Params:
    entity – (object) any parent entity, which includes the matching entity object
    abs_path – (str), absolute path of matching object

Returns: 
    child entity object, which has matching absolute path with given _abs_path_.
    None, if no match is found.

Here is an example from the same unit test file:
```
from ydk.types import entity_to_dict, entity_diff, abs_path_to_entity

class EntityDiffTest(unittest.TestCase):

    def print_diffs(self, diff, ent_left, ent_right, key_width=70):
        print("\n------> DIFFS:")
        for key in diff:
            value = diff[key]
            print("%s: %s vs %s" % (
            key.rjust(key_width), check_empty_str_value(value[0]), check_empty_str_value(value[1])))
            if value[0] is not None:
                r = ent_left
            else:
                r = ent_right
            entity = abs_path_to_entity(r, key)
            self.assertIsNotNone(entity)
```
