### ISSUE TITLE
Netconf 'get-schema' RPC timeout error when the timeout is specified

### ISSUE THREAD

**Issue by ygorelik** [CiscoDevNet/ydk-gen#960]
## Current Behavior

The Netconf connection timeout on 'get-schema' RPC, when timeout is specified during NetconfServiceProvider initialization.

The issue does not appear when timeout is not specified.

## Steps to Reproduce

Delete cache repository in your home directory `$HOME/.ydk/<device-IP>`. 
Then execute the below script by issuing the command:
```
rm -rf ~/.ydk/172.27.150.154/*
./test_960.py -v ssh://root:'Cisco1234!'@172.27.150.154:830
```
## Your Script

```
#!/usr/bin/env python

import argparse
import logging

from urllib.parse import urlparse

from ydk.services import NetconfService, CRUDService
from ydk.providers import NetconfServiceProvider
from ydk.models.cisco_iosxr_711 import Cisco_IOS_XR_um_router_bgp_cfg as xr


def enable_logging(level):
    log = logging.getLogger('ydk')
    log.setLevel(level)
    handler = logging.StreamHandler()
    formatter = logging.Formatter(("%(asctime)s - %(name)s - %(levelname)s - %(message)s"))
    handler.setFormatter(formatter)
    log.addHandler(handler)

if __name__ == "__main__":
    """Execute main program."""

    parser = argparse.ArgumentParser()
    parser.add_argument("-v", "--verbose",
                        help="print debugging messages",
                        action="store_true")
    parser.add_argument("device",
                        help="NETCONF device (ssh://user:password@host:port)")
    args = parser.parse_args()
    device = urlparse(args.device)

    if args.verbose:
        enable_logging(logging.DEBUG)

    # create NETCONF provider and service
    provider = NetconfServiceProvider(address=device.hostname,
                                      port=device.port,
                                      username=device.username,
                                      password=device.password,
                                      protocol=device.scheme,
                                      timeout=180)
    crud = CRUDService()

    # NI configuration
    router = xr.Router()  # create object

    # get data from NETCONF device
    router_cfg = crud.read_config(provider, router)
```

## Logs

```
2019-10-04 09:35:58,100 - ydk - DEBUG - Loading module 'Cisco-IOS-XR-um-router-bgp-cfg', revision ''
2019-10-04 09:35:58,100 - ydk - DEBUG - Getting module 'Cisco-IOS-XR-um-router-bgp-cfg' submodule 'none'
2019-10-04 09:35:58,100 - ydk - DEBUG - Looking for file in folder: /users/ygorelik/.ydk/172.27.150.154
2019-10-04 09:35:58,101 - ydk - DEBUG - Opening file '/users/ygorelik/.ydk/172.27.150.154/Cisco-IOS-XR-um-router-bgp-cfg.yang'
2019-10-04 09:35:58,102 - ydk - DEBUG - File '/users/ygorelik/.ydk/172.27.150.154/Cisco-IOS-XR-um-router-bgp-cfg.yang' is not found in repository
2019-10-04 09:35:58,102 - ydk - DEBUG - Getting module 'Cisco-IOS-XR-um-router-bgp-cfg' using get-schema
2019-10-04 09:35:58,102 - ydk - DEBUG - NetconfSSHClient: NC session status: 1
2019-10-04 09:35:58,102 - ydk - DEBUG - Trace: Missing message-id in rpc.
2019-10-04 09:35:58,102 - ydk - DEBUG - Netconf SSH Client: sending RPC
2019-10-04 09:35:58,102 - ydk - DEBUG - Trace: Writing message (session 2869051160):
<?xml version="1.0"?>
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="1">
  <get-schema xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring">
    <identifier>Cisco-IOS-XR-um-router-bgp-cfg</identifier>
    <format>yang</format>
  </get-schema>
</rpc>

2019-10-04 09:35:58,102 - ydk - DEBUG - NetconfSSHClient: NC session status: 1
2019-10-04 09:35:58,102 - ydk - DEBUG - Netconf SSH Client: receiving reply RPC
2019-10-04 09:35:58,303 - ydk - DEBUG - Netconf SSH Client: processing reply
2019-10-04 09:35:58,303 - ydk - ERROR - Connection timed out
Traceback (most recent call last):
  File "./test_960.py", line 49, in <module>
    router_cfg = crud.read_config(provider, router)
  File "/auto/atom-yang/pyats_ydk8/lib/python3.6/site-packages/ydk/services/crud_service.py", line 86, in read_config
    read_top_entity = self._crud.read_config(provider, top_filters)
  File "/auto/atom-yang/local/Python3.6.4/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/auto/atom-yang/pyats_ydk8/lib/python3.6/site-packages/ydk/errors/error_handler.py", line 82, in handle_runtime_error
    _raise(_exc)
  File "/auto/atom-yang/pyats_ydk8/lib/python3.6/site-packages/ydk/errors/error_handler.py", line 54, in _raise
    exec("raise exc from None")
  File "<string>", line 1, in <module>
ydk.errors.YClientError:  Connection timed out
2019-10-04 09:35:58,347 - ydk - INFO - Disconnected from device
2019-10-04 09:35:58,349 - ydk - DEBUG - Trace: Writing message (session 2869051160):
<?xml version="1.0" encoding="UTF-8"?>
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="2">
  <close-session/>
</rpc>
```

## System Information

YDK-0.8.3

**Comment by ygorelik** [comment]
It appeared that the timeout parameter is set in **microseconds**. When set correctly the script is working fine. The default timeout setting is -1, which means infinite timeout; other important value is 0, which  corresponds to non-blocking connection.
