### ISSUE TITLE
Bundle profile description is not accurate

### ISSUE THREAD

**Issue by ygorelik** [CiscoDevNet/ydk-gen#971]
Noted by YDK user - horseinthesky. See the discussion on [Cisco Community](https://community.cisco.com/t5/yang-development-kit-ydk/building-model-bundle-for-juniper/m-p/3992045).

## Current Behavior

The [online documentation](https://github.com/CiscoDevNet/ydk-gen/tree/master/profiles#an-excerpt-from-the-readme-on-how-to-construct-a-bundle-profile) of bundle profile structure is not accurate, missing key elements. When followed by given example the bundle generation fails.
```
python3 generate.py --python --bundle ~/test/junos-19.2.json
Traceback (most recent call last):
  File "generate.py", line 492, in <module>
    output_directory = (generator.generate(options.bundle))
  File "/home/horseinthesky/ydk-gen/ydkgen/__init__.py", line 93, in generate
    return self._generate_bundle(description_file)
  File "/home/horseinthesky/ydk-gen/ydkgen/__init__.py", line 120, in _generate_bundle
    bundle_translator.translate(profile_file, tmp_file, self.ydk_root)
  File "/home/horseinthesky/ydk-gen/ydkgen/resolver/bundle_translator.py", line 198, in translate
    modules.extend(globals()[get_fun](data['models'][source],ydk_root))
  File "/home/horseinthesky/ydk-gen/ydkgen/resolver/bundle_translator.py", line 151, in get_git_attrs
    for c in g['commits']:
KeyError: 'commits'
```

## System Information
YDK-0.8.4

**Comment by ygorelik** [comment]
Resolved in release [0.8.5.](https://github.com/ygorelik/ydk-gen/tree/0.8.5)
