### ISSUE TITLE
YDK fails instantiate some of the generated bundle classes

### ISSUE THREAD

**Issue by ygorelik** [CiscoDevNet/ydk-gen#983]
Issue tracker is ONLY used for reporting bugs. Please use the [YDK Community](https://communities.cisco.com/community/developer/ydk) for any support issues.

## Expected Behavior

The generated API must be consistent and stable

## Current Behavior

Some of the objects from Cisco IOS XR 6.6.2 bundle cannot be instantiated.

## Your Script

```
from ydk.models.cisco_ios_xr import Cisco_IOS_XR_snmp_agent_cfg as cfg

es = cfg.Snmp.Notification.EntityState()
```

## Logs

```
(venv) Yakovs-Air:ydk-gen ygorelik$ python scripts/tests/divide.py 
Traceback (most recent call last):
  File "scripts/tests/divide.py", line 3, in <module>
    es = cfg.Snmp.Notification.EntityState()
  File "/Users/ygorelik/ydk-gen/venv/lib/python3.7/site-packages/ydk/models/cisco_ios_xr/Cisco_IOS_XR_snmp_agent_cfg.py", line 5235, in __init__
    self.yang_name = "entity-state"
  File "/Users/ygorelik/ydk-gen/venv/lib/python3.7/site-packages/ydk/models/cisco_ios_xr/Cisco_IOS_XR_snmp_agent_cfg.py", line 5252, in __setattr__
    self._perform_setattr(Snmp.Notification.EntityState, ['switchover', 'oper_status'], name, value)
  File "/Users/ygorelik/ydk-gen/venv/lib/python3.7/site-packages/ydk/types/py_types.py", line 387, in _perform_setattr
    format(name, self.__class__.__name__))
ydk.errors.YModelError: Attempt to assign unknown attribute 'yang_name' to 'EntityState'.
```

## System Information

```
(venv) Yakovs-Air:ydk-gen ygorelik$ pip list | grep ydk
ydk                         0.8.4
ydk-models-cisco-ios-xe     16.9.3     
ydk-models-cisco-ios-xr     6.6.2      
ydk-models-cisco-ios-xr-663 6.6.3      
ydk-models-ietf             0.1.5.post2
ydk-models-openconfig       0.1.6.post1
ydk-models-ydktest          0.1.0      
ydk-models-ydktest-oc-nis   0.1.0      
ydk-service-gnmi            0.4.0.post4
```

**Comment by ygorelik** [comment]
The issue appears due to use of 'entity' node name in the YANG model. The generated code contains two same level classes:

```
class Snmp(Entity):

    class Notification(Entity):

        class Entity(Entity):
            def __init__(self):
                super(Snmp.Notification.Entity, self).__init__()

        class EntityState(Entity):
            def __init__(self):
                super(Snmp.Notification.EntityState, self).__init__()
```
The Python interpreter gets confused when setting supper class, which must be ydk.types.Entity.

**Comment by 111pontes** [comment]
Is testing coverage pending for this?

**Comment by ygorelik** [comment]
The solution has already been tested. The code currently in my fork, branch 0.8.5. I will create pull request to merge it to CiscoDevNet master branch when I finish working on documentation. After pull request is accepted I will close all issues, which are currently in Ready state.

Yan
