### ISSUE TITLE
Installation Failure on Ubuntu 18.04.4 LTS - Python Virtual Environment

### ISSUE THREAD

**Issue by uvindhu** [CiscoDevNet/ydk-gen#994]
## Expected Behavior
YDK Core, IETF, OpenConfig, XR models installed successfully on Python Virtual Environment.

## Current Behavior
pip install ydk-models-cisco-ios-xr <=> Installation failed with following log attached.

## Steps to Reproduce
source bin/activate
pip install ydk-models-cisco-ios-xr

## Your Script
sudo apt-get install gdebi-core python3-dev python-dev libtool-bin
sudo apt-get install libcurl4-openssl-dev libpcre3-dev libssh-dev libxml2-dev libxslt1-dev cmake
wget https://devhub.cisco.com/artifactory/debian-ydk/0.8.3/bionic/libydk-0.8.3-1.amd64.deb
sudo gdebi libydk-0.8.3-1.amd64.deb
cd ~/<folder name>
virtualenv -p python3 .
source bin/activate
pip install ydk-models-cisco-ios-xr

## Logs

(ncclient) uvindhu@vm-1:~/ncclient$ pip install ydk-models-cisco-ios-xr
Collecting ydk-models-cisco-ios-xr
  Downloading ydk-models-cisco-ios-xr-6.6.3.tar.gz (33.0 MB)
     |████████████████████████████████| 33.0 MB 17 kB/s 
Collecting ydk>=0.8.4
  Using cached ydk-0.8.4.tar.gz (33 kB)
Collecting ydk-models-ietf>=0.1.5.post2
  Using cached ydk-models-ietf-0.1.5.post2.tar.gz (210 kB)
Requirement already satisfied: pybind11>=2.1.1 in ./lib/python3.6/site-packages (from ydk>=0.8.4->ydk-models-cisco-ios-xr) (2.5.0)
Building wheels for collected packages: ydk-models-cisco-ios-xr, ydk, ydk-models-ietf
  Building wheel for ydk-models-cisco-ios-xr (setup.py) ... done
  Created wheel for ydk-models-cisco-ios-xr: filename=ydk_models_cisco_ios_xr-6.6.3-py2.py3-none-any.whl size=35526280 sha256=225a7afc6aaf39357f6e8c6f643cf8afec512e0f8117e67a96a9dce63472523b
  Stored in directory: /home/uvindhu/.cache/pip/wheels/da/f9/47/f68f1d64d3879693a903697e00b7dce063f89e917a78989262
  Building wheel for ydk (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/uvindhu/ncclient/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-pjrepcyg/ydk/setup.py'"'"'; __file__='"'"'/tmp/pip-install-pjrepcyg/ydk/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-z03zp84g
       cwd: /tmp/pip-install-pjrepcyg/ydk/
  Complete output (123 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/ydk
  copying ydk/exthook.py -> build/lib.linux-x86_64-3.6/ydk
  copying ydk/__init__.py -> build/lib.linux-x86_64-3.6/ydk
  creating build/lib.linux-x86_64-3.6/ydk/errors
  copying ydk/errors/error_handler.py -> build/lib.linux-x86_64-3.6/ydk/errors
  copying ydk/errors/__init__.py -> build/lib.linux-x86_64-3.6/ydk/errors
  creating build/lib.linux-x86_64-3.6/ydk/filters
  copying ydk/filters/__init__.py -> build/lib.linux-x86_64-3.6/ydk/filters
  creating build/lib.linux-x86_64-3.6/ydk/types
  copying ydk/types/__init__.py -> build/lib.linux-x86_64-3.6/ydk/types
  copying ydk/types/py_types.py -> build/lib.linux-x86_64-3.6/ydk/types
  creating build/lib.linux-x86_64-3.6/ydk/_core
  copying ydk/_core/_importer.py -> build/lib.linux-x86_64-3.6/ydk/_core
  copying ydk/_core/_dm_meta_info.py -> build/lib.linux-x86_64-3.6/ydk/_core
  copying ydk/_core/__init__.py -> build/lib.linux-x86_64-3.6/ydk/_core
  creating build/lib.linux-x86_64-3.6/ydk/ext
  copying ydk/ext/__init__.py -> build/lib.linux-x86_64-3.6/ydk/ext
  creating build/lib.linux-x86_64-3.6/ydk/path
  copying ydk/path/__init__.py -> build/lib.linux-x86_64-3.6/ydk/path
  creating build/lib.linux-x86_64-3.6/ydk/providers
  copying ydk/providers/netconf_provider.py -> build/lib.linux-x86_64-3.6/ydk/providers
  copying ydk/providers/__init__.py -> build/lib.linux-x86_64-3.6/ydk/providers
  copying ydk/providers/codec_provider.py -> build/lib.linux-x86_64-3.6/ydk/providers
  creating build/lib.linux-x86_64-3.6/ydk/services
  copying ydk/services/netconf_service.py -> build/lib.linux-x86_64-3.6/ydk/services
  copying ydk/services/crud_service.py -> build/lib.linux-x86_64-3.6/ydk/services
  copying ydk/services/executor_service.py -> build/lib.linux-x86_64-3.6/ydk/services
  copying ydk/services/__init__.py -> build/lib.linux-x86_64-3.6/ydk/services
  copying ydk/services/codec_service.py -> build/lib.linux-x86_64-3.6/ydk/services
  creating build/lib.linux-x86_64-3.6/ydk/entity_utils
  copying ydk/entity_utils/entity_utils.py -> build/lib.linux-x86_64-3.6/ydk/entity_utils
  copying ydk/entity_utils/__init__.py -> build/lib.linux-x86_64-3.6/ydk/entity_utils
  creating build/lib.linux-x86_64-3.6/ydk/models
  copying ydk/models/__init__.py -> build/lib.linux-x86_64-3.6/ydk/models
  creating build/lib.linux-x86_64-3.6/ydk/logging
  copying ydk/logging/__init__.py -> build/lib.linux-x86_64-3.6/ydk/logging
  creating build/lib.linux-x86_64-3.6/ydk/path/sessions
  copying ydk/path/sessions/restconf_session.py -> build/lib.linux-x86_64-3.6/ydk/path/sessions
  copying ydk/path/sessions/netconf_session.py -> build/lib.linux-x86_64-3.6/ydk/path/sessions
  copying ydk/path/sessions/__init__.py -> build/lib.linux-x86_64-3.6/ydk/path/sessions
  running build_ext
  -- The C compiler identification is GNU 7.5.0
  -- The CXX compiler identification is GNU 7.5.0
  -- Check for working C compiler: /usr/bin/cc
  -- Check for working C compiler: /usr/bin/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: /usr/bin/c++
  -- Check for working CXX compiler: /usr/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  python version: 3.6m
  -- Found PythonLibs: /usr/local/lib/libpython3.6m.a (found version "3.6.6")
  pybind11 include: /home/uvindhu/ncclient/lib/python3.6/site-packages/pybind11/include;/home/uvindhu/ncclient/lib/python3.6/site-packages/pybind11/include
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /tmp/pip-install-pjrepcyg/ydk/build/temp.linux-x86_64-3.6
  Scanning dependencies of target ydk_
  [ 50%] Building CXX object CMakeFiles/ydk_.dir/python.cpp.o
  /tmp/pip-install-pjrepcyg/ydk/python.cpp: In lambda function:
  /tmp/pip-install-pjrepcyg/ydk/python.cpp:541:39: warning: unused parameter ‘left’ [-Wunused-parameter]
           .def("__eq__", [](ydk::Empty& left, ydk::Empty& right)
                                         ^~~~
  /tmp/pip-install-pjrepcyg/ydk/python.cpp:541:57: warning: unused parameter ‘right’ [-Wunused-parameter]
           .def("__eq__", [](ydk::Empty& left, ydk::Empty& right)
                                                           ^~~~~
  /tmp/pip-install-pjrepcyg/ydk/python.cpp: In lambda function:
  /tmp/pip-install-pjrepcyg/ydk/python.cpp:545:39: warning: unused parameter ‘left’ [-Wunused-parameter]
           .def("__ne__", [](ydk::Empty& left, ydk::Empty& right)
                                         ^~~~
  /tmp/pip-install-pjrepcyg/ydk/python.cpp:545:57: warning: unused parameter ‘right’ [-Wunused-parameter]
           .def("__ne__", [](ydk::Empty& left, ydk::Empty& right)
                                                           ^~~~~
  [100%] Linking CXX shared module ../lib.linux-x86_64-3.6/ydk_.so
  /usr/bin/ld: /usr/local/lib/libpython3.6m.a(ceval.o): relocation R_X86_64_PC32 against symbol `_Py_NoneStruct' can not be used when making a shared object; recompile with -fPIC
  /usr/bin/ld: final link failed: Bad value
  collect2: error: ld returned 1 exit status
  CMakeFiles/ydk_.dir/build.make:102: recipe for target '../lib.linux-x86_64-3.6/ydk_.so' failed
  make[2]: *** [../lib.linux-x86_64-3.6/ydk_.so] Error 1
  CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/ydk_.dir/all' failed
  make[1]: *** [CMakeFiles/ydk_.dir/all] Error 2
  Makefile:83: recipe for target 'all' failed
  make: *** [all] Error 2
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-pjrepcyg/ydk/setup.py", line 145, in <module>
      zip_safe=False,
    File "/home/uvindhu/ncclient/lib/python3.6/site-packages/setuptools/__init__.py", line 144, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/uvindhu/ncclient/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/usr/local/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-pjrepcyg/ydk/setup.py", line 68, in run
      self.build_extension(ext)
    File "/tmp/pip-install-pjrepcyg/ydk/setup.py", line 101, in build_extension
      subprocess.check_call([cmake_executable, '--build', '.'], cwd=self.build_temp)
    File "/usr/local/lib/python3.6/subprocess.py", line 291, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '--build', '.']' returned non-zero exit status 2.
  ----------------------------------------
  ERROR: Failed building wheel for ydk
  Running setup.py clean for ydk
  Building wheel for ydk-models-ietf (setup.py) ... done
  Created wheel for ydk-models-ietf: filename=ydk_models_ietf-0.1.5.post2-py2.py3-none-any.whl size=248888 sha256=e8ca1a1d98db0ae1d071ad152eb260dc7400b3a8f3421d36cbb08ac4bd87a007
  Stored in directory: /home/uvindhu/.cache/pip/wheels/f5/1d/5f/df42d10920e70bc070039b95c2eec6ab25f64ba6eac09a7581
Successfully built ydk-models-cisco-ios-xr ydk-models-ietf
Failed to build ydk
Installing collected packages: ydk, ydk-models-ietf, ydk-models-cisco-ios-xr
    Running setup.py install for ydk ... error
    ERROR: Command errored out with exit status 1:
     command: /home/uvindhu/ncclient/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-pjrepcyg/ydk/setup.py'"'"'; __file__='"'"'/tmp/pip-install-pjrepcyg/ydk/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-uccxvmie/install-record.txt --single-version-externally-managed --compile --install-headers /home/uvindhu/ncclient/include/site/python3.6/ydk
         cwd: /tmp/pip-install-pjrepcyg/ydk/
    Complete output (125 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/ydk
    copying ydk/exthook.py -> build/lib.linux-x86_64-3.6/ydk
    copying ydk/__init__.py -> build/lib.linux-x86_64-3.6/ydk
    creating build/lib.linux-x86_64-3.6/ydk/errors
    copying ydk/errors/error_handler.py -> build/lib.linux-x86_64-3.6/ydk/errors
    copying ydk/errors/__init__.py -> build/lib.linux-x86_64-3.6/ydk/errors
    creating build/lib.linux-x86_64-3.6/ydk/filters
    copying ydk/filters/__init__.py -> build/lib.linux-x86_64-3.6/ydk/filters
    creating build/lib.linux-x86_64-3.6/ydk/types
    copying ydk/types/__init__.py -> build/lib.linux-x86_64-3.6/ydk/types
    copying ydk/types/py_types.py -> build/lib.linux-x86_64-3.6/ydk/types
    creating build/lib.linux-x86_64-3.6/ydk/_core
    copying ydk/_core/_importer.py -> build/lib.linux-x86_64-3.6/ydk/_core
    copying ydk/_core/_dm_meta_info.py -> build/lib.linux-x86_64-3.6/ydk/_core
    copying ydk/_core/__init__.py -> build/lib.linux-x86_64-3.6/ydk/_core
    creating build/lib.linux-x86_64-3.6/ydk/ext
    copying ydk/ext/__init__.py -> build/lib.linux-x86_64-3.6/ydk/ext
    creating build/lib.linux-x86_64-3.6/ydk/path
    copying ydk/path/__init__.py -> build/lib.linux-x86_64-3.6/ydk/path
    creating build/lib.linux-x86_64-3.6/ydk/providers
    copying ydk/providers/netconf_provider.py -> build/lib.linux-x86_64-3.6/ydk/providers
    copying ydk/providers/__init__.py -> build/lib.linux-x86_64-3.6/ydk/providers
    copying ydk/providers/codec_provider.py -> build/lib.linux-x86_64-3.6/ydk/providers
    creating build/lib.linux-x86_64-3.6/ydk/services
    copying ydk/services/netconf_service.py -> build/lib.linux-x86_64-3.6/ydk/services
    copying ydk/services/crud_service.py -> build/lib.linux-x86_64-3.6/ydk/services
    copying ydk/services/executor_service.py -> build/lib.linux-x86_64-3.6/ydk/services
    copying ydk/services/__init__.py -> build/lib.linux-x86_64-3.6/ydk/services
    copying ydk/services/codec_service.py -> build/lib.linux-x86_64-3.6/ydk/services
    creating build/lib.linux-x86_64-3.6/ydk/entity_utils
    copying ydk/entity_utils/entity_utils.py -> build/lib.linux-x86_64-3.6/ydk/entity_utils
    copying ydk/entity_utils/__init__.py -> build/lib.linux-x86_64-3.6/ydk/entity_utils
    creating build/lib.linux-x86_64-3.6/ydk/models
    copying ydk/models/__init__.py -> build/lib.linux-x86_64-3.6/ydk/models
    creating build/lib.linux-x86_64-3.6/ydk/logging
    copying ydk/logging/__init__.py -> build/lib.linux-x86_64-3.6/ydk/logging
    creating build/lib.linux-x86_64-3.6/ydk/path/sessions
    copying ydk/path/sessions/restconf_session.py -> build/lib.linux-x86_64-3.6/ydk/path/sessions
    copying ydk/path/sessions/netconf_session.py -> build/lib.linux-x86_64-3.6/ydk/path/sessions
    copying ydk/path/sessions/__init__.py -> build/lib.linux-x86_64-3.6/ydk/path/sessions
    running build_ext
    -- The C compiler identification is GNU 7.5.0
    -- The CXX compiler identification is GNU 7.5.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    python version: 3.6m
    -- Found PythonLibs: /usr/local/lib/libpython3.6m.a (found version "3.6.6")
    pybind11 include: /home/uvindhu/ncclient/lib/python3.6/site-packages/pybind11/include;/home/uvindhu/ncclient/lib/python3.6/site-packages/pybind11/include
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /tmp/pip-install-pjrepcyg/ydk/build/temp.linux-x86_64-3.6
    Scanning dependencies of target ydk_
    [ 50%] Building CXX object CMakeFiles/ydk_.dir/python.cpp.o
    /tmp/pip-install-pjrepcyg/ydk/python.cpp: In lambda function:
    /tmp/pip-install-pjrepcyg/ydk/python.cpp:541:39: warning: unused parameter ‘left’ [-Wunused-parameter]
             .def("__eq__", [](ydk::Empty& left, ydk::Empty& right)
                                           ^~~~
    /tmp/pip-install-pjrepcyg/ydk/python.cpp:541:57: warning: unused parameter ‘right’ [-Wunused-parameter]
             .def("__eq__", [](ydk::Empty& left, ydk::Empty& right)
                                                             ^~~~~
    /tmp/pip-install-pjrepcyg/ydk/python.cpp: In lambda function:
    /tmp/pip-install-pjrepcyg/ydk/python.cpp:545:39: warning: unused parameter ‘left’ [-Wunused-parameter]
             .def("__ne__", [](ydk::Empty& left, ydk::Empty& right)
                                           ^~~~
    /tmp/pip-install-pjrepcyg/ydk/python.cpp:545:57: warning: unused parameter ‘right’ [-Wunused-parameter]
             .def("__ne__", [](ydk::Empty& left, ydk::Empty& right)
                                                             ^~~~~
    [100%] Linking CXX shared module ../lib.linux-x86_64-3.6/ydk_.so
    /usr/bin/ld: /usr/local/lib/libpython3.6m.a(ceval.o): relocation R_X86_64_PC32 against symbol `_Py_NoneStruct' can not be used when making a shared object; recompile with -fPIC
    /usr/bin/ld: final link failed: Bad value
    collect2: error: ld returned 1 exit status
    CMakeFiles/ydk_.dir/build.make:102: recipe for target '../lib.linux-x86_64-3.6/ydk_.so' failed
    make[2]: *** [../lib.linux-x86_64-3.6/ydk_.so] Error 1
    CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/ydk_.dir/all' failed
    make[1]: *** [CMakeFiles/ydk_.dir/all] Error 2
    Makefile:83: recipe for target 'all' failed
    make: *** [all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-pjrepcyg/ydk/setup.py", line 145, in <module>
        zip_safe=False,
      File "/home/uvindhu/ncclient/lib/python3.6/site-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/uvindhu/ncclient/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/usr/local/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/local/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-pjrepcyg/ydk/setup.py", line 68, in run
        self.build_extension(ext)
      File "/tmp/pip-install-pjrepcyg/ydk/setup.py", line 101, in build_extension
        subprocess.check_call([cmake_executable, '--build', '.'], cwd=self.build_temp)
      File "/usr/local/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '--build', '.']' returned non-zero exit status 2.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/uvindhu/ncclient/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-pjrepcyg/ydk/setup.py'"'"'; __file__='"'"'/tmp/pip-install-pjrepcyg/ydk/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-uccxvmie/install-record.txt --single-version-externally-managed --compile --install-headers /home/uvindhu/ncclient/include/site/python3.6/ydk Check the logs for full command output.

## System Information
Python Version - 3.6.6
OS - Ubuntu 18.04.4 x64

(ncclient) uvindhu@vm-1:~/ncclient$ pip freeze
bcrypt==3.1.7
bitarray==1.2.1
cffi==1.14.0
cryptography==2.9
enum34==1.1.10
lxml==4.5.0
ncclient==0.6.7
paramiko==2.7.1
pyang==2.2.1
pyangbind==0.8.1
pybind11==2.5.0
pycparser==2.20
PyNaCl==1.3.0
regex==2020.4.4
six==1.14.0
xmltodict==0.12.0

**Comment by uvindhu** [comment]
I have resolved the above issue. Python needs to be installed with --enable-shared option.

cd <compilation-directory>
tar jvzf Python-3.6.6.tar.bz2
cd Python-3.6.6
./configure --enable-shared
make
sudo make install
