### ISSUE TITLE
Open-Config Interface IP address read not working

### ISSUE THREAD

**Issue by uvindhu** [CiscoDevNet/ydk-gen#995]
## Expected Behavior
Read and print IP address of the interface. - Cisco Always on CSR router used.
10.10.20.48

## Current Behavior
Traceback (most recent call last):
  File "test.py", line 35, in <module>
    print(gig1.subinterfaces.subinterface[0].ipv4.addresses.address[0].ip)
  File "/home/uvindhu/ncclient/lib/python3.6/site-packages/ydk/types/py_types.py", line 776, in __getitem__
    entity = self._entity_map[format(item)]
KeyError: '0'

## Your Script

from ydk.services import CRUDService
from ydk.providers import NetconfServiceProvider
from ydk.models.openconfig.openconfig_interfaces import Interfaces
from datetime import timedelta
from ydk.errors import YError

provider = NetconfServiceProvider(address="ios-xe-mgmt.cisco.com", port=10000,    username="root", password="D_Vay!_10&",      protocol="ssh")
crud = CRUDService()
interfaces= Interfaces()
interface = interfaces.Interface()
interface.name = 'GigabitEthernet1'
subinterface = interface.subinterfaces.Subinterface()
subinterface.index = 0
subinterface.ipv4 = subinterface.Ipv4()
interface.subinterfaces.subinterface.append(subinterface)
interfaces.interface.append(interface)
try:
	gig1 = crud.read(provider, interface)
	print(gig1.subinterfaces.subinterface[0].ipv4.addresses.address[0].ip)
except YError:
	print('An error occurred reading interfaces.')
exit()

## System Information
Python 3.6.6
Ubuntu 18.04 LTS

**Comment by uvindhu** [comment]
https://community.cisco.com/t5/yang-development-kit-ydk/getting-ip-address-via-openconfig-models/m-p/4081751#M1473

Above discussion was raised on Cisco Community.
